common/static/coffee/spec/discussion/discussion_spec_helper.coffee, common/static/coffee/spec/discussion/view/new_post_view_spec.coffee, common/static/coffee/src/discussion/views/new_post_view.coffee
Hides the cohort dropdown menu when it does not apply.
=> Hide "Visible To" dropdown for non-cohorted inline discussions

lms/djangoapps/courseware/module_render.py, lms/djangoapps/courseware/tests/test_module_render.py
Make sure that unicode and unicode-encoded strings do not cause the hasher problems.
=> Xblock external ui/resource hash check

lms/djangoapps/courseware/module_render.py, lms/djangoapps/courseware/tests/test_module_render.py
md5 does not accept Unicode objects, only raw strings. This ensures a raw string is always used in a straightforward way for this purpose, and mirrors the upstream change for the same fix.
=> Fix issue where unicode encodings caused XBlock rendering to fail.

common/static/coffee/src/discussion/views/discussion_thread_view.coffee
A section of the initial hotfix no longer applies and needed to be removed for functionality to be restored.
=> Remove broken hotfix remnant.

lms/djangoapps/django_comment_client/base/views.py
Fixes issue where updating a thread will cause a 'Topic does not exist' message in the case that a user does not explicitly select a topic.
=> Allow for us of the old commentable_id if the user does not select a topic

lms/djangoapps/api_manager/courses/tests.py, lms/djangoapps/api_manager/groups/tests.py, lms/djangoapps/api_manager/users/tests.py
@chrisndodge @martynjames fixed some broken tests. Course end dates are now in past and as a result of it grading events were not captured.
=> fixed some broken tests

lms/djangoapps/django_comment_client/base/views.py, lms/djangoapps/django_comment_client/tests/test_utils.py, lms/djangoapps/django_comment_client/utils.py
When two or more instances of Discussion XBlock were configured with the same discussion target (Category/Subcategory), only one of the blocks would be shown on the Course Discussion page. This was the source of several bugs when trying to edit discussion threads.
This patch adds incrementing numbers to the title of each duplicate subcategory when rendering the Course Discussion to make sure that all of the threads are visible in Course Discussion. The screenshot below shows how two discussion blocks defined with the same target (Main Category / Main Subcategory) are displayed in Course Discussion.
A workaround for the issues caused by duplicate discussion targets from 9835d67a06db453efda549d509f159c0e2fb90b4 was reverted as part of this pull request because it should be no longer …
=> Fix issues with duplicate discussion targets

lms/djangoapps/progress/migrations/0003_move_cmc_data.py
@chrisndodge @martynjames @smagoun -- added a stop to the backwards data migration for the progress app, which was the acute cause of the data loss incurred back in December.  We could think about logging a follow-on story for implementing a robust backwards migration, but for now this will prevent any repeat performances.
=> mattdrayer/MCKIN-2988: Added stop to backwards data migration.

common/static/coffee/spec/discussion/discussion_spec_helper.coffee, common/templates/discussion/_underscore_templates.html
Background: This PR adds a wrapper around username and labels in discussion threads/responses to allow for nowrap styling. Styling applied via third party-hosted edX instance.
JIRA Ticket: OC-547
Partner information: 3rd party-hosted open edX instance, for an edX solutions client.
Merge deadline: 2015-03-16
=> Added wrapper around username and labels to allow for nowrap styling

lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py, lms/djangoapps/django_comment_client/tests/test_utils.py, lms/djangoapps/django_comment_client/utils.py, lms/lib/comment_client/user.py
Background: This PR adds management command to export discussion participation statistics per course.
JIRA ticket: OC-550
Dependencies: Partial dependency on https://github.com/edx-solutions/cs_comments_service/pull/13 - without it should work fine, except filtering by thread type.
Partner information: 3rd party-hosted open edX instance, for an edX solutions client.
Merge deadline: Monday, 2015-03-09.
Author concerns: there seems to be no unit tests for `lms/lib/comment_client/user.py` and for management commands in general. Due to tight deadline, this parts were left with no additional test coverage, but tested manually. Hints on how to best test them are welcome.
Testing instructions: issuing the following command as `edxapp` user should trigger export process with described results:
* …
=> Management command to export discussion participation statistics per course

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/urls.py, lms/djangoapps/api_manager/users/views.py
@marjev @martynjames -- I've posted a changeset here for you to review.  It contains a new API workflow which should return all of the user's gradebook entries.  Take a look and let me know if you need additional gradebook fields to be returned in the payload (currently just course_id, grade, proforma_grade).  Once we have the operation working to your liking, we'll merge to master.
=> mattdrayer/MCKIN-3046: Added multi-course grade query

cms/templates/studio_xblock_wrapper.html, common/test/acceptance/tests/studio/test_studio_container.py
This cherry-picks 19bd7005e6e5ec6ffc9ae08de900ac3d88d37823 (upstream PR 7496) from post-birch work upstream, since it makes editing of Problem Builder much nicer. I could swear I'd already asked for this to be included on the birch rebase branch[es] somewhere, but apparently not...
=> Consistently use display_name_with_default in Studio

cms/envs/common.py, lms/envs/common.py, requirements/edx/custom.txt
This bumps Problem Builder to the latest version.
Will fix a [DB issue](https://openedx.atlassian.net/browse/OSPR-547) as well as SOL-782 and SOL-787 - see https://github.com/open-craft/problem-builder/pull/21
=> Bump Problem Builder to latest version

requirements/edx/custom.txt
**JIRA Ticket:** [SOL-814](https://openedx.atlassian.net/browse/SOL-814)
This is one of two alternative solutions to the problem. Another solution is in platform [PR#436](https://github.com/edx-solutions/edx-platform/pull/436)
Advantages of this solution:
* edx-platform does not contain problem-builder related configuration.
Disadvantages of this solution:
* Problem builder migrations might become incompatible with modern Django (>=1.7)
=> Updated problem builder hash to use version with legacy Django migrations

requirements/edx/custom.txt
@antoviaque You introduced a small typo when you updated the hashes.
I'm not sure what the right procedure is to merge this fix.  Can I just push something like this to master directly for the solutions fork?
=> Fix typo in requirements file, making "pip install" work again

lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py, lms/djangoapps/django_comment_client/tests/management/test_export_discussion_participation.py
Previously, if it found one course without cohorted discussions, it would stop at that course with an error, even if other courses from the --all option would have cohorted discussions to export.
Now, we print out the error, but keep going through the rest of the list.
=> Don't stop with --all when one of the course doesn't have cohorted discussions

lms/djangoapps/api_manager/users/urls.py
@bradenmacdonald @antoviaque 
Low-priority PR that should only affect dev environments, which may have split courses, etc, which won't fit the old regex pattern. Xavier, we'll need a second reviewer for this.
=> Make user API use the same regex as everyone else.

requirements/edx/github.txt
This pulls in the changes in [PR #5 of the XBlock repository](https://github.com/edx-solutions/XBlock/pull/5).  See there for the code review and the thumbs up.
=> Update XBlock release hash to latest master version.

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py
JIRA ticket: https://edx-wiki.atlassian.net/browse/MCKIN-3367
Steps to reproduce:
1) update the title in profile dropdown
2) updating the name shouldn't remove the user's title
@mattdrayer I've changed the api side to fix the bug reported in the ticket linked above. Could you perhaps review this sometimes this week?
=> (MCKIN-3367) Preserve user's title upon changing user's name

common/djangoapps/student/views.py, common/djangoapps/third_party_auth/migrations/0004_auto__add_field_samlproviderconfig_autoprovision_account__add_field_oa.py, common/djangoapps/third_party_auth/models.py, common/djangoapps/third_party_auth/pipeline.py, common/djangoapps/third_party_auth/settings.py, common/djangoapps/third_party_auth/strategy.py, common/djangoapps/third_party_auth/tests/specs/test_testshib.py, common/djangoapps/third_party_auth/tests/test_pipeline.py, common/djangoapps/third_party_auth/tests/test_strategy.py, lms/envs/aws.py, lms/envs/test.py
**JIRA Ticket:** https://openedx.atlassian.net/browse/YONK-80
**PR deployment instructions:** contains a migration - make sure to run `./manage.py lms migrate --settings=devstack` or equivalent
**Testing instructions:**
1. Follow instructions at [Shibboleth Configuration](https://openedx.atlassian.net/wiki/display/OpenOPS/New+Shibboleth+Configuration) docs until step 6.
2. The easiest way to set up a second part of SAML authentication process is to use http://testshib.org
2.1. Export edX SSO metadata to a file.
2.2. Import them at ["Register" step](https://www.testshib.org/register.html) of testshib configuration (make sure the filename is unique)
2.3. When editing SAML provider config (step 6 in Shibboleth Config guide), set `urn:oid:1.3.6.1.4.1.5923.1.1.1.6` as email hint (testshib does …
=> Automatic account provisioning

cms/envs/common.py, lms/envs/common.py
This reverts commit c083c903c14d8e4aa21d9b6fe3a2b2d8193b2b02.
When groupwork fires off a notification, the platform uses the edx-notifications library to transform that notification into a URL the user can click.
Before Eugeny's change, it used a querystring parameter of 'seqid', which eugeny changed to better reflect what the parameter was actually pointing to, which was an activity. He updated it there and in Apros, visible in the other PR.
However every link that had previously been transformed was stored, causing the issue in https://openedx.atlassian.net/browse/YONK-146
All of the links used 'seqid' instead of 'actid'. New notifications, once the platform was updated, would use 'actid', but this hasn't happened in production yet since the production settings were never changed to use …
=> Revert "Updated GP v1 notifications URL resolver to use new querystring attribute"

lms/djangoapps/verify_student/migrations/0004_auto__add_verificationcheckpoint__add_unique_verificationcheckpoint_co.py
The shortening call here will create a table name that conflicts with a model table, and things appear to work just fine without it.
=> Remove south table shortening call.

cms/djangoapps/models/settings/course_metadata.py, common/test/acceptance/pages/studio/settings_advanced.py, lms/djangoapps/django_comment_client/base/tests.py, lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py, lms/djangoapps/django_comment_client/tests/management/test_export_discussion_participation.py, openedx/core/djangoapps/course_groups/admin.py, openedx/core/djangoapps/course_groups/management/commands/convert_cohort_format.py, openedx/core/djangoapps/course_groups/management/commands/tests/test_convert_cohort_format.py, openedx/core/djangoapps/course_groups/models.py
This PR:
1. Removes cohort_config from advanced settings since that setting is no longer respected.
2. Adds an Admin view for the new CourseCohortSettings model, since our course authors do not have access to the LMS
3. Updates existing code to use the API for getting course cohort settings.
4. Adds a command to convert cohort_config settings so that they will be properly understood by the lazy converter upstream made. The command needs to be run before interfacing with any of the courses. If you've already run a cypress branch, you will likely need to clear out all CourseCohortSettings objects from the DB. you can do this with CourseCohortSettings.objects.all().delete() or by truncating the relevant table.
See https://openedx.atlassian.net/browse/YONK-171
To test:
1. Use master to set up …
=> Cohort changes

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py, lms/djangoapps/gradebook/management/commands/generate_gradebook_entries.py
@vkaracic can you test to see if this works for you on your local devstack when you:
@mattdrayer I added a piece of code that will handle the situation that we discussed on hipchat. I added logging in case a user finds himself in a situation like that and wrote a test case when there is no gradebook entry for user/course combination in the db and a request was made to get that gradebook entry.
=> (YONK-158) Create new gradebook entry for new course/user

requirements/edx/custom.txt, requirements/edx/github.txt
Updating github.txt xblock-utils hash to match custom.txt version, since deployments install [custom requirements](https://github.com/edx/configuration/blob/368b717b4ac8dae96a9db6af4ab3aea4b4618c91/playbooks/roles/edxapp/tasks/deploy.yml#L168) just before [github requirements](https://github.com/edx/configuration/blob/368b717b4ac8dae96a9db6af4ab3aea4b4618c91/playbooks/roles/edxapp/tasks/deploy.yml#L179) and github installs outdated version.
=> XBlock-utils hash update

common/djangoapps/third_party_auth/api/tests/test_views.py, common/djangoapps/third_party_auth/api/urls.py, common/djangoapps/third_party_auth/api/views.py, common/djangoapps/third_party_auth/models.py, common/djangoapps/third_party_auth/pipeline.py, common/djangoapps/third_party_auth/tests/test_pipeline.py, lms/urls.py
**Description**:
This is a solutions cherry-pick of an upstream PR that implements a new API that can be used to retrieve a list of third party auth providers linked to the given user's account.
**Upstream PR**: https://github.com/edx/edx-platform/pull/9672
**JIRA**: [YONK-123](https://openedx.atlassian.net/browse/YONK-123)
**Arch council**: This API spec has been reviewed by the arch council and is not yet formally approved but has no outstanding issues/controversy. [See proposal + discussion.](https://docs.google.com/document/d/1lZT45A9CxX2bRm4k5cBEYgrbnkvyUwaQet-01kY9iWk/edit)
**Reviewers**: @e-kolpakov and TBD
**Test Instructions**:
1. Enable one or more third party auth providers (such as 'Dummy') and link them to user's accounts.
2. View the new API by going to URLs like …
=> Initial implementation of API for listing a user's third party auth providers

openedx/core/djangoapps/course_groups/management/commands/convert_cohort_format.py, openedx/core/djangoapps/course_groups/management/commands/tests/test_convert_cohort_format.py
Cohorted discussion IDs were not being properly handled and merged for conversion. See https://openedx.atlassian.net/browse/YONK-211
@bradenmacdonald @smarnach Please review at first opportunity so we can get this in the release if possible.
=> Merge course discussion IDs for cohort config conversion.

cms/envs/common.py, lms/envs/common.py, requirements/edx/custom.txt
**Background:** Group Project XBlock sends notifications for file upload, grades posted and stage open/close dates. Group Project v2 sends the same types of messages, but uses different navigation approach, so the URLs in messages need to be different. For this to work, GP v2 has to send messages of unique types. 
**Description:** This PR switches GP v2 to use dedicated message types. Note this PR is likely slightly incomplete, as it should include a hash update of edx-notifications. If edx-notifications PR is merged before this one, the hash will be updated as part of this PR; otherwise, there would be a separate PR for that.
**Dependencies:** This PR is one of the three that fix notifications in Group Project v2 XBlock; the other two are:
* …
=> Default URL resolvers for GP v2 notifications

common/djangoapps/third_party_auth/pipeline.py, common/djangoapps/third_party_auth/settings.py, common/djangoapps/third_party_auth/strategy.py, common/djangoapps/third_party_auth/templates/third_party_auth/post_custom_auth_entry.html, common/djangoapps/third_party_auth/tests/specs/test_google.py, common/djangoapps/third_party_auth/tests/test_strategy.py, common/djangoapps/third_party_auth/urls.py, common/djangoapps/third_party_auth/views.py, lms/djangoapps/api_manager/sessions/views.py, lms/envs/aws.py, lms/envs/test.py
This PR makes a simple change to `third_party_auth` so that we can configure "custom auth entry points" on a server. This basically means we can have a custom URL acting as the login/register page, and it will be correctly integrated with the SSO pipeline. It can be an internal URL that's part of the LMS or an external URL.
This PR also tweaks the solutions server API so that we can login a user by "upgrading" their existing anonymous session rather than creating a new session. This is required to preserve the third_party_auth pipeline during SSO logins.
**JIRA**: This is part of [YONK-81](https://openedx.atlassian.net/browse/YONK-81)
**For more context and real world use**: See Apros PR 1189.
**Example**:
First, one would configure a custom auth entry point called `marketing` in …
=> Custom SSO entry points

common/djangoapps/third_party_auth/strategy.py, common/djangoapps/third_party_auth/tests/test_strategy.py, lms/envs/aws.py
**Description:** If LMS is set up to run behind a reverse proxy, the external host and port for TPA request are not the same as internal ones. `python-social-auth` can only grab internal values, so it results in "Response was received at wrong address" authentication errors.
Common practice is to set up X-Forwarded-* headers to keep information about initial request target. Some web-servers (i.e. gunicorn) honors these headers and, if present, pass their values to Django as real host and port. Other servers does not do that (i.e. django development server used in dev environments). This PR adds an explicit support for X-Forwarded-Port and X-Forwarded-Host headers, using them for purposes of checking the TPA response destination.
**Related JIRA Ticket:** …
=> Third party auth: Support for running behind a reverse proxy on a non-standard port

lms/djangoapps/api_manager/sessions/views.py
This is a quick follow-up to #529. This adds an explanatory comment to the new API functionality, per @mattdrayer's [suggestion](https://github.com/edx-solutions/edx-platform/pull/529#discussion_r40257375).
=> Add explanatory comment to new sessions API

lms/startup.py
**Description:** Notifications startup sequence causes importing lms/urls.py. Since it was the first step in LMS startup sequence, urls.py was processed before other apps (i.e. third_party_auth) had a chance to add themselves (and dependencies) to INSTALLED_APPS. As a result, third_party_auth did not work when notifications were enabled.
**Technical details:** The app that actually imported urls.py was `djdebug` - so the issue might not exist in environments with djdebug disabled.
**Testing Instructions:**
1. Enable both TPA and Notifications in lms.env.json -> Features (set ENABLE_NOTIFICATIONS and ENABLE_THIRD_PARTY_AUTH to true)
2. Check that notifications works (i.e. using Group Project, or just progressing through the course so that "You're number N in the cohort for Progression" …
=> [YONK-148] Third party auth and Notifications conflict

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py
**Description:** When existing username or email is used, LMS API fails to register users (which is right), but provides misleading error message "User '%username' already exists". This message does not reflect that conflict might be caused by duplicate email, rather than username.
This PR updates the message to reflect the fact that either username or email could have caused the conflict.
**Test instructions:**
Try three different scenarios: 
1. Username is unique, email already taken
1. Username already taken, email is unique
1. Both username and email already taken
To test this, use an external REST client (i.e. curl, Postman): send POST to `/api/server/users` with the following content:
{
"username": "Existing username",
"email": "existing@email.org",
"password": "Irrelevant, but …
=> Changed error message to be more in-line with possible reasons of the problem

common/djangoapps/third_party_auth/pipeline.py, common/djangoapps/third_party_auth/tests/specs/test_testshib.py, lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py, lms/envs/test.py, openedx/core/djangoapps/course_groups/cohorts.py, openedx/core/djangoapps/course_groups/tests/test_cohorts.py
This PR extends custom entry points support by allowing custom entry points to opt-in for automatically linking accounts by email.
Test instructions - part of two-PR changeset - instructions are given on the [other one](https://github.com/mckinseyacademy/mcka_apros/pull/1215) (not testable without third party app anyway).
=> Support for linking accounts by email for custom entry points

common/djangoapps/third_party_auth/pipeline.py, common/djangoapps/third_party_auth/tests/specs/test_google.py, common/djangoapps/third_party_auth/views.py
This is a simple follow-up to #529. It improves slightly on that PR by adding a bit more data that is sent to the custom registration form.
Previously, the custom registration form page/app (e.g. Apros "finalize SSO registration" view) would only get user details like name, email, etc. but could not directly tell what company's SAML provider was being used.
Test instructions: See related PR on the private Apros repository.
=> Send provider ID to custom SSO auth entry points

requirements/edx/custom.txt
Hash update to include https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/37 .
=> Bump DnDv2 hash to include fix for MCKIN-3560

requirements/edx/custom.txt
This bumps the hash of Group Work v2 to include changes already reviewed in: 
- https://github.com/open-craft/xblock-group-project-v2/pull/83
=> Update hash of group work v2

requirements/edx/custom.txt
Bump the problem builder hash so that we include an important hotfix (exponential slowdown in large step builder assessments).
=> Apply hotfix version hash for problem builder

lms/djangoapps/api_manager/users/views.py, lms/djangoapps/organizations/serializers.py, lms/djangoapps/organizations/tests.py, lms/djangoapps/organizations/views.py
@smagoun this PR supports YONK-281. We are simplifying Organization list and retrieve APIs and creating separate endpoints to get organization user, groups and workgroups.
@mattdrayer could you please review?
=> Improve performance of Organization list and retrieve APIs

cms/djangoapps/contentstore/tests/test_import.py, cms/djangoapps/contentstore/tests/test_libraries.py, cms/djangoapps/contentstore/views/tests/test_group_configurations.py, cms/envs/common.py, lms/djangoapps/api_manager/courses/tests.py, lms/djangoapps/api_manager/courses/views.py, lms/djangoapps/api_manager/courseware_access.py, lms/djangoapps/api_manager/models.py, lms/djangoapps/api_manager/receivers.py, lms/envs/common.py, openedx/core/djangoapps/content/__init__.py, openedx/core/djangoapps/content/course_metadata/migrations/0001_initial.py, openedx/core/djangoapps/content/course_metadata/models.py, openedx/core/djangoapps/content/course_metadata/signals.py, openedx/core/djangoapps/content/course_metadata/tasks.py, openedx/core/djangoapps/content/course_metadata/test_utils.py, openedx/core/djangoapps/content/course_metadata/tests.py, openedx/core/djangoapps/content/course_metadata/utils.py, openedx/core/djangoapps/content/course_structures/tests.py, openedx/core/djangoapps/util/testing.py
This PR creates `CourseAggregatedMetaData` model to store course aggregates. For we have two fields  `total_assessments` and `total_modules` in this model. We are using value of `total_assessments` in `CoursesMetricsCompletionsLeadersList` API. We update relevant data on of course on `course_published` signal. @mattdrayer could you please review?.
=> ziafazal/YONK-280: add course aggregate meta date model

lms/djangoapps/api_manager/courses/content.py, lms/djangoapps/api_manager/courses/tasks.py, lms/djangoapps/api_manager/courses/tests.py, lms/djangoapps/api_manager/courses/views.py
@ziafazal please review. This PR updates api_manager.courses.views.CoursesStaticTabsDetail and api_manager.courses.views.CoursesStaticTabsList to cache contents of static tabs for 5 minutes if content length is not more than 4KB.
=> Update static tabs APIs to cache tab contents

cms/djangoapps/contentstore/tests/test_crud.py, lms/djangoapps/instructor_task/tests/test_base.py, lms/envs/test.py, lms/startup.py, openedx/core/djangoapps/content/__init__.py, openedx/core/djangoapps/content/course_metadata/__init__.py, openedx/core/djangoapps/content/course_metadata/signals.py, openedx/core/djangoapps/content/course_metadata/tests.py, openedx/core/djangoapps/content/course_overviews/signals.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/content/course_structures/__init__.py, openedx/core/djangoapps/content/course_structures/api/v0/tests_api.py, openedx/core/djangoapps/content/course_structures/signals.py, openedx/core/djangoapps/util/testing.py
Disconnecting signals after test run to avoid being called by other tests and to reduce Circle CI tests run time.
@msaqib52 FYI.
=> disconnect signals to improve tests time

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py
This PR fixes a bug where user's gradebook is generated ever if he/she is not enrolled in given course. 
@mattdrayer would you please review it?
=> ziafazal/YONK-288: user should be enrolled in the course before grade book is generated

cms/envs/aws.py, cms/envs/common.py, lms/djangoapps/progress/signals.py, lms/djangoapps/progress/tests.py, lms/envs/aws.py, lms/envs/common.py, openedx/core/djangoapps/content/course_metadata/test_utils.py, openedx/core/djangoapps/content/course_metadata/utils.py
This  PR further refines code related to user's progress calculations. We have to exclude those `verticals` if they have any unit having these categories `discussion-course, group-project, gp-v2-project`.
@afzaledx would you please review?
=> ziafazal/YONK-309-ignore-verticals: ignore some verticals from progress calculations

lms/djangoapps/api_manager/users/serializers.py, lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py
This PR updates users list API to return following new fields:
- last_login
- number of enrolled courses
- permission groups(roles)
also adds following new filters:
- full name(attribute name in auth_userprofile)
- organizations(organizations user belongs to)
- courses(user is enrolled in)
and removes filter requirement so we can get users without supplying any filter.
@ziafazal please review
=> Update users list API

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py, lms/djangoapps/gradebook/receivers.py, lms/djangoapps/gradebook/tasks.py
This PR does two things
1) Calculates user's grades asynchronously inside a Celery task to improve response time of `grade` events.
2) Refactor user grades API to traverse course tree for grade computations only when it is required or at time we have not already computed user's grade.
@douglashall would you please review this one?
=> ziafazal/YONK-306:update gradebook asynchronously and traverse course tree only when required

lms/djangoapps/api_manager/courses/tests.py, lms/djangoapps/api_manager/courses/views.py, lms/djangoapps/gradebook/models.py
This PR has changes extend course metrics api to return these additional fields
`users_not_started`
`modules_completed`
`users_completed`
@msaqib52  would you please review this?
=> Ziafazal/yonk 295: updated course metrics API to return additional data

lms/djangoapps/gradebook/receivers.py, lms/djangoapps/gradebook/tasks.py, lms/djangoapps/gradebook/tests.py
User grade computations were moved into a Celery task but argument(course_key, user) passed to that celery task were not primitive types and as a result we were getting these errors
```
EncodeError: CourseLocator(....) is not JSON serializable
EncodeError: <User: ..> is not JSON serializable
```
when celery task is executed.
This PR fixes the issue by converting argument passed to celery task into primitive types.
@msaqib52 would you please review this?
=> fixed issue with user grades not being computed

lms/djangoapps/api_manager/management/commands/bulk_delete_courses_with_reference_data.py, lms/djangoapps/api_manager/management/commands/tests/test_bulk_delete_courses_with_reference_data.py
On McKA QA and McKA Integration environment we need to delete courses in bulk to free disk space. This PR has a new django management command to delete multiples courses where there is no activity by course authors for a certain number of days.
We can run this command on devstack like this
```
./manage.py lms bulk_delete_courses_with_reference_data --age=60  --settings=devstack
```
where `age` option is number of days.
@douglashall would you review this one?
=> Bulk course delete management command

lms/djangoapps/api_manager/management/commands/bulk_delete_courses_with_reference_data.py, lms/djangoapps/api_manager/management/commands/tests/test_bulk_delete_courses_with_reference_data.py
`bulk_delete_courses_with_reference_data` command break when we have course having no value fo `edited_on` attribute. This PR fixes that issue and refactors code to use logger instead of print statements.
@afzaledx would you please review?
=> ziafazal/delete-old-courses-fix: feedback changes and fix for no edited_on case

openedx/core/djangoapps/content/course_metadata/tasks.py
We are getting this error on MCKA QA environment when `update_course_aggregate_metadata` task is executed
```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: u'lms.djangoapps.api_manager.tasks.update_course_metadata'
```
I believe renaming the task to appropriate module it belongs to should fix it.
@msaqib52 would you please review this change?
=> ziafazal/task-keyerror-fix: renamed task to fix task keyerror

lms/djangoapps/api_manager/permissions.py, lms/djangoapps/organizations/serializers.py, lms/djangoapps/organizations/tests.py, lms/djangoapps/organizations/views.py
This PR Updates organizations list API to return number of courses as an additional field and also enables pagination on this API.
=> YONK-318: Update organizations list API to return number of courses

requirements/edx/custom.txt
This PR updates version number of [organizations](https://github.com/edx-solutions/organizations-edx-platform-extensions/tree/v1.0.4) app, which fixes the enrolled_users attribute to return only id’s of users from this organization and enrolled in this course.
@ziafazal would you please review?
=> bump organizations app version

lms/djangoapps/api_manager/users/tests.py, lms/djangoapps/api_manager/users/views.py
This PR adds partial filtering support to users list API, ``users`` can be filtered by using partial keywords for ``name``, ``email``, ``organization_display_name`` and ``courses``, providing query param partial match i-e ``/api/server/users?name=jo&match=partial``
=> YONK-337: add partial keyword filtering on attributes to users list API

lms/djangoapps/api_manager/courses/tests.py, lms/djangoapps/api_manager/courses/views.py, lms/djangoapps/api_manager/users/serializers.py
This PR has changes to add `section_breakdown` of users grades to `grades` field of course user list API. Changes in this PR also enable us to get additional fields by add a querystring like this `additional_fields=grades,organizations,roles`.
@msaqib52 would you please review?
=> ziafazal/YONK-339-b: added grade section breakdown and ability to pull additional fields

common/djangoapps/student/roles.py, requirements/edx/custom.txt
This PR adds a `roles` to `get_aggregate_exclusion_user_ids` method to get user ids of those users having given roles if `roles` parameter is present otherwise it would return user ids for roles in `AGGREGATION_EXCLUDE_ROLES ` setting. It also bumps the version of api-integration.
@msaqib52 please review.
=> added roles parameter

common/static/common/js/discussion/mathjax_include.js, lms/templates/courseware/courseware-chromeless.html, lms/templates/courseware/courseware.html
Changes from our previous PR #744 were [merged to `edx:master](https://github.com/edx/edx-platform/pull/13483), but had to be [reverted](https://github.com/edx/edx-platform/pull/13651) due to timing issues introduced into the Courseware lettuce acceptance tests.
Those issues have been fixed by https://github.com/edx/edx-platform/pull/13713.
This PR brings the fixes in https://github.com/edx/edx-platform/pull/13713 across to the `edx-solutions` Eucalyptus rebase.
**JIRA tickets**: Related to [YONK-382](https://openedx.atlassian.net/browse/YONK-382).
**Discussions**: See comments on [PR #13713](https://github.com/edx/edx-platform/pull/13713#issuecomment-252650478) for test results.
**Merge deadline**: Aiming for 17 Oct 2016.
See PR #744 for test setup instructions, …
=> MathJax: disable "fast preview" mode

common/static/common/js/discussion/main.js, openedx/core/lib/xblock_builtin/xblock_discussion_course/static/js/discussion_course.js
Fixes DiscussionCourseXBlock URLs by resetting the Backbone.History router to use the correct URL root.
Also fixes an issue I noticed with the "All Discussions" button, which wasn't correctly toggling the discussions list.
**JIRA tickets**: Implements YONK-413
**Partner information**: 3rd party-hosted open edX instance, for an edX solutions client
**Merge deadline**:  Fri Oct 21 2016
**Dependencies**:
* https://github.com/edx-solutions/cs_comments_service/pull/18
* [mcka_apros:ziafazal/eucalyptus-modifications](https://github.com/mckinseyacademy/mcka_apros/tree/ziafazal/eucalyptus-modifications) - this takes care of installing the fix from https://github.com/edx-solutions/jquery-xblock/pull/24.
**Setup Instructions**:
1. Get Studio, LMS, and Apros running on the parent branch …
=> YONK-413 Fix DiscussionCourseXBlock URLs

openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion.py
While testing eucalyptus upgrade on integration environment we found inline discussions does not render in studio when added inside a group project v2. It was trying to render student view and since discussion JS are not setup in asset pipeline of studio it was not able to pull `discussion_vendor` asset group. To fix this issue we need inline discussion xblock to override `preview_view` method. This [story](https://openedx.atlassian.net/browse/YONK-426) has more details to reproduce error.
@pomegranited would you please review this one?
=> added preview_view to inline disucssion

lms/djangoapps/courseware/tests/test_self_paced_overrides.py, lms/djangoapps/django_comment_client/utils.py
We have renamed inline discussion xblock from `disucssion-forum` to `discussion`. This PR filters inline discussion xblocks with their legacy names also to support loading of discussion threads for old courses.
This fixes YONK-428 and YONK-430.
@antoviaque can some one from your team review this?
=> support legacy inline discussion forum name in filters

cms/djangoapps/contentstore/views/item.py, requirements/edx/github.txt
**Description:** This PR fixes a couple of issues related to XBlocks:
* Added missing `local_resource_url` method to `StudioEditModuleRuntime` used to render XBlock's edit UI.
* Upgraded xblock-utils to 1.0.3 to fix issue with adding singleton nested XBlocks
**JIRA:** 
* [YONK-435](https://openedx.atlassian.net/browse/YONK-435)
* [YONK-436](https://openedx.atlassian.net/browse/YONK-436)
**Testing instructions:**
*YONK-345:*
1. Create a course.
2. Add Drag and Drop v2, Poll, Survey or any other XBlock affected by [YONK-435](https://openedx.atlassian.net/browse/YONK-435) (non-exclusive list available on the ticket) to Advanced problem list in course "Advanced Settings".
3. Create section, subsection and unit.
4. Add a chosen XBlock to the unit.
5. Click "EDIT" on the block. *Expected …
=> Added missing local_resource_url method to StudioEditModuleRuntime

lms/static/sass/_build-base-v1-no-reset.scss, lms/static/sass/_build-base-v1-rtl.scss, lms/static/sass/_build-base-v1.scss, lms/static/sass/discussion/_edx-pattern-library-loader.scss, lms/static/sass/discussion/inline-discussion-rtl.scss, lms/static/sass/discussion/inline-discussion.scss
**Description:** This PR attempts to fix styling problems reported in [YONK-437](https://openedx.atlassian.net/browse/YONK-437). 
**JIRA:** [YONK-437](https://openedx.atlassian.net/browse/YONK-437)
**Testing instructions:**
1. Create a course with GPv2 XBlock ([instructions](https://github.com/open-craft/xblock-group-project-v2/blob/master/README.md), [example course](https://github.com/open-craft/xblock-group-project-v2/tree/master/examples))
2. Configure Group Project in Apros ([instructions](https://github.com/mckinseyacademy/mcka_apros/blob/master/docs/GroupWorkConfiguration.md))
3. Log in into Apros as student enrolled into group project course.
4. Navigate to Group Project part (this button in top-right menu)
5. Observe that reported styling issues are gone.
**Author concerns:** …
=> Fix styling problems caused by discussions

cms/djangoapps/contentstore/views/item.py, common/lib/xmodule/xmodule/x_module.py
**Description:** This PR fixes "missing local_resource_url" bug using a better approach (closer to upstream)
**Details:** The bug was caused by the lack of `local_resource_url` in `StudioEditModuleSystem`. However, (investigation showed that) upstream was not affected by this. Further investigation revealed that a [part of the code](https://github.com/edx-solutions/edx-platform/blob/ziafazal/fix-broken-features/common/lib/xmodule/xmodule/x_module.py#L1486-L1488) causes `DescriptorSystem` to unconditionally use `local_resource_url` from `xmodule_runtime` if it is set on an XBlock. This part of code was [long removed from usptream](https://github.com/edx/edx-platform/commit/2faff29a211c1ec5f2a2dcdd08af2ca9598f166f#diff-936697469ba38db0e821ff2f2196c449L1301)
**JIRA:** 
- …
=> Better fix for missing local_resource_url

common/lib/xmodule/xmodule/modulestore/tests/test_cross_modulestore_import_export.py, common/lib/xmodule/xmodule/xml_module.py, openedx/core/lib/xblock_builtin/xblock_discussion/tests.py, openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion.py
**Description:** Backport of https://github.com/edx/edx-platform/pull/13056
Observed Problems:
1. Discussion categories and targets were missing
2. When imported over existing course Discussion IDs have changed unexpectedly - all posts were missing
Solutions:
* Parsing legacy discussion OLX
* Do not force exporting discussion ID
(cherry picked from commit fe6a942)
**JIRA:** [YONK-370](https://openedx.atlassian.net/browse/YONK-370)
**Testing instructions:** See https://github.com/edx/edx-platform/pull/13056
**Reviewers:**
=> [TNL-5001] Import-export issues when importing legacy discussion OLX format

common/djangoapps/third_party_auth/decorators.py, common/djangoapps/third_party_auth/views.py, lms/envs/aws.py, lms/envs/common.py
This PR has added a decorator which can used on any view to allow rendering of that view inside a FRAME or IFRAME if parent is a white listed URL and HTTP REFERER is one of the SAML Idp redirect url. We are adding this new decorator on `auth/custom_auth_entry` view to fix McKA SSO broken flow in case of first time registrations. [YONK-494](https://openedx.atlassian.net/browse/YONK-494) has more detail on McKA issue.
Unit tests to support these changes are added when we cherry pick these in Eucalyptus upgrade branch.
@ayesha-baig could you please review.
=> ziafazal/YONK-494: added ability to allow frames from a whit listed url

requirements/edx/custom.txt
This bumps the version of Problem Builder to include a fix for MCKIN-4700 (UI for MCQ's/MRQ's gets disturbed for lengthy choices).
@ziafazal Is this the correct branch to target?
@maxrothman @fredsmith (not sure who to ping) This version bump happens to pull in https://github.com/open-craft/problem-builder/pull/138 which includes a potentially large data migration. Can you please advise if similar care will need to be taken for deploying this on this fork? (Or is the `problem_builder_answer` table much smaller than edx.org?)
=> Update Problem Builder Version

cms/djangoapps/contentstore/views/preview.py
This PR fixes issue reported in [YONK-523](https://openedx.atlassian.net/browse/YONK-523)
Studio - When course author opens a unit or refreshes the page, publish button gets enabled.
=> YONK-523: avoid creation of draft nodes of document in mongo

requirements/edx/base.txt
astroid 1.3.8 is an unmet dependency of the version of pylint used in edx-lint 0.4.3.
=> astroid 1.3.8 is an unmet dependency of the version of pylint

requirements/edx/custom.txt
This PR installs [OpenCraft's Chat XBlock](https://github.com/open-craft/xblock-chat) as a custom package.
1. Set up a devstack using this branch.
2. [Enable the Chat XBlock in Studio](https://github.com/open-craft/xblock-chat#enabling-in-studio).
3. Add a new unit and verify that the Chat XBlock is available as an Advanced component. 
**Reviewers**
=> Install Chat XBlock as a custom package

lms/djangoapps/grades/tests/integration/test_events.py, scripts/all-tests.sh
This PR added ESLINT_THRESHOLD and skip a flaky test on CircleCI to fix circleci builds after ficus upgrade.
=> added ESLINT_THRESHOLD and skip a flaky test on CircleCI 

requirements/edx/custom.txt
Make edx-platform use the xblock-chat latest version.
**Review**
Ensure the commit matches [xblock-chat](https://github.com/open-craft/xblock-chat)'s HEAD
**Reviewers**
=> Update xblock-chat to latest version

requirements/edx/custom.txt
This bumps the problem builder version to include the WIP from https://github.com/open-craft/problem-builder/pull/150 to provide a mobile endpoint.
Note that the problem builder PR has not merged yet, so this is using a branch. The API for native views may change somewhat in the version that finally merges.
CC @replaceafill @mtyaka
=> Update Problem Builder to beta with Native API endpoint

requirements/edx/custom.txt
This updates xblock-chat to include fixes from https://github.com/open-craft/xblock-chat/pull/12.
**Testing**:
See https://github.com/open-craft/xblock-chat/pull/12.
**Reviewers**:
=> Bump xblock-chat

requirements/edx/custom.txt
The [actual name of the package is xblock-problem-builder](https://github.com/open-craft/problem-builder/blob/d312e9a587e4376b9afadb982f5fc28e4a9061fc/setup.py#L73), even though the repository is named problem-builder.
=> Fix problem-builder egg name in custom requirements.

requirements/edx/custom.txt
This updates xblock-chat to include IE fixes from https://github.com/open-craft/xblock-chat/pull/11.
It also includes changes from https://github.com/open-craft/xblock-chat/pull/14
**Testing**:
Verify that the xblock now loads in IE 10 & 11.
**Notes and concerns**:
While the xblock now loads in IE 10, the layout is rather broken. This is because IE 10 implements an outdated version of the flexbox spec. This will be fixed in a separate story/PR.
=> Update xblock-chat to latest version.

requirements/edx/custom.txt
This bumps the version of problem builder to include https://github.com/open-craft/problem-builder/pull/152 . There are no other changes.
=> Bump Problem Builder Version

requirements/edx/custom.txt, requirements/edx/github.txt
This updates the two xblocks two new versions which enable mobile views.
The Poll XBlock is currently using a custom branch, but there are plans to move to master in the near future.
It includes updates from https://github.com/open-craft/xblock-poll/pull/29 and https://github.com/mckinseyacademy/xblock-diagnosticfeedback/pull/24.
=> Update Poll and Diagnostic Feedback XBlocks.

requirements/edx/custom.txt
Adding version number in egg name to make it consistent with other requirement specifications.
Also It was observed that not mentioning version number in egg name led to old version being retained by Pip.
=> GW egg name fix

requirements/edx/custom.txt
Updates the `xblock-ooyala` requirement to the latest tagged release, [v2.0.9](https://github.com/edx-solutions/xblock-ooyala/releases/tag/v2.0.9).
**Reviewers**
=> MCKIN-5257 Bumps xblock-ooyala to v2.0.9

requirements/edx/custom.txt
Group Work v2 is showing some anomalies after latest changes. 
We are reverting it back to older hash till we identify root cause and fix.
This commit is to make sure that older commit is working fine on QA so we take that to stage.
=> revert group work v2 to older commit

requirements/edx/custom.txt
This PR bumps xblock-diagnosticfeedback version to the latest tagged release [v0.2.2](https://github.com/mckinseyacademy/xblock-diagnosticfeedback/releases/tag/v0.2.2).
=> MCKIN-5256: Diagnostic feedback version update

requirements/edx/custom.txt
This PR bumps xblock-image-explorer version to the latest tagged release [v0.4.0](https://github.com/edx-solutions/xblock-image-explorer/releases/tag/v0.4.0).
=> MCKIN-5350: XBlock Image Explorer version update

requirements/edx/custom.txt
This is a version bump to pull in https://github.com/open-craft/xblock-eoc-journal/pull/9 , fixing a bug reported on MCKIN-4999 with incorrect engagement metrics.
=> Version bump for xblock-eoc-journal

requirements/edx/custom.txt
Originally the submission was of the following form:
For MCQ (multiple-choice questions) it was string value.
For long/free form answers, it was a json in an array [{: }]
This PR makes the submission for both MCQs and freeform answers to the same format, a json with a 'value' key ({"value": }). This is so that we can add other info if needed in future.
=> Problem builder version bump after OC-2959 updates

common/lib/xmodule/xmodule/html_module.py, common/lib/xmodule/xmodule/tests/test_html_module.py, lms/djangoapps/course_api/blocks/tests/test_views.py, lms/djangoapps/course_api/blocks/transformers/tests/test_student_view.py
Allow the HTML content of the HtmlBlock to be downloaded via the course blocks API.
**JIRA tickets**: [OC-2995](https://tasks.opencraft.com/browse/OC-2995) [MCKIN-5637](https://edx-wiki.atlassian.net/browse/MCKIN-5637)
1. Have a course with a Text Html XBlock
2. Navigate to http://localhost:8000/api/courses/v1/blocks/?all_blocks=true&depth=all&requested_fields=student_view_data&course_id=<course_id>
3. See that the block's HTML content is available in the API output as:
```json
"student_view_data": {
"html": "<h1>HTML Content</h3>"
}
```
1. I'm unsure about whether or not to use `HtmlBlock.get_html()` since the context that `student_view_data` is called in doesn't provide …
=> Add student_view_data to HTML XBlock

lms/djangoapps/completion_api/models.py, lms/djangoapps/completion_api/serializers.py, lms/djangoapps/completion_api/tests/test_serializers.py, lms/djangoapps/completion_api/tests/test_views.py, lms/djangoapps/completion_api/urls.py, lms/djangoapps/completion_api/views.py, lms/envs/aws.py, lms/envs/test.py, lms/urls.py
Create a prototype implementation of the completion api.
* Contains a list and detail view for a specified user's course completion rates at /api/completion/v1/course/ and /api/completion/v1/course/<course_id>
* Allow staff to access other users
* Caller can specify whether to include subsection data.  
- Not yet generalizable to other block categories (but it shouldn't be hard).
* Paginated results.
* Does not include leaderboard endpoints.
=> Completion API prototype

requirements/edx/custom.txt
This PR upgrades Solutions' Poll XBlock to the current version (1.3.1)
**JIRA tickets**: [OC-2980](https://tasks.opencraft.com/browse/OC-2980) [MCKIN-5301](https://edx-wiki.atlassian.net/browse/MCKIN-5301)
**Reviewers**
=> xblock-poll version bump

common/lib/xmodule/xmodule/html_module.py
Add default context arg for HtmlBlock's student_view_data to prevent errors
**JIRA tickets**: [OC-2995](https://tasks.opencraft.com/browse/OC-2995)
=> specified default context arg for HtmlBlock get_student_value

lms/static/js/ajax-error.js
This fixes a bug introduced by https://github.com/edx-solutions/edx-platform/pull/856.
When a user submitting a problem is logged out due to session invalidation, they should be prompted to log back in and then once logged in, should be redirected to the same problem page.
This was broken by the above PR. When the user session is invalidated, clicking on the "Submit" button was doing nothing. This PR fixes it.
Should be merged ASAP.
**Reviewers**
=> MCKIN-5641: When user is logged out due to session invalidation, submitting a problem should redirect to login page

requirements/edx/custom.txt
This bumps problem builder to version 2.7.3 to pull in some minor API improvements: https://github.com/open-craft/problem-builder/pull/162/files?short_path=0159ad6#diff-0159ad6c3a1f1beb62bf08c385f28573
This work is follow-up to MCKIN-5253.
=> Problem Builder version bump to 2.7.3

requirements/edx/custom.txt
This PR bumps xblock-image-explorer version to v0.4.1 to include responsive changes.
@wajeeha-khalid can you please review?
=> bump xblock-image-explorer version to v0.4.1

lms/djangoapps/completion_api/tests/test_views.py, lms/djangoapps/completion_api/views.py
The new interim completion API was not working via OAuth2.
The reason due to inheritance order being wrong, so the authentication classes specified for this API were overridden by the base class:
Before:
```
>>> from completion_api.views import CompletionListView
>>> CompletionListView.authentication_classes
[<class 'rest_framework.authentication.SessionAuthentication'>, <class 'rest_framework.authentication.BasicAuthentication'>]
```
After:
```
>>> from completion_api.views import CompletionListView
>>> CompletionListView.authentication_classes
(<class 'openedx.core.lib.api.authentication.OAuth2AuthenticationAllowInactiveUser'>, <class 'openedx.core.lib.api.authentication.SessionAuthenticationAllowInactiveUser'>)
```
*Testing Instructions* (Devstack):
1. (If you need this:) Go to …
=> MCKIN-5415 Fix: Completion API was not working via OAuth2

lms/templates/courseware/courseware-chromeless.html
This fixes the Android app layout for Xblock-chat – it adds a `.chromeless` class to `div.course-wrapper` that allows xblocks to add CSS tweaks to chromeless views. It is a backport of this [PR](https://github.com/edx/edx-platform/pull/15474) for the edx-solutions fork.
**JIRA Ticket**: [OC-2855](https://tasks.opencraft.com/browse/OC-2855)
1. Build and install edx-android-app
2. Add an xblock-chat to a course page and use the Android emulator to check that the chat fully expands vertically, instead of occupying only the top half of the screen.
=> Add chromeless class to the wrapper when in chromeless mode.

requirements/edx/custom.txt
This fixes some layout bugs we noticed while working on MCKIN-5274. Details [here](https://github.com/open-craft/xblock-chat/pull/18).
=> Version bump for xblock-chat

requirements/edx/custom.txt
This PR bumps xblock image explorer version to `v0.4.3` which adds `multi_device` support for `student_view`
=> Bump xblock image explorer version to v0.4.3

requirements/edx/custom.txt
We have received a zip code base of scorm xblock from appsembler team as their latest changes (required by us to run SCORM xblock) are not yet available from their github repo.
This PR is to point git reference for SCORM xblock to mcka github repo with that code base instead of appsembler.
=> update git reference of scorm xblock to point to mcka repo

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt, requirements/edx/github.txt
This bumps Drag and Drop v2 from version 1.x to version 2.0.18. This brings in every single change listed in [Changelog.md](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/v2.0.18/Changelog.md). Updated documentation is available in [Readme.md](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/v2.0.18/README.md).
A demo course showing the new features is available at https://github.com/open-craft/demo-courses
It was necessary to bump the `XBlock` version as well, to bring in `ScorableMixin`. We have yet ot determine if that is fully compatible with Ficus, but it seems like it will be.
=> Bump Drag and Drop v2 (and XBlock) versions

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt, requirements/edx/github.txt
This re-adds changes from https://github.com/edx-solutions/edx-platform/pull/886, which somehow either disappeared from master, or never made it to master even though the PR was successfully merged.
This also further bumps the DnDv2 xblock to add some new improvements for mobile.
**Reviewers**:
=> Bump Drag and Drop v2 (and XBlock) versions.

lms/djangoapps/completion_api/tests/test_views.py, lms/djangoapps/completion_api/views.py
Change the user parameter to be username instead.
1. Log in as a student user.
2. Complete some blocks.
3. Try to access /api/completion/v0/course/?user=otherusersname  Expect a regular response, because the user parameter is not recognized
4. Try to access /api/completion/v0/course/?username=otherusersname  Expect a 4xx response, because you can't masquerade as another user
5. Log in as a staff user.
6. Try to access /api/completion/v0/course/?user=otherusersname  Expect a regular response, with the staff user's completions, because the user parameter is not recognized
7. Try to access /api/completion/v0/course/?username=studentuser (from above). Expect a 200 response with the data of the student user.
=> Interim Completion API user vs. username inconsistency

requirements/edx/custom.txt
This bumps the `api-integration` version to pull in https://github.com/edx-solutions/api-integration/pull/71 which is required to use staff-only courseware sections via the solutions api.
@ziafazal  This would also pull in your version 1.3.8 with https://github.com/edx-solutions/api-integration/pull/83 - is that OK?
=> MCKIN-5434 api-integration version bump

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt
We have identified a few issues in latest DnD version that was deployed to stage+prod
https://edx-wiki.atlassian.net/browse/MCKIN-6170
This PR is to revert DnD xblock version back to older one only from release branch.
=> MCKIN-6170: revert DnD to old version from stage+prod

lms/djangoapps/discussion_api/api.py, lms/djangoapps/django_comment_client/base/views.py, requirements/edx/custom.txt
This PR has changes to move social engagement score update logic in signal handlers of social engagement app from edx-platform. It has changes to send `thread_followed` and `thread_unfollowed` signal when thread follow/unfollow actions are performed by calling API.
This would fix the issue reported in YONK-785.
=> YONK-785: Moved course engagement score update into signal handlers

requirements/edx/custom.txt
This PR bump xblock-group-project-v2 version to 0.4.4, to fix user profile image urls according to updated users api.
=> MCKIN-6182: bump xblock-group-project-v2 version to 0.4.4

requirements/edx/custom.txt
Version bump to pull in some important bugfixes. This is a pre-release build, since one of the PRs involved is still waiting for final upstream review from edX.
@mtyaka If the build is green, could you please give this a quick sanity check and merge? We'd like to get this onto QA ASAP.
I forgot to update drag-and-drop-v2's setup.py for this prerelease version, but it should still work, and since it's not an official version release, that's probably fine.
=> MCKIN-6170 MCKIN-6121 Version bump for Drag and drop

lms/djangoapps/completion_api/models.py, lms/djangoapps/completion_api/tests/test_serializers.py
The earned value for student progress retrieved from StudentProgress model is not correct. Until this is corrected, get it from the "earned" property of CompletionDataMixin object.
1. Import a course and complete some problems in the course.
2. Modify the blocks or delete them.
3. Check that the value in the StudentProgress model still shows the original earned completions, but the value is correctly calculated by the backend.
1. This might be a temporary fix.
**Reviewers**
=> For Mobile API, get earned value from CompletionDataMixin instead of StudentProgress model

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt
This temporarily installs both version 7b05446 and version v2.1.4-prerelease2 of xblock-drag-and-drop-v2 in parallel. This is meant to be used only temporarily for one course, and not to be maintained in the long term.
**Caveats**
- Any existing drag and drop exercises on the server that have been edited with the new version will break.
- The new version and the old version cannot exist within the same subsection, since the JavaScript conflicts.
- For authors, there may be up to four different drag and drop component types available in Studio (v1 CAPA, v1 XBlock, v2, v2-new) which is confusing.
=> [MCKIN-6357] Revert to old DnDv2 version and install new one in parallel.

requirements/edx/custom.txt
This should fix all known major issues with what we're temporarily calling "drag and drop v3/v2-new". It does so by adding some McKinsey-specific CSS to the "v3"/"v2-new" xblock. The CSS will only affect the v3/v2-new XBlock; it won't affect the existing v2 XBlock.
Most of these changes were pulled directly from the new theme that I've proposed, which is in a private repo. Ask me if you don't have the link.
The exact CSS fixes included can be seen at https://github.com/open-craft/xblock-drag-and-drop-v2/pull/16/commits (ignore the first commit).
Testing instructions: See https://github.com/open-craft/xblock-drag-and-drop-v2/pull/16
Reminder: 
* The new version and the old version cannot exist within the same subsection, since the JavaScript conflicts.
* If testing this in a mobile app, …
=> Update dnd "v3" (v2-new), add McKA CSS overrides

cms/djangoapps/contentstore/views/course.py
If course structure is already cached calling `api.course_structure` with empty list of `block_types` returns completed course structure from cache. This check fixes the issue in that scenario. [YONK-825](https://openedx.atlassian.net/browse/YONK-825) has the details of the issue.
=> YONK-825: don't look into course structure if we dont have deprecated_block_types

requirements/edx/custom.txt
Incorporates the XSS fixes from open-craft/xblock-group-project-v2/pull/118
=> Increment GPv2 xblock version to 0.4.6

lms/djangoapps/completion_api/views.py
This fixes an internal server error when passing `course` in the `requested_fields` API parameter.
**JIRA tickets**: None
**Discussions**: None
**Screenshots**: None
**Sandbox URL**: None
**Testing instructions**
1. Register with a normal user
2. Advance a little through a course
3. http://localhost:8000/api/completion/v0/course/ should show meaningful data
4. http://localhost:8000/api/completion/v0/course/?requested_fields=course   should show 400 error at the bottom. No more 500 error
5. http://localhost:8000/api/completion/v0/course/?requested_fields=mean should work
6. http://localhost:8000/api/completion/v0/course/?requested_fields=courseeeeee should show 400 error
**Author notes and concerns**: None
**Reviewers**
**Settings**
None
=> MCKIN-6337 Remove 'course' parameter from requested_fields parameter in completion API

requirements/edx/custom.txt
The latest version includes fixes from https://github.com/open-craft/xblock-chat/pull/19.
=> Upgrade xblock-chat to latest version.

requirements/edx/custom.txt
This bumps the new xblock-drag-and-drop-v2 (installed in parallel with the old version) to include fixes from https://github.com/open-craft/xblock-drag-and-drop-v2/pull/18.
=> [MCKIN-6342] Bump xblock drag and drop v3

cms/djangoapps/contentstore/views/course.py
This PR has change to fix bug reported in YONK-842.
=> YONK:842: use LMS_BASE instead of SITE_NAME

requirements/edx/github.txt
Older versions of Django Wiki didn't pin Django to below 2.0, causing it to be unexpectedly upgraded.
=> upgrade django wiki to 0.0.16

requirements/edx/custom.txt
This updates `xblock-chat`. The new version includes fixes for the chromeless view and native apps from https://github.com/open-craft/xblock-chat/pull/23.
=> Bump xblock-chat to latest version.

common/lib/xmodule/xmodule/html_module.py, common/lib/xmodule/xmodule/tests/test_html_module.py, lms/djangoapps/course_api/blocks/transformers/tests/test_student_view.py, lms/envs/common.py, openedx/core/lib/block_structure/block_structure.py
This pull request merges the changes found in upstream [PR #15905.](https://github.com/edx/edx-platform/pull/15905) In addition to the changes, other linked files such as openedx/core/djangoapps/content/block_structure/factory.py have been added.
This encompasses two changes:
1. Need to set settings.FEATURES['ENABLE_HTML_XBLOCK_STUDENT_VIEW_DATA'] to continue to see HTML `student_view_data`.
2. A bugfix for the Course Blocks API `student_view_data` parameter has been put in for testing when `settings.DEBUG = True`, because this change may affect the mobile apps using the Course Blocks API.
Previously, if you put anything in that parameter, then all blocks with student_view_data would return theirs. With this fix enabled, the behavior is in line with [the …
=> MCKIN-5637, MCKIN-6563 - Merge HTML XBlock student_view_data from Upstream

lms/djangoapps/course_api/blocks/transformers/tests/test_student_view.py, openedx/core/lib/block_structure/block_structure.py
https://github.com/edx-solutions/edx-platform/pull/969 disabled the `student_view_data` bugfix using `settings.DEBUG`, which may or may not be enabled in QA.
This change uses a feature flag to enable the bugfix instead.  The bugfix is disabled by default to allow affected apps to be fixed prior to release.
**Testing instructions**
* Run this branch on a solutions devstack
* Login using a user enrolled in the Demo course, e.g. honor@example.com
* Navigate to the Course Blocks API, and request `student_view_data=html`, e.g. 
http://localhost:8000/api/courses/v1/blocks/?course_id=course-v1%3aedX%2bDemoX%2bDemo_Course&depth=all&student_view_data=html&username=honor
Note that the returned data shows `student_view_data` blocks for all types of blocks, including `html`, `discussion`, and …
=> [MCKIN-6576] Disable the student_view_data bugfix using a feature flag

requirements/edx/custom.txt
This PR bumps xblock image explorer version to v0.5.0, Which adds feature flag for calculating hotspots in %.
=> MCKIN-6614: Bump xblock image explorer version to v0.5.0

openedx/core/djangoapps/user_api/accounts/tests/test_views.py, openedx/core/djangoapps/user_api/preferences/tests/test_api.py, requirements/edx/base.txt, requirements/edx/custom.txt
This PR bumps the version of the End of the Course Journal Xblock to include fixes from https://github.com/open-craft/xblock-eoc-journal/pull/10 as a part of MCKIN-6708.
Signed-off-by: Tomasz Gargas <tomasz@opencraft.com>
=> MCKIN-6708 Bump End of Course Journal Xblock's version.

lms/djangoapps/completion_api/tests/test_views.py, lms/djangoapps/completion_api/views.py
This pull request adds the ability to query the Completion API and retrieve student progresses only from mobile courses.
**JIRA tickets**: MCKIN-6672
1. Ensure that a course has the "Mobile Course Available" set to true in Advanced Settings.
2. Visit /api/completion/v0/course/?mobile_only=true
3. Ensure that the course with "Mobile Course Available" is shown.
**Reviewers**
=> [MCKIN-6672] McKA Interim Progress API: Allow retrieving only mobile courses

common/djangoapps/student/tasks.py
Changes include the addition of a check that ensure no need to send notifications if the channel is none. 
**Issue Fix**: Learners are getting multiple notifications of same announcement.
=> YONK-875: No need to send Notification if Channel is None

requirements/edx/custom.txt, requirements/edx/github.txt
Uses temporary branches for XBlock, xblock-utils, and DnDv2-new to provide fixes for XBlock template translations.
**JIRA tickets**: [MCKIN-7023](https://edx-wiki.atlassian.net/browse/MCKIN-7023)
**Discussions**: [WL-230](https://openedx.atlassian.net/browse/WL-230), [YONK-879](https://openedx.atlassian.net/browse/YONK-879?focusedCommentId=307771&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307771)
**Dependencies**:
* https://github.com/edx/xblock-utils/pull/48
* https://github.com/edx-solutions/xblock-image-explorer/pull/37
* https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154
* https://github.com/open-craft/xblock-drag-and-drop-v2/pull/25
**Screenshots**: See https://github.com/edx-solutions/xblock-image-explorer/pull/37 and …
=> [MCKIN-7023] Improve XBlock i18n by allowing template translations

requirements/edx/custom.txt
Bump version of Problem Builder XBlock to include support for correct/incorrect feedback added in v2.9.0 via open-craft/problem-builder#183
**JIRA tickets**:  OSPR-2337
**Dependencies**: open-craft/problem-builder#183
**Reviewers**
=> [MCKIN-7199] Bump version of problem builder XBlock

common/djangoapps/django_comment_common/signals.py, openedx/features/course_experience/tests/views/test_course_home.py
Changes include addition of a signal to update CourseDiscussionSettings with CourseChortsSettings.
=> YONK-938: Signal added for cohorted discussions

requirements/edx/custom.txt
Bump version of Problem Builder XBlock to v2.9.2 which adds ``description`` field in ``student_view_data`` for ``pb-answer-recap``.  Re: open-craft/problem-builder#185
**Dependencies**: open-craft/problem-builder#185
**Reviewers**
=> Update problem-builder version to include fix from 2.9.2

lms/djangoapps/completion_api/models.py
This is a possible fix for MCKIN-7398. This changes the code to fetch CourseOverview from the database whenever possible, instead of always fetching it from the ModuleStore and updating the CourseOverview cache.
This should also improve the API performance.
=> MCKIN-7398 Avoid database write that can cause deadlock

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt
**Description**
This upgrades DnDv2 to the master version for all courses and makes `xblock-drag-and-drop-v2-new` version just an alias for the master version.
**Testing**
1. **Before applying this change** add at least on old DnDv2 block and at least one new DnDv2 block to your test course.
* The new drag and drop is added by adding `drag-and-drop-v2-new` to the course advanced settings as an advanced module type, then adding the component via "Component > Drag and Drop Problem"
* The old drag and drop is added by adding Problem > Advanced > Drag and Drop
1. Apply the changes from this PR and (re)install the requirements.
1. Restart LMS/Studio.
1. Verify that the old DnDv2 blocks have been updated to the new version and continue to work correctly.
1. Verify that the new DnDv2 blocks …
=> MCKIN-7382 Upgrade all DnDv2 blocks to new version.

lms/djangoapps/grades/tests/test_new.py, requirements/edx/custom.txt
**Description**
This upgrades DnDv2 to the master version for all courses and makes `xblock-drag-and-drop-v2-new` version just an alias for the master version.
This is identical to https://github.com/edx-solutions/edx-platform/pull/1063 but targets `integration`.
**Testing**
1. **Before applying this change** add at least on old DnDv2 block and at least one new DnDv2 block to your test course.
* The new drag and drop is added by adding `drag-and-drop-v2-new` to the course advanced settings as an advanced module type, then adding the component via "Component > Drag and Drop Problem"
* The old drag and drop is added by adding Problem > Advanced > Drag and Drop
1. Apply the changes from this PR and (re)install the requirements.
1. Restart LMS/Studio.
1. Verify that the old DnDv2 blocks have …
=> MCKIN-7382 Upgrade all DnDv2 blocks to new version

requirements/edx/custom.txt
This PR bumps version of xblock-image-explorer to apply changes from https://github.com/edx-solutions/xblock-image-explorer/pull/43.
Signed-off-by: Tomasz Gargas <tomasz@opencraft.com>
=> [MCKIN-7179] Bump version of xblock-image-explorer.

requirements/edx/custom.txt, requirements/edx/github.txt
Cleanup only; no new functionality introduced.
Removes dependencies on temporary branches introduced by https://github.com/edx-solutions/edx-platform/pull/1032.
**JIRA tickets**: [MCKIN-7023](https://edx-wiki.atlassian.net/browse/MCKIN-7023)
Same as https://github.com/edx-solutions/edx-platform/pull/1032
1. We are waiting for https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154 to merge before the [drag-and-drop-v2-new](https://github.com/edx-solutions/edx-platform/blob/5ab79a82767268ac2583055b03081518f550aba5/requirements/edx/custom.txt#L9) revision can be updated too.
**Reviewers**
=> MCKIN-7023 xblock i18n bump versions

common/djangoapps/third_party_auth/api/tests/test_views.py, common/djangoapps/third_party_auth/api/urls.py, common/djangoapps/third_party_auth/api/views.py, lms/envs/aws.py
Make SSO provider discovery use the same endpoint as the existing request.  Gate unprivileged rquests with a setting.  Revises work done in #1047.
**JIRA tickets**: Fixes OC-4285
**Discussions**: See OC-4285
**Merge deadline**: ?
1. Set up a user (username1) with TPA providers. 
2. Enable the ALLOW_UNPRIVILEGED_SSO_PROVIDER_QUERY setting in lms.env.json.
2. Log in as some other user (username2)
3. Request /api/third_party_auth/v0/users/username1
4. See that the providers were returned, but that remote_id was excluded from the response.
1. This removes the ability to query by email, since that wasn't part of the old endpoint.  It could be …
=> SSO discovery revisited

requirements/edx/custom.txt
This PR adds ooyala player support to problem builder.
Note: We are changing problem-builder hash for testing purposes in integration branch, do not push this change to other environments.
@naeem91 please review
=> add ooyala player support to problem builder

common/djangoapps/third_party_auth/api/tests/test_views.py, common/djangoapps/third_party_auth/api/urls.py, common/djangoapps/third_party_auth/api/views.py, lms/envs/aws.py
Make SSO provider discovery use the same endpoint as the existing request. Gate unprivileged requests with a setting. Applies #1080  to the development branch.
=> [MCKIN-7315] SSO provider endpoint reworked 

requirements/edx/custom.txt
The new version includes ability to export student's own answers to freeform questions in PDF form, implemented in https://github.com/open-craft/xblock-eoc-journal/pull/12.
=> [MCKIN-5151] Bump xblock-eoc-journal.

requirements/edx/custom.txt
Bumps problem builder version to v2.10.1, which moves its apros.css file into the McKA custom theme.
**Reviewer**
=> MCKIN-7493 Moves the problem_builder apros.css into the theme

cms/envs/common.py, lms/djangoapps/course_api/blocks/api.py, lms/djangoapps/course_api/blocks/transformers/__init__.py, lms/djangoapps/course_api/blocks/transformers/block_completion.py, lms/djangoapps/course_api/blocks/transformers/tests/test_block_completion.py, lms/djangoapps/course_api/blocks/views.py, lms/envs/common.py, requirements/edx/base.txt, setup.py
Fixes OC-4473
Add completion to requirements and INSTALLED_APPS, and backport the CompletionTransformer.  
**JIRA tickets**: Implements OC-4473
**Discussions**:  Ginkgo backport epic described here: https://docs.google.com/document/d/19e2PSEsTK6ZPHXoQ08YbyH9URmd0fb96GKmbFTF0CwQ/edit#
**Dependencies**: edx-completion repo.
**Screenshots**: N/A
Using a ginkgo-based solutions devstack checked out to this branch.
1. Verify that edx-platform tests pass.
2. Set completion.enable_completion_tracking waffle switch to active.
3. Verify that block completions are created when interacting with a course.  (View some blocks, watch some videos, answer some problems, then check in the shell that …
=> Backport block completion transformer.

lms/djangoapps/courseware/module_render.py, lms/djangoapps/courseware/tests/test_module_render.py, requirements/edx/custom.txt
This backport brings in the code that handles creating BlockCompletion objects when the following xblock events are published:
1. "grade"  -- scorable blocks are now be completed when an answer is submitted.
2. "completion" -- This is new, and the preferred way for non-scorable blocks to be completed.
3. "progress" -- Legacy mckinsey blocks that still use the progress system will be completed when they submit one of these events.
**JIRA tickets**: Implements OC-4475 (no MCKIN ticket that I know of).
**Dependencies**: OC-4474, still in review, but this branch is based on that one.
**Screenshots**: N/A
On a ginkgo solutions devstack:
1. Update installed prereqs.
1. Enable completion tracking waffle flag.
2. Log into a …
=> Backport completion event handling.

common/lib/xmodule/xmodule/discussion_module.py, openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion.py
Adds completion_mode to discussion xblock and discussion module.
**JIRA tickets**: Implements OC-4521
**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.
1. Enable completion.enable_completion_tracking waffle switch.
2. Verify that interacting with a discussion block does not result in a created BlockCompletion object.
3. Verify that discussion blocks are not considered when calculating total available completions for a given aggregator.
N/A
**Reviewers**
**Settings**
N/A
=> Add completion mode for discussion block and module.

requirements/edx/custom.txt
Bumps version of xblock-drag-and-drop-v2 to include changes from https://github.com/edx-solutions/xblock-drag-and-drop-v2/commit/a35f8bfb1315522c3a9d3786d94673d06ebfff3b
=> MCKIN-7601 Bump version of xblock-drag-and-drop-v2 to include native API changes

requirements/edx/custom.txt
Bumps version of the Group Project v2 XBlock to include bugfix in https://github.com/open-craft/xblock-group-project-v2/pull/121.
=> Bump version of group project v2

.gitignore, common/lib/xmodule/xmodule/assets/vertical/public/js/vertical_student_view.js, common/lib/xmodule/xmodule/vertical_block.py, common/test/acceptance/pages/lms/completion.py, common/test/acceptance/pages/lms/courseware.py, common/test/acceptance/tests/lms/test_lms_courseware.py, common/test/db_fixtures/waffle_flags.json, lms/djangoapps/courseware/views/views.py, lms/djangoapps/lms_xblock/mixin.py, lms/djangoapps/lms_xblock/runtime.py, lms/static/coffee/src/courseware.coffee, lms/static/completion/js/.eslintrc.js, lms/static/completion/js/CompletionOnViewService.js, lms/static/completion/js/ViewedEvent.js, lms/static/completion/js/spec/ViewedEvent_spec.js, lms/static/lms/js/spec/main.js, lms/templates/courseware/courseware-chromeless.html, openedx/core/lib/xblock_utils/__init__.py, requirements/edx/base.txt, webpack.config.js
Brings complete-by-viewing code into edx-solutions fork of edx platform.  This enables the completion system to register when a user has seen blocks that are completed by being viewed, including, most notably, html blocks.  
**JIRA tickets**: OC-4520, MCKIN-7751
1.  Set completion.enable_completion_tracking waffle switch.
2.  Delete existing block completions. 
from completion.models import BlockCompletion
BlockCompletion.objects.all().delete()
3.  Open up your browser's network traffic monitor (F12, and navigate to the appropriate tab
4.  Sign into a course, and navigate to a page with HTML blocks.  Look at a page, spending at …
=> Backport completion-by-viewing logic

requirements/edx/custom.txt
Updates version of projects-edx-platform-extensions to include management command that cleans up unwanted uploads. 
Original bug fix PR: https://github.com/open-craft/xblock-group-project-v2/pull/121
projects-edx-platform-extensions PR: https://github.com/edx-solutions/projects-edx-platform-extensions/pull/17
=> Bump version of projects-edx-platform-extensions

openedx/tests/aggregator_load/test_views.py
@symbolist, @bradenmacdonald
OC-4952
tl;dr: On a course with 10,000 users, it takes 10 minutes to query all course-level aggregators.
Larger page sizes shrink the total query time (more pages to fetch, fewer results per page).
page_size=100 (100 pages) -> 1400s
page_size=1000 (10 pages) -> 590s
page_size= 5000 (2 pages) -> 450s
Number of blocks in the course don't seem to affect the query time.
Checkout the current branch. Run the following commands (in a solutions devstack):
$ pip uninstall openedx-completion-aggregator
$ pip install git+https://github.com/open-craft/openedx-completion-aggregator@master#egg=openedx-completion-aggregator
$paver test_system -s lms -t openedx/tests/aggregator_load -e '--logging-level=WARNING --nocapture'
Tweak values for number of users and page_size in …
=> Performance test for querying all aggregators.

.gitignore, common/lib/xmodule/xmodule/assets/vertical/public/js/vertical_student_view.js, common/lib/xmodule/xmodule/vertical_block.py, common/test/acceptance/pages/lms/completion.py, common/test/acceptance/pages/lms/courseware.py, common/test/acceptance/tests/lms/test_lms_courseware.py, common/test/db_fixtures/waffle_flags.json, lms/djangoapps/courseware/module_render.py, lms/djangoapps/courseware/views/views.py, lms/djangoapps/lms_xblock/mixin.py, lms/djangoapps/lms_xblock/runtime.py, lms/static/coffee/src/courseware.coffee, lms/static/completion/js/.eslintrc.js, lms/static/completion/js/CompletionOnViewService.js, lms/static/completion/js/ViewedEvent.js, lms/static/completion/js/spec/ViewedEvent_spec.js, lms/static/lms/js/spec/main.js, lms/templates/courseware/courseware-chromeless.html, openedx/core/lib/xblock_utils/__init__.py, requirements/edx/base.txt, webpack.config.js
This backports the complete-on-view logic to ginkgo.  The only difference between this and the previous implementation (#1104, which was reverted) is that this one removes the chunkhash from the webpack-generated filenames.  These files are cached with a timeout of only 300 seconds, which is the same as non-bundled javascript files, so this should be be a safe change.  
**JIRA tickets**: Implements MCKIN-7877, OC-4855.
**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.
Verify that https://SANDBOXHOST/static/bundles/CompletionOnViewService.js exists and returns a 200 response.
Verify that visiting HTML …
=> Backport complete-on-view, take 2.

lms/envs/common.py, lms/urls.py, requirements/edx/custom.txt
Adds the [`openedx-user-manager-api`](https://github.com/mckinseyacademy/openedx-user-manager-api) as an installed django application, and loads its URL endpoints.
**JIRA tickets**: MCKIN-8112
**Dependencies**:
* https://github.com/mckinseyacademy/openedx-user-manager-api/pull/2
1. Run migrations.
1.  No CRUD endpoints exist yet for the user manager API, so data needs to be added via the LMS shell, e.g. 
```python
from user_manager.models import UserManagerRole
from django.contrib.auth import get_user_model
User = get_user_model()
honor = User.objects.get(username='honor')
staff = User.objects.get(username='staff')
manager_role = UserManagerRole.objects.create(
user=honor,
manager_user=staff,
)
```
1. Authenticate to the LMS as any user.
1. Visit …
=> [MCKIN-8112] Integrate the openedx-user-manager-api into Ginkgo 

requirements/edx/base.txt
'social-auth-core' version updated from 1.4.0 to 1.7.0
=> YONK-1081: User Identifier is wrong when using name_id for SSO 

common/djangoapps/enrollment/forms.py, common/djangoapps/enrollment/serializers.py, common/djangoapps/enrollment/tests/fixtures/course-enrollments-api-list-valid-data.json, common/djangoapps/enrollment/tests/test_views.py, common/djangoapps/enrollment/urls.py, common/djangoapps/enrollment/views.py
Creates an enrollment API endpoint to list course enrollments by course or a list of users. 
**Testing instructions**
* Create some test courses and users.
* Enroll some users at random into the created courses.
* Create a staff user (`is_staff` set to `True`).
* Login as the staff user.
* The endpoint is `/api/enrollment/v1/enrollments` with at least of one `course_id`, `username` query string parameters required. The `course_id` field accepts a single URL-encoded course ID and the `username` field accepts a string containing comma-separated usernames, URL encoded if necessary. Refer to the [view docstring](https://github.com/open-craft/edx-platform/blob/MCKIN-8184-api-to-return-list-of-course-enrollments-by-course-or-users/common/djangoapps/enrollment/views.py#L713) for more details.
* …
=> [MCKIN-8184] Create an API to list course enrollments by course or a list of users

requirements/edx/custom.txt
Bumps the version of the openedx-user-manager-api to incorporate the security restrictions.
**JIRA tickets**: MCKA-8112, OC-4961
**Dependencies**: https://github.com/mckinseyacademy/openedx-user-manager-api/pull/5
Automated tests are sufficient here.
**Reviewers**
=> [OC-4961] [MCKA-8112] Bump version for user-manager API

requirements/edx/base.txt
Use pypi release instead of tagged git commit.
Fixes: OC-5248, YONK-1111
Reviewers:
=> Bump edx-completion==0.1.10

lms/templates/courseware/courseware-chromeless.html
Mcka ticket: https://edx-wiki.atlassian.net/browse/MCKIN-8414
dir tag is missing in this page's body which causes discrepancies in Xblocks webviews for rtl languages.
=> dir tag added in xblock webview template 

requirements/edx/custom.txt
Version bump for open-craft/openedx-completion-aggregator@1.5.2 
Resolves issues with aggregators not rendering properly when updated live.
**JIRA tickets**: MCKIN-8474
**Discussions**:
Test that aggregator api returns appropriate results when aggregators are out of date.
**Reviewers**
**Settings**
=> Version bump aggregator to 1.5.2

requirements/edx/custom.txt
Version bump PR for open-craft/openedx-completion-aggregator#32  
Configures aggregator to have django admin pages.  
* Design takes into account performance considerations for large relationships: No select box for user model.
**JIRA tickets**: Assists with MCKIN-8099
**Merge deadline**: Sooner the better, but not critical.
Version bump.  See related PR, above.
**Author notes and concerns**:  N/A
**Reviewers**
**Settings**
=> Version bump aggregator MCKIN-8099

lms/djangoapps/discussion_api/forms.py, lms/djangoapps/discussion_api/serializers.py, lms/djangoapps/discussion_api/tests/test_views.py, lms/djangoapps/discussion_api/urls.py, lms/djangoapps/discussion_api/views.py
This PR implements an alternative cohort discussion settings and cohort discussion roles management API for server-to-server communication. This is related to PR https://github.com/edx/edx-platform/pull/18975 PR which implements a few other API endpoints for managing cohorts. The endpoints support OAuth2 authentication and session authentication and build upon existing API endpoints for the purpose.
* Log in to the LMS as a staff user.
* Create a test course and enable cohorts for it.
* Create some test users.
* Create a few cohorts and enroll the test users at random in the test course into the created cohorts.
* Enable the 'Course Discussions' feature for the course.
* Test and verify the course discussion settings endpoints using the format of the following …
=> [MCKIN-8524] Implement an alternative discussion settings, roles management API

openedx/core/djangoapps/course_groups/serializers.py, openedx/core/djangoapps/course_groups/tests/test_api_views.py, openedx/core/djangoapps/course_groups/views.py
This PR adds the 'get users in a cohort' endpoint accidentally missed in the upstream backport PR #1177. CC @xitij2000.
The testing instructions are the same as on the original PR.
=> [MCKIN-8395] Add the missing get users in a cohort endpoint

requirements/edx/custom.txt
Version bump openedx-completion-aggregator to include memory usage fix for run_aggregator_service mgt command.
**JIRA tickets**: FIXES YONK-1089
**Discussions**: Architecture discussed extensively on the wiki and in meetings, then the revised proposal was presented to the Arch Council on Oct. 21 and given thumbs up.
1. Verify that 1.5.4 contains the needed changes, and gets deployed.
This needs to be merged ASAP.
**Reviewers**
**Settings**
=> Bump aggregator to 1.5.4

requirements/edx/custom.txt
Version bump openedx-completion-aggregator to include memory usage fix for run_aggregator_service mgt command.  This PR hotfixes the version bump into the release-candidate branch, so it can be run on staging.
**JIRA tickets**: Fixes YONK-1089
**Discussions**: YONK-1089 and edx-mcka-dev slack channel on openedx.slack.com
1. Verify that 1.5.4 contains the needed changes, and gets deployed.
This needs to be merged ASAP.
**Reviewers**
**Settings**
=> [Staging Hotfix] Version bump aggregator to 1.5.4

common/lib/xmodule/xmodule/tests/test_validation.py, requirements/edx/base.txt, requirements/edx/custom.txt
Hotfix to update required XBlock, because the new completion_aggregator depends on it to run aggregator service.
Fixes YONK-1173.
* XBlock diff from currently installed version: https://github.com/edx/XBlock/compare/xblock-1.2.0...xblock-1.2.2?expand=1
* This change is already applied on QA, so no update needs to happen there.
=> YONK-1173: Update xblock version to match aggregator's requirements

common/test/utils.py, lms/djangoapps/django_comment_client/base/tests.py, lms/djangoapps/teams/tests/test_models.py, lms/lib/comment_client/thread.py, requirements/edx/custom.txt
This (along with [this](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/23)) fixes broken tests.
Currently I've 'skipped' the `test_create_cohorted_thread`, because changes after signal are saved by Celery task.
I've also encountered these failures randomly (I wasn't able to reproduce them deterministically):
```python
======================================================================
FAIL: test_follow_unfollow_thread_signals_1___follow_thread____thread_followed__ (lms.djangoapps.django_comment_client.base.tests.ViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/circleci/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/ddt.py", line 114, in wrapper
return func(self, *args, …
```
=> [MCKIN-8418] Fix tests

requirements/edx/custom.txt
Version bump PR to bring in performance improvements to openedx-completion-aggregator migration.
**JIRA tickets**: Implements YONK-1175
**Sandbox URL**: N/A
N/A
**Reviewers**
**Settings**
=> [Staging Hotfix] YONK-1175: Version bump aggregator to 1.5.10

requirements/edx/custom.txt
Allow the migration to work with an empty table.
=> Version bump aggregator to 1.5.11.

requirements/edx/custom.txt
This PR bumps xblock-poll version to 1.5.1
=> bump xblock-poll version to 1.5.1

requirements/edx/custom.txt
Without this revert, I get an error when accessing http://apros.mcka.local/courses/edX/PS1/20181029, which is a course that has problem-builder, image-explorer, ooyala-player, poll, and survey xblocks.
I reverted all the changes made since the last successful QA deployment, which included updates to:
* openedx-completion-aggregator (1.5.11 -> 1.5.12
* xblock-image-explorer (1.0.1 -> 1.1.1)
* problem-builder (2.10.5 -> 2.11.0)
* xblock-poll (poll & survey blocks) (1.5.1 -> 1.6.0)
One by one, I re-applied the changes.  Aggregator and problem-builder didn't cause any problems.  The errors showed up again when either image-explorer or xblock-poll was updated.  So this reverts those two changes, and leaves the problem-builder and openedx-completion-aggregator changes in place.
=> MCKIN-8752: Revert poll and image-explorer version bumps

requirements/edx/custom.txt
Exclude group-project-v2 blocks from completion calculation.
Merges work done in https://github.com/open-craft/xblock-group-project-v2/pull/124
**JIRA tickets**: MCKIN-8797
**Dependencies**: N/A.
**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.
1. Step by step manual setup/testing/verification instructions go here.
2. Step 2
**Reviewers**
**Settings**
=> MCKIN-8797: Version bump group-project-v2 to 0.4.10

requirements/edx/custom.txt
Version bump PR for aggregator v1.5.13.  
Relates to open-craft/openedx-completion-aggregator#44
**JIRA tickets**: No MCKIN ticket yet.
**Discussions**: See edx-mcka-dev slack channel
1. See instructions on aggregator PR.
See aggregator PR.
**Reviewers**
**Settings**
N/A
=> Aggregator version bump 1.5.13

requirements/edx/custom.txt
This PR bumps xblock problem builder version to 2.11.1
=> MCKIN-8666: bump xblock problem builder version to 2.11.1

lms/djangoapps/discussion/views.py
Discussion board AssertionError fixed.
Previously, When forum service is down maintenance page was not loaded as code throws assertion error as fragment gets HTTPResponse object. Fragment now gets a string and maintenance page is rendered successfully.
Also, fragment resources are also added which were not being loaded previously in maintenance error case
=> YONK-1177 - Performance related errors on discussion forum and progress page 

common/djangoapps/third_party_auth/api/views.py
Throttling was intended to limit each user so they could not use this endpoint to scrape a list of all users and their SSO associations.  However, the requests are being made directly by apros, so instead of each user being limited, each app server is limited.
**JIRA tickets**: Fixes 
**Discussions**: On edx-mcka-dev slack channel, 11/07
**Merge deadline**: ASAP.
1. Try to log in 
1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...
**Reviewers**
**Settings**
```yaml …
```
=> Remove throttling from SSO provider view.

common/djangoapps/third_party_auth/api/tests/test_views.py, common/djangoapps/third_party_auth/api/views.py
/api/third_party_auth/v0/users/{username} also returns if a user is activated or not
New PR because the old one was accidentally closed.
=> [BB-430] [MCKIN-8671] Third-party Auth endpoint should return whether user is active

requirements/edx/custom.txt
Bump aggregator version to 1.5.14 to include migrate_progress by id.
**JIRA tickets**: Implements SOL-5, SOL-6.
**Merge deadline**:ASAP
Verify that aggregator installs the correct version, and can run ./manage.py migrate_progress --ids=100,200,300
**Reviewers**
**Settings**
=> Bump aggregator version to 1.5.14

requirements/edx/custom.txt
The Ooyala XBlock needs some setup of API keys etc that isn't possible on the devstack, so this PR will temporarily bump the version of the block for testing https://github.com/edx-solutions/xblock-ooyala/pull/86
=> [MCKIN-8325] Bump ooyala xblock for testing

lms/djangoapps/courseware/module_render.py
This PR fixes `django-oauth2-provider` support for XBlock callbacks.
- create DOP and DOT access tokens,
- make requests to XBlocks and check that both are working.
=> [MCKIN-8747] Fix `django-oauth2-provider` support for XBlock callbacks

requirements/edx/custom.txt
@UmanShahzad 
Version bump xblock-group-project to 0.1.1 to exclude from completion aggregation.
**JIRA tickets**: MCKIN-8826
**Discussions**: NA
Version bump of already tested code.
**Reviewers**
**Settings**
=> MCKIN-8826: Version bump group-project to 0.1.1

lms/djangoapps/courseware/module_render.py, lms/djangoapps/courseware/tests/factories.py, lms/djangoapps/courseware/tests/test_entrance_exam.py, lms/djangoapps/courseware/tests/test_module_render.py, lms/djangoapps/courseware/tests/test_views.py, lms/urls.py
This PR adds OAuth2 and JWT API to call XBlock handlers. It is an alternative approach to edx#15940 - it reuses some DRF logic to handle this, but does not convert `handle_xblock_callback` to DRF view, which caused issues described in edx/Xblock#383.
It needed some reverts as well, because changes from edx#15940 were needed here.
1. Run tests: `pytest lms/djangoapps/courseware/tests`.
2. Set up OAuth2 token and make GET and POST requests to xblock endpoint.
=> [MCKIN-5641] Add upstream-compatible OAuth2 support to XBlock handlers

requirements/edx/custom.txt
This PR is updating the Ooyala-xblock version to 2.0.18. 
Tickets: MCKIN-8790
=> update the ooyala xblock version

requirements/edx/custom.txt
Version bump aggregator to improve performance of single-user single-course endpoint.
**JIRA tickets**: MCKIN-8827
**Sandbox URL**: TBD -Architecture discussed extensively on the wiki and in meetings, then the revised proposal was presented to the Arch Council on Oct. 21 and given thumbs up. sandbox is being provisioned.
**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.
Tested on open-craft/openedx-completion-aggregator#47
**Reviewers**
**Settings**
=> MCKIN-8827: Version bump aggregator to 1.5.16

requirements/edx/custom.txt
Pointed to commit containing the temp image fix https://github.com/edx-solutions/xblock-drag-and-drop-v2/commits/temp-image-fix
=> DnDv2 version corrected

requirements/edx/custom.txt
This pr is pointing ooyala fix to the branch mckin-8725b
=> ooyala point to removing bitmovin and bit_wrapper branch

requirements/edx/custom.txt
This contains a version bump for xblock-image-explorer.  It resolves the issue with image-explorer blocks being completed to early.  A similar problem for polls and surveys has already been resolved.
**JIRA tickets**: Implements BB-590
Install the latest requirements: Create a course that has a poll, survey and image-explorer block. 
In studio (log in as staff w/ password edx): 
1. Go into advanced settings and add {{"poll", "survey", "image-explorer"}} to the list of advanced xblock types.  (Note, the list has to be a valid JSON list: double quotes only, no trailing comma, square brackets around the whole thing).
2. Then go …
=> Bump image explorer version to 1.1.1

requirements/edx/custom.txt
Optimized `discussion-edx-platform-extensions` is not meant to go to the next prod release, so we should bump it back to v1.2.8 for now.
=> [MCKIN-9028] Downgrade `discussion-edx-platform-extensions`

common/lib/xmodule/xmodule/library_content_module.py, openedx/tests/completion_aggregator_integration/test_creation.py
Create aggregation integration tests.  
These are moved over from edx/edx-platform#17703, because it was too hard to keep them in sync with the changing platform, and there was no good end plan for merging the code.  Here, it can be merged cleanly, and run with regular platform tests.
**JIRA tickets**: [BB-157](https://opencraft.atlassian.net/browse/BB-157/), [BB-163](https://opencraft.atlassian.net/browse/BB-163/)
**Discussions**: See references JIRA tickets, and mainline edx-platform PR.
1. Read over the discussion on the previous PR (edx/edx-platform#17703) and the referenced tickets.  
2. Verify that the tests provide sufficient coverage as …
=> Aggregation integration tests

openedx/tests/completion_aggregator_integration/test_creation.py, requirements/edx/custom.txt
Version bump for https://github.com/open-craft/openedx-completion-aggregator/pull/49
**JIRA tickets**: Implements MCKIN-8827
1. Step by step manual setup/testing/verification instructions go here.
2. Step 2
1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...
**Reviewers**
**Settings**
=> MCKIN-8827: Cache block structure (aggregator version bump)

requirements/edx/custom.txt
Version bump for problem builder to v3.2.1.
Already tested on https://github.com/open-craft/problem-builder/pull/224.
=> [MCKIN-9274] Version bump for problem builder

lms/djangoapps/courseware/model_data.py
Implemented the try/except block on saving a user's score as implemented in Hawthorn release [link](https://github.com/edx/edx-platform/blob/open-release/hawthorn.master/lms/djangoapps/courseware/model_data.py#L993)
It will avoid raising database errors on New Relic.
Upstream PR: https://github.com/edx/edx-platform/pull/16912/files
=> YONK-967: Integrity error fixed on set_scores

requirements/edx/base.txt, requirements/edx/custom.txt
This PR bumps completions to add OAuth authentication to POST endpoint.
1. Create an OAuth token to test the POST endpoint.
2. Perform a POST request to set completion, i.e.
```
curl -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d '{"username":"<username>","course_key":"<course_key>","blocks":{"<block_id>":1.0}}' localhost:8000/api/completion/v1/completion-batch
```
**Reviewers**
=> Bump completion to v0.1.15

lms/djangoapps/instructor/permissions.py, lms/djangoapps/instructor/tests/test_api.py, lms/djangoapps/instructor/urls.py, lms/djangoapps/instructor/views/api.py, lms/djangoapps/instructor/views/api_urls.py, lms/djangoapps/instructor/views/instructor_dashboard.py, lms/urls.py
This PR enables OAuth access of the endpoints necessary to generate, get status and download problem response reports.
**JIRA tickets**: [OSPR-2983](https://openedx.atlassian.net/browse/OSPR-2983), [BB-728](https://tasks.opencraft.com/browse/BB-728)
**Merge deadline**: 25/01/2019 (end of Sprint 186).
1. Run tests related to this new endpoint:
```
paver test_system -t lms/djangoapps/instructor/tests/test_api.py
```
2. [Go to the `DemoX edX Demonstration Course` as **staff** user.
](http://lms.mcka.local/courses/course-v1:edX+DemoX+Demo_Course/instructor#view-data_download)
3. Check if the generation of problem response reports is working correctly via the instructor interface.
4. [Create an Oauth client here if …
=> [MCKIN-9301] BB-728 - Modify LMS APIs to enable OAuth access to problem response reports

lms/static/scorm/ssla/config_override.js
Once a user launches a scorm course in a popup, a string would appear on the iframe(scormxblock) that seemed visually clickable but was not, and was unnecessary. This PR removes that string.
=> MCKIN-9407 Remove string on iframe after launching popup

requirements/edx/custom.txt
This PR bumps api-integration version to v2.5.1, which adds new API for fetching course engagement summary.
=> MCKIN-9466: bump api-integration version to v2.5.1

requirements/edx/custom.txt
This PR bumps the version for problem-builder. The changes from problem-builder introduces a pre_delete signal receiver to delete `Answer` records when a User is deleted. See https://github.com/open-craft/problem-builder/pull/225.
=> [MCKIN-8913] BB-785 Bump problem-builder version

requirements/edx/custom.txt
bump xblock-ooyala version to v2.0.22 which includes fix for MCKIN-9463
=> MCKIN-9463: bump xblock-ooyala version to v2.0.22

requirements/edx/base.txt, requirements/edx/github.txt
This PR bumps completions to add OAuth authentication to POST endpoint.
1. Create an OAuth token to test the POST endpoint.
2. Perform a POST request to set completion, i.e.
```
curl -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d '{"username":"<username>","course_key":"<course_key>","blocks":{"<block_id>":1.0}}' localhost:8000/api/completion/v1/completion-batch
```
**Reviewers**
=> Bump edx-completion to 0.1.10.1

lms/djangoapps/instructor_task/tasks_helper/grades.py, lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Fix issue with multiple responses for a single user returned by generate_report_data
Use absolute path in location instead of a relative path.
Upstream PR: https://github.com/edx/edx-platform/pull/19507
=> MCKIN-9302: Fix issue with multiple responses for a single user returned by generate_report_data

lms/djangoapps/instructor/tests/test_api.py, lms/djangoapps/instructor/views/api.py, lms/djangoapps/instructor_task/api.py, lms/djangoapps/instructor_task/tasks_helper/grades.py, lms/djangoapps/instructor_task/tests/test_api.py, lms/djangoapps/instructor_task/tests/test_tasks_helper.py
This PR adds two features to the problem response report API:
1) Support for specifying multiple root blocks. 
With this feature, you can now pass a comma-separated list of problem locations, and the generated report will include both of them (and children). 
2) Support for specifying a problem type filter. 
This feature allows you to request a report for only one or more types of problems.
Re: https://github.com/edx/edx-platform/pull/19781
=> [MCKIN-9474] [BB-873] Support for filters, and multiple roots in problem response reports

lms/static/scorm/ssla/config_override.js
This PR makes changes in the SSLA confiuration for the scorm xblock.
In case a popup fails to launch, change the UI shown to the user in the iframe.
Steps to reproduce: 
1. Block popups in your browser settings your local server domain.
2. Attempt to launch a scorm popup from apros (auto/manual)
3. Check that the UI is now similar to the one posted in the ticket. Also posted below for ease of review.
=> MCKIN-9579 Add button when ssla fails to launch scorm popup

requirements/edx/custom.txt
MCKIN-9820, BB-941
Version bump of openedx-completion-aggregator to handle KeyError more gracefully.
See https://github.com/open-craft/openedx-completion-aggregator/pull/53
Reviewer: @xitij2000
=> MCKIN-9820: Version bump aggregator v1.5.21

lms/static/scorm/ssla/config_override.js
Fixes an issue where div does not captures the whole height in mozilla. Added `display: table;` in css.
=> MCKIN-9959 Modify Ssla configuration popup fail css

cms/envs/common.py, lms/envs/common.py, openedx/core/djangoapps/user_api/accounts/api.py, openedx/core/djangoapps/user_api/accounts/tests/test_api.py
This PR fixes two small bugs in user deletion that affects both participant and company deletion.
**1. An object was passed as argument for the profile image deletion Celery task** 
Recently, a new deletion function was create in order to delete user profile images asynchronously by using a Celery task.
Because we're using the devstack to test the settings, the default setting is `CELERY_ALWAYS_EAGER = True` which runs the function synchronously by passing arguments as a normal function, without ever going through the broker.
The problem with that is that in Celery tasks the parameters need to go serialized through the message broker, when using a production environment, meaning we can't pass any Python objects. Which is exactly what's happening on [this …
=> BB-991: Fix user deletion celery task

lms/static/scorm/ssla/config_override.js
This PR makes changes in the SSLA player configuration to add hooks to the event of "Scorm popup closing".
**Background:**
The SSLA player has been integrated on edx-platform to work with Scorm xblock. Together, the xblock and the player enable users to launch Third party authored scorm courses.
**Author's Notes:**
Please refer to the ssla player's [public documentation](https://www.jcasolutions.com/wp-content/uploads/2018/01/SSLA_Documentation.pdf) for any queries.
=> MCKIN-9654 Ssla Config: handle scorm popup close

lms/djangoapps/instructor/urls.py
Adds an alternative path to instructor task API as /api/instructor/v1/tasks
=> [MCKIN-9476] Add instructor tasks list to a path inside /api

requirements/edx/custom.txt
Version bump openedx-completion-aggregator to 1.5.22.  This pulls in https://github.com/open-craft/openedx-completion-aggregator/pull/57
**JIRA tickets**: MCKIN-10256
Already tested on linked aggregator PR.
**Reviewers**
=> MCKIN-10256: Version bump aggregator 1.5.22.  Resolve dangling StaleCompletions

requirements/edx/base.txt, requirements/edx/custom.txt, requirements/edx/github.txt
Version bump to use the latest version of edx-completion.  This removes the need for a separate fork for ginkgo.
**NOTE**  This should not be merged until the edx-completion PR merges, and gets a fresh PyPI deployment.
**JIRA tickets**: BB-1060 
**Merge deadline**: N/A
1. Verify that all completion endpoints work, directly, through apros, and via mobile.
1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...
**Reviewers**
=> BB-1060: Use latest edx completion

openedx/core/djangoapps/user_api/accounts/api.py, requirements/edx/custom.txt
This PR changes the user deletion to also remove notifications mentioning an user.
1. Checkout this branch and restart edxapp.
2. Go to the discussions and create a thread with an user.
3. Create a test user and make a comment on the thread created above.
4. With the first user, confirm a notification is received containing the test user username.
5. Perform the deletion of the test user.
6. With the first user, confirm the notification does not show any longer.
BONUS: Check the MySQL table directly:
```
mysql> SELECT * from edx_notifications_notificationmessage WHERE payload LIKE '%test_user%';
Empty set (0.00 sec)
```
**Reviewers**
=> [MCKIN-8914] Delete notifications mentioning an user

lms/envs/aws.py, lms/envs/test.py
This PR brings back `progress` to INSTALLED_APPS to prevent issues when deleting participants.
=> [MCKIN-10137] Add progress to envs INSTALLED_APPS

requirements/edx/custom.txt
This branch bumps the xblock-poll requirement to v1.8.5 to incorporate a fix for multiple survey blocks in the same unit interfering with each other.
=> [MCKIN-10708] Bump xblock-poll to v1.8.5.

requirements/edx/custom.txt
This PR bumps xblock problem-builder version to v3.3.4.
cc: @attiyaIshaque
=> MCKIN-8902: bump xblock problem-builder version to v3.3.4

lms/static/coffee/src/courseware.coffee
Xblocks were initializing twice causing issues in the initialization of Xblock Drag and Drop, This PR removes duplicate initialization of xblocks.
=> MCKIN-10975: fix double initialization of blocks

common/djangoapps/util/password_policy_validators.py
**Ticket**: https://edx-wiki.atlassian.net/browse/MCKIN-11119
**Description:**
White-space is now considered as special character during password validation.
=> MCKIN-11119 Consider white-space as punctuation during password validation

requirements/edx/base.txt
Upgrading version of urllib3 because of group-work dependency (boto3).
Error can be found [here](https://rpm.newrelic.com/accounts/631098/applications/4390895/traced_errors/940c162e-9c9e-11e9-9258-0242ac110011_0_6625)
=> MCKIN-11136-version-bump-urllib3

lms/djangoapps/instructor_task/migrations/0003_auto_20191008_1151.py, lms/djangoapps/instructor_task/models.py, lms/djangoapps/instructor_task/tests/test_api.py
Admin was unable to generate a report on the course detail page facing the error for 3 rows when a course has a larger course id than the normal/usual course id. Now, an admin will be able to generate a report in case of selecting 3 rows.
=> MCKIN-11613 Admin is unable to generate a report on course detail page.

common/static/common/templates/discussion/new-post.underscore
When either the "Show Discussion" button or the "Add a Post" button is activated new content appears below, but focus remains on the button rather than moving to the new content.
Tab index added in order to get focus.
=> MCKIN-12234 discussion content update focus update accordingly

lms/djangoapps/instructor_task/api_helper.py
Unable to generate polls report if a task gets stuck by some reason and stays in progress state. So this fix will be checking out the task for a day, after that the task will be obsoleted if it is still in progress.
=> MCKIN-12693 Unable to access or download polls report

common/static/common/templates/discussion/thread-list-item.underscore
Description
[Issue]  
Color alone is used to communicate discussion status.  The meaning provided by color is not available in textual format. For example, the blue vertical line that is used to indicate 'never read' does not have textual representation. 
[Impact]
Screen-reader users are not able to know the discussion status communicated via color alone. 
```
<li data-id="5d91fadf1398d9091ce4685d" class="forum-nav-thread never-read">
<a href="/courses/DEV/MCKA_SHOWCASE/NOV2018/discussion/forum/f0c5437e8a016eae9a849b5a4edb885b0b413f6c/threads/5d91fadf1398d9091ce4685d" class="forum-nav-thread-link">
<div class="forum-nav-thread-wrapper-0">
```
Environment
[Recommendation]
Developers must ensure information or meaning conveyed through color or sensory character is also available in textual …
=> MCKIN-12139-AF#27-Discussion_Page-Ensure color is not the sole means of communicating information

common/static/common/templates/discussion/new-post.underscore
Move programmatic focus to the top of the new content. In the case of activating "Show Discussion" focus should move to the "Add a Post" button. When "Add a Post" is activated focus should move to the heading "Add a Post".
=> MCKIN-12234 Discussion moving focus to new content

lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js
**Issue**: When "All Topics" button or a discussion title link is activated new content appears on the screen, but focus remains on the button rather than moving to the new content. 
**User Impact**: Screen reader users and users with low vision who may be zoomed in may not easily notice/located the new content when focus does not automatically move there.
This PR move focus to sidebar posts filter dropdown when user clicks 'all topics' link.
=> MCKIN-12240: Discussion: on all topics click move focus to sidebar posts filter

requirements/edx/custom.txt
merged OpenCraft [PR](https://github.com/edx/edx-notifications/pull/190) into edx-notifactions and updating edx-notifications links to openedx GitHub organisations. 
It was changed to OpenCraft organisations for some urgent changes. Those changes have been merged into development of edx-notifications.
=> edx-notifications version bump

cms/djangoapps/contentstore/management/commands/toggle_assets_lock.py, cms/djangoapps/contentstore/views/assets.py
This PR adds a management command to lock/unlock assets course assets and makes newly uploaded assets locked by default.
=> MCKIN-12722: lock course assets

lms/djangoapps/instructor/views/api.py, lms/djangoapps/instructor_task/api_helper.py
A task generation request for an already running task returned just the status, and not the task id. We need the task_id on apros side to check for progress of task after intervals.
=> MCKIN-12871 PBReport: Return task_id for already running task

common/djangoapps/third_party_auth/admin.py, common/djangoapps/third_party_auth/models.py
Fields icon_class and icon_image do not appear in django admin.
If they one of them is not set, LTI Config addition fails.
Issue:
This PR allows these fields to be displayed in django admin so either of them can be set.
**Url to verify:** http://courses.integration.mckinsey.edx.org/admin/third_party_auth/ltiproviderconfig/add/
**Code that causes the error:**
https://github.com/edx-solutions/edx-platform/blob/f55f1461d8b6f2e889ee9f2011c6d062fbefbe23/common/djangoapps/third_party_auth/models.py#L199
=> MCKIN-13610 Fix failure to add LTI config

common/djangoapps/third_party_auth/admin.py
Fields icon_class and icon_image do not appear in django admin.
If they one of them is not set, LTI Config addition fails.
Issue:
This PR allows these fields to be displayed in django admin so either of them can be set.
**Url to verify:** http://courses.integration.mckinsey.edx.org/admin/third_party_auth/ltiproviderconfig/add/
**Code that causes the error:**
https://github.com/edx-solutions/edx-platform/blob/f55f1461d8b6f2e889ee9f2011c6d062fbefbe23/common/djangoapps/third_party_auth/models.py#L199
=> MCKIN-13610 Fix failure to add LTI config (#1694)

cms/djangoapps/contentstore/views/assets.py, cms/envs/aws.py, cms/envs/common.py, common/lib/xmodule/xmodule/tests/test_video.py
This PR put assets locking behind feature flag so it could be controlled environment wise.
Related flag PR: https://github.com/edx/mckinsey-internal/pull/291
p.s fixes test failures as per upstream: https://github.com/edx/edx-platform/pull/23679
=> MCKIN-12722 - assets locking put behind feature flag

cms/envs/common.py, common/lib/xmodule/xmodule/tests/test_video.py
**`openedx.core.djangoapps.content.course_structures.tasks.update_course_structure`** and **`openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache`** tasks are  not
getting autodiscovered by celery and needs to be imported explicitly.
Fix tests that are failing due to missing youtube content. These tests were fixed in openedx in this PR https://github.com/edx/edx-platform/pull/23680
=> Fix unregistered celery task.

requirements/edx/custom.txt
This PR bumps `xblock-poll` version to `v1.9.7`
=> MCKIN-17536: bump xblock-poll version to v1.9.7

lms/djangoapps/courseware/module_render.py
**Issue:** 
csrf_token in the response body and header doesn't match.
Request Headers:
Request Body:
**Reason:**
In Django 1.8 `from django.template.context_processors import csrf` function used to return the same [csrf token](https://github.com/django/django/blob/6a0dc2176f4ebf907e124d433411e52bba39a28e/django/middleware/csrf.py#L40-L51) from the request.
Since we've updated the Django to 1.11 as part of Ironwood.
Now in Django 1.11`from django.template.context_processors import csrf` function returns a new [csrf token](https://github.com/django/django/blob/c669cf279ae7b3e02a61db4fb077030a4db80e4f/django/middleware/csrf.py#L80-L96) created from the last one.
**Solution:**
Update the set-cookie in response headers so that we have the same csrf_token in response body and headers.
=> MCKIN-17522 Added set-cookie in the student view response

requirements/edx/custom.txt
This PR bumps xblock chat version to v0.2.7
=> MCKIN-18600: bump xblock chat version to v0.2.7

requirements/edx/custom.txt
This PR bumps xblock eoc-journal version to 0.6
=> MCKIN-18602: bump xblock eoc-journal version to 0.6

requirements/edx/custom.txt
xblock-eoc-journal at open-craft github repo is not compatible with ginkgo anymore, they have updated it to support ironwood.
We will use v0.6 from open-craft github repo when ironwood is released.
=> MCKIN-18602: use forked xblock-eoc-journal to support ginkgo

cms/djangoapps/contentstore/views/component.py, cms/static/sass/elements/_modules.scss
Renamed the following discussion button as a caution to not use it to create a discussion block. There is another option to create a discussion block rather than this.
=> MCKIN-21791 renaming the discussion button

common/djangoapps/database_fixups/migrations/0002_remove_foreign_keys_from_progress_extensions.py
The `progress-edx-platform-extensions` has been deprecated in favor of `edx-completion`.
The requirement was removed in [this commit](https://github.com/edx-solutions/edx-platform/commit/59bf3efe71533de53b60bd979517e889d18a96bb) below. However its [migration](https://github.com/edx-solutions/progress-edx-platform-extensions/blob/master/progress/migrations/0001_initial.py) had not been reverted.
That migration used `auth_user.id` as the foreign key in its [models](https://github.com/edx-solutions/progress-edx-platform-extensions/blob/master/progress/models.py), but Django does not resolve this constraint
between existing tables anymore, because the model has been removed.
In  #1862 we are dropping the tables related to deprecated application in order to be able to remove users properly. …
=> [MCKIN-21879] Remove foreign keys from deprecated `progress-edx-platform-extensions`

lms/djangoapps/email_marketing/signals.py, lms/envs/common.py, openedx/core/djangoapps/cors_csrf/tests/test_middleware.py, openedx/core/djangoapps/lang_pref/middleware.py, openedx/core/djangoapps/lang_pref/tests/test_middleware.py, openedx/core/djangoapps/lang_pref/views.py, openedx/core/djangoapps/user_authn/views/auto_auth.py, requirements/edx/base.in, requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-22396
In Scorm shell login flow, the platform is loaded in an iframe from a cross origin ancestor. Hence we need the sessionid and csrftoken cookies to have samesite='None' and secure=True (after chrome update).
Commits:
https://github.com/edx/edx-platform/commit/7b3525278ebe3efbd7138a65343aff609de41838
https://github.com/edx/edx-platform/commit/bb85420e914978dc8c53d8bb180afc2a4b0d580c
Related PR without cherry-picked commits: https://github.com/edx-solutions/edx-platform/pull/1876
=> MCKIN-22396 Fix samesite cookie issue for Scorm Shell login flow

common/lib/xmodule/xmodule/graders.py, common/lib/xmodule/xmodule/tests/test_graders.py, lms/djangoapps/gating/api.py, lms/djangoapps/grades/course_grade.py, lms/djangoapps/grades/scores.py, lms/djangoapps/grades/subsection_grade.py, lms/djangoapps/grades/tests/test_subsection_grade.py, lms/templates/courseware/progress.html
This reverts commit fde830b73aae88227869588e83752bf5b38c0842.
this commit introduced in ironwood rebase and was being used for specific rounding criteria which is conflicting to Apros as well as Xblocks rounding.
=> MCKIN-22514 Proficiency is not rounding off correctly

common/djangoapps/database_fixups/migrations/0002_remove_foreign_keys_from_progress_extensions.py
This is a follow up PR to #1874. It adds `reverse_sql` to the migration introduced there.
1. Run `./manage.py lms migrate database_fixups`.
1. Go to `dbshell`, run `SHOW CREATE TABLE progress_coursemodulecompletion` and check that the `CONSTRAINT` is no longer present there.
1. Run `./manage.py lms migrate database_fixups 0001`.
1. Go to `dbshell`, run `SHOW CREATE TABLE progress_coursemodulecompletion` and check that the `CONSTRAINT` is present now.
**Author's concerns**:
Applying this migration is rather fast, but reverting it is around 15 times slower on my machine. I tried disabling `FOREIGN_KEY_CHECKS`, but it didn't help. Also when I run these 3 SQL queries manually via the `dbshell`, they take around 0.01s each.
```bash
time ./manage.py lms migrate …
```
=> [BB-2765] Add `reverse_sql` to `database_fixups/0002` migration

lms/djangoapps/django_comment_client/utils.py
`sorted` function does not order the list containing alphanumeric strings in some cases. For example:
`>>> test_list = [('General', 'General', 'entry'), ('Lesson 4', 'Lesson 4', 'subcategory'), ('Lesson 5', 'Lesson 5', 'subcategory'), ('Lesson 6', 'Lesson 6', 'subcategory'), ('Lesson 7', 'Lesson 7', 'subcategory'), ('Lesson 2', 'Lesson 2', 'subcategory'), ('Lesson 3', 'Lesson 3', 'subcategory'), ('Lesson 8', 'Lesson 8', 'subcategory'), ('Lesson 9', 'Lesson 9', 'subcategory'), ('Lesson 11', 'Lesson 11', 'subcategory'), ('Week 1', 'Week 1', 'subcategory'), ('Lesson 10', 'Lesson 10', 'subcategory'), ('Lesson 1', 'Lesson 1', 'subcategory')]`
`>>> [(x[0], x[2]) for x in sorted(test_list, key=lambda x: x[1])]`
`[('General', 'entry'), ('Lesson 1', 'subcategory'), ('Lesson 10', 'subcategory'), …
=> MCKIN-24663 sorting alphanumeric list

cms/djangoapps/course_creators/models.py
Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-24885
LMS is not able to access the model CourseCreator, due to missing app label.
The result is it failure of user deletion since MYSQL does not know what to do with the foreign_key between CourseCreator and User in absence of django model code.
=> MCKIN-24885 CMS: Add missing app_label

common/static/common/js/discussion/views/discussion_inline_view.js, common/static/common/templates/discussion/thread-list-item.underscore, lms/djangoapps/discussion/static/discussion/js/discussion_router.js
Fixed the followings:
1. Post Anonymously is not working accordingly. On posting 2nd time, the user has to select the checkbox again for the anonymous post.
2.  On posting a question, the string is shown as follows: "discussion posted 4 minutes ago by {user}". It should be written as a "question posted 4 minutes ago".
=> MCKIN-25091 fixed Discussion post Anonymously

requirements/edx/custom.txt
Bumps version of group project XBlock to include changes from https://github.com/open-craft/xblock-group-project-v2/pull/145
That PR fixes unnecessary error logs in studio.
=> [YONK-1748] Update group projects version to include fix for unnecessary error logs

lms/urls.py
This PR fixes broken unit tests of `edx-platform` under `lms/djangoapps/badges`.
=> MCKIN-26666: fix unit tests for lms badges app

lms/urls.py
This PR solves the warning produced when a server is started for namespace of URL.
**JIRA tickets**: [YONK-1822](https://openedx.atlassian.net/browse/YONK-1822)
~~**Screenshots**: Always include screenshots if there is any change to the UI. Can be useful for people that are not reviewer but want to know what's going on.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned (if needed).~~
1. Clone this repo and checkout to the branch
2. Restart the server and observer the logs, you should not see `?: (urls.W005) URL namespace 'completion_aggregator' isn't unique. You may not be able to reverse all URLs in this namespace` warning.
None
**Reviewers**
=> [YONK-1822][BB-3217] Added namespace to URL to avoid warnings

lms/djangoapps/instructor_task/models.py
Increased expiry time of s3 csv file link to 20 minutes. This would help avoid link expiration when poll report are created for courses with large number of users.
=> MCKIN-24991 Increased expiry time of s3 csv file link to 20 minutes

cms/templates/container.html
This fix is to only show those xblock in navigation bar/breadcrumb which have their pages.
**JIRA tickets**: [BB-3205](https://tasks.opencraft.com/browse/BB-3205)
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Dependencies**: None~~
Before:
After:
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
* Get the devstack to run
* Install problem-builder in the devstack
* Configure [problem-builder](https://github.com/open-craft/problem-builder/blob/master/doc/Usage.md) by adding it to advance module in studio
* Create a step-builder in demo course
* Navigate …
=> [BB-3205] Fix showing links with none on breadcrumb

openedx/core/djangoapps/user_api/completion/tasks.py, openedx/core/djangoapps/user_api/completion/tests/test_tasks.py
This PR implements updating of gradebooks for users for which we do migration of progress.
Same as for https://github.com/edx-solutions/edx-platform/pull/1952, but now leaderboard and course details page should show correct data.
**Reviewers**
=> [MCKIN-27241] [BB-3434] Update user gradebooks after migration

openedx/core/djangoapps/user_api/completion/tasks.py
This PR adds removal of stale aggregators. Without this, [users_above_qs queryset](https://github.com/edx-solutions/api-integration/blob/c46d1f3f4834fbcba3913462853552f8acb7815b/edx_solutions_api_integration/courses/utils.py#L128-L133) returns an incorrect set of users, which results in generating of incorrect metrics.
**JIRA tickets**:
[BB-3434](https://tasks.opencraft.com/browse/BB-3434)
**Reviewers**
=> [BB-3434] Remove stale aggregators

lms/envs/common.py
User deletion fails for users who have entries in user_tasks__usertaskstatus table. 
Users have entries in this table who have attempted to export/import a course on studio.
This happens becuase lms is not able to detect user_tasks django app.
This PR fixes that.
=> MCKIN-24885 Add user_tasks to lms installed apps

openedx/core/djangoapps/contentserver/middleware.py
Converting session_id to string as `engine.SessionStore` expects a string
=> MCKIN-29127 - Session id bytes conversion

lms/djangoapps/discussion/rest_api/api.py
While deleting a post, the number of comments are retrieved where API reports wrong number of total pages due to PY3 incompatible division:
```
response.data["pagination"]
{'previous': None, 'count': 3, 'num_pages': 1.02, 'next': 'http://apros.devstack.lms?ajax=1&page=2'}
```
Which results in `PageNotFoundError`:
```
is_thread)):
File "/edx/src/discussion-edx-platform-extensions/social_engagement/engagement.py", line 382, in _get_paginated_results
has_next = response.data["pagination"]["next"]
File "/edx/app/edxapp/edx-platform/lms/djangoapps/discussion/rest_api/views.py", line 526, in retrieve
form.cleaned_data["requested_fields"],
File "/edx/app/edxapp/edx-platform/lms/djangoapps/discussion/rest_api/api.py", line 1074, in get_response_comments
raise PageNotFoundError("Page not found (No …
```
=> MCKIN-29165 - Discussion post deletion fix

openedx/core/djangoapps/user_api/completion/tasks.py, openedx/core/djangoapps/user_api/completion/tests/test_tasks.py
This PR contains fixes to the merging of user accounts, specifically merging when the target is already enrolled in the course but has no progress in it.
**JIRA tickets**: MCKIN-27241
**Discussions**: Jira ticket
1. Checkout this branch in your devstack.
1. Create three users, e.g. A, B, and C, and enroll all in a test course.
1. Browse the test course with users A and B, generating progress.
1. Run the migration from user A to B and see it fail, as user B already has progress.
1. Unenroll user C from test course, making the enrollment inactive.
1. Run the migrate from user A to C, and watch it succeed.
**Reviewers**
=> [MCKIN-27241] Merge user progress when target is enrolled but has no progress

openedx/core/djangoapps/user_api/completion/tasks.py, openedx/core/djangoapps/user_api/completion/tests/test_tasks.py
Merge user progress when target is enrolled but has noprogress (#2065)
During user progress migration, targets already enrolled in the course are now acceptable if they have no progress in that course already. In case progress already exists, the migration to that user will be skipped.
=> [MCKIN-27241] Cherry Pick Commit

common/static/common/js/discussion/mathjax_include.js
MathJax was also parsing the Django Debug Tool bar which caused performance issues.
'djdt-hidden' class is added in the filter to ignore during parsing.
=> MCKIN-29636 <MckA> Discussion (forum + inline) - Content is not loading quickly in Preview box

.circleci/config.yml, lms/djangoapps/instructor_analytics/basic.py, lms/djangoapps/instructor_task/models.py, lms/djangoapps/instructor_task/tasks_helper/grades.py, lms/djangoapps/instructor_task/tasks_helper/utils.py, lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Calculating student responses batch wise while generating report for xblock-poll. 
Production server is running out of memory and killing the process when generating report for courses which have large amount of user responses. The large number of responses can be due to large number of students enrolled, large number of module having a poll or survey or both. In current implementation, `_build_student_data` returns a list of all responses which is then written to a file. Each item of a list is a response to a single question. The course that encountered this error on production had ~100k responses. To counter this problem, responses are now yielded by `_build_student_data` batch wise which are written to the file simultaneously. This approach will avoid having to store all the responses …
=> MCKIN-24991 Calculating student responses batch wise for xblock-poll

common/lib/xmodule/xmodule/modulestore/xml.py
`etree.tostring` uses ASCII encoding by default. Many characters are not supported in ASCII which results in errors. Specifying unicode encoding while parsing xml to handle such errors.
=> MCKIN-31550 - Parsing xml using unicode to handle special characters

openedx/core/djangoapps/course_groups/cohorts.py, openedx/core/djangoapps/course_groups/tests/test_cohorts.py
In modules with cohorted discussions, course staff were being assigned a random cohort from the course. Changing this behavior to assign `default_cohort` to the staff.
=> MCKIN-31000 - Adding course staff to default_cohort when viewing cohorted discussion

lms/djangoapps/courseware/user_state_client.py, lms/djangoapps/instructor_task/tasks_helper/grades.py
Previously, `iter_all_for_block` would return an iterator that would iterate over all the users that have submitted response to a block. This resulted in generating response data for all users that have submitted a response to a block. After the change, `iter_all_for_block` would return iterator over specified batch of users. As a result response data would be generated for only the users in the batch.
=> MCKIN-24991 - Improving performance by not generating redundant data

common/djangoapps/database_fixups/migrations/0003_remove_foreign_keys_from_edx_django_oauth2_provider.py
The `edx-django-oauth2-provider` has been deprecated in favor of `django-oauth-toolkit`.
Its tables however persist in database. They have foreign key dependency with `auth_user.id`. Django does
not resolves this constraint and we are unable to delete users.
The `ON DELETE` behavior in these tables for foreign keys is set to `NO ACTION`. This migration alters this behavior and set it to `CASCADE`. This will allow the users to be deleted.
=> MCKIN-32075 - Migration to alter foreign key on delete behaviour of oauth2 tables to CASCADE

requirements/edx/base.in, requirements/edx/base.txt, requirements/edx/custom.txt, requirements/edx/development.txt, requirements/edx/testing.txt
This PR bump xblock eoc journal version to 0.10.1 and Also cherry-picks `py2neo` fix from `release-freeze` to fix build failures on CI on development branch
=> MCKIN-32454: bump xblock eoc journal version to 0.10.1

lms/djangoapps/instructor_task/tasks_helper/grades.py
Fixing error in case where there is no response to the poll/survey when generating poll/survey report.
In case when the poll/survey do not have any response, `student_data` inside `_build_student_data` function is an empty array in the first iteration. Previously the `break` statement was above the yield statement and in the above mentioned scenario, the function did not returned anything. This would cause the while loop in `generate` function to not run. The `output_buffer` remains `None` and gives an error on `output_buffer.seek(0)`.
Also in implementation before this ticket, in case of no response, `student_data_keys_list` was returned from `_build_student_data` function which would be the only row in resulting csv file.
By moving the `break` statement below `yield`, we ensure that …
=> MCKIN-24991 - Fix for reports with no responses

lms/djangoapps/courseware/user_state_client.py, lms/djangoapps/instructor_analytics/basic.py, lms/djangoapps/instructor_analytics/tests/test_basic.py, lms/djangoapps/instructor_task/tasks_helper/grades.py, lms/djangoapps/instructor_task/tests/test_tasks_helper.py
This PR reduces memory consumption and improves performance of poll report generation process.
1. Instead of batching `_build_student_data` on basis of users, it is now batched on modules. After responses for a module are calculated, they are yielded and written to a file instead of keeping them all in memory at a time.
2. `StudentModule` is filtered only using `module_state_key` as this field is indexed.
3. Reducing database calls to `auth_user` table by using `select_related` in query. This ensures that no additional database calls are made when later iterating over the queryset and getting `username` from related object.
=> MCKIN-24991 - Batching poll report responses generation on basis of modules

requirements/edx/base.in, requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
Upgrading `django-ses` version to `2.0.0`. This version uses AWS Signature V4 as older versions are deprecated.
=> MEI-7725 - Upgrade django-ses version

openedx/core/djangoapps/content_libraries/permissions.py, requirements/edx/base.in, requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/github.in, requirements/edx/testing.txt
Bridgekeeper's edX fork started breaking on `Python3.5.2` because it requires [setuptools_scm>=1.11.1](https://github.com/edx-unsupported/bridgekeeper/blob/edx_release_py3/setup.py#L10) which's latest version has dropped support for [python < 3.6.](https://github.com/pypa/setuptools_scm/blob/main/setup.py#L21)
upstream PR: https://github.com/edx/edx-platform/commit/e3d85bcd74c3f2bb9bb615f2378d46b31d876df2
=> Bridgekeeper upgrade
