common/static/coffee/spec/discussion/discussion_spec_helper.coffee
common/static/coffee/spec/discussion/view/new_post_view_spec.coffee
common/static/coffee/src/discussion/discussion_module_view.coffee
common/static/coffee/src/discussion/views/new_post_view.coffee
common/templates/discussion/_underscore_templates.html
lms/djangoapps/django_comment_client/forum/views.py

Some upstream changes I assumed would be in the repository were not, so they have been backported. A few additional adjustments were made, and this appears to be working properly now.

Fix is_commentable_cohorted hiding

---

common/static/coffee/spec/discussion/discussion_spec_helper.coffee
common/templates/discussion/_underscore_templates.html

Places the topic dropdown in a wrapper div.
It may be useful to [view this change with whitespace ignored](https://github.com/edx-solutions/edx-platform/pull/373/files?w=1).

Add wrapper to discussion topic dropdown.

---

lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/views.py

@mattdrayer @martynjames @markoivanovic I have made these fixes to address issues raised in MCKIN-2948 and MCKIN-2955.

fixed issues with organization metrics when organization has multiple courses

---

requirements/edx/custom.txt

I believe this is self-explanatory
cc @antoviaque

Added officemix xblock to requirements

---

lms/djangoapps/organizations/views.py

@markoivanovic added default value for `complete_status`

added default value for complete_status

---

requirements/edx/custom.txt

This needs to be merged after 
https://github.com/edx-solutions/xblock-group-project/pull/39

MCKIN-2986 Update group project xblock version

---

common/static/coffee/spec/discussion/discussion_spec_helper.coffee
common/static/coffee/spec/discussion/view/discussion_thread_list_view_spec.coffee
common/static/coffee/src/discussion/views/discussion_content_view.coffee
common/static/coffee/src/discussion/views/discussion_thread_list_view.coffee
common/static/coffee/src/discussion/views/discussion_thread_view.coffee
common/templates/discussion/_underscore_templates.html
common/test/acceptance/pages/lms/discussion.py
common/test/acceptance/tests/discussion/test_discussion.py

* Fixes bug with showing response vote count twice - cherry-picked upstream commit
* Added ability to set custom css classes on search messages

Discussion bug fixes and improvements

---

requirements/edx/custom.txt

poll: Update hash

---

lms/djangoapps/django_comment_client/forum/views.py

Extracted setting group name into method, added group names to followed posts response

Fixed cohort visibility label when viewing "Posts I'm following"

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/management/commands/tests/test_migrate_courseids.py
lms/djangoapps/api_manager/test_receivers.py
lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/courseware/management/commands/tests/test_delete_course_references.py
lms/djangoapps/gradebook/management/commands/tests/test_generate_gradebook_entries.py
lms/djangoapps/gradebook/tests.py
lms/djangoapps/instructor/tests/test_receivers.py
lms/djangoapps/progress/management/commands/tests/test_generate_progress_entries.py
lms/djangoapps/projects/management/commands/tests/test_migrate_project_courseids.py
lms/djangoapps/projects/tests/test_receivers.py
lms/djangoapps/projects/tests/test_workgroups.py
lms/envs/common.py

@chrisndodge -- updated all of the static date references and added settings overrides where needed, as well.  Could have gotten more clever with the dates but I figured a five year offset would be sufficient for now.

mattdrayer/fix_broken_tests: Updated stale dates throughout test suite

---

lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py
lms/djangoapps/django_comment_client/tests/management/test_export_discussion_participation.py
lms/djangoapps/django_comment_client/tests/test_utils.py
lms/djangoapps/django_comment_client/utils.py
lms/lib/comment_client/tests.py
lms/lib/comment_client/user.py

Refactored export discussion participation command to improve testability.
Added tests for export discussion participation command and related changes

Tests for export discussion participation command

---

lms/djangoapps/api_manager/users/views.py

@martynjames -- updated the API operation to return complete_status of False when the user's grade is zero.

mattdrayer/MCKIN-3046-2: False status for zero grades

---

requirements/edx/custom.txt

Merge release into master

---

lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py
lms/djangoapps/django_comment_client/tests/management/test_export_discussion_participation.py

Now exports number of threads read in social data.

Added threads read to export of discussion participation.

---

common/lib/xblock/discussion/discussion_forum/discussion_forum.py
requirements/edx/custom.txt
requirements/edx/github.txt

@ziafazal restored XBlock, mentoring and notification versions.

Switched to rebased XBlock version + restored some xblock dependencies

---

requirements/edx/github.txt

@ziafazal Updated XBlock version to include https://github.com/edx-solutions/XBlock/commit/6e0495b68d64c27bbbc46c7946e3cc11142ab747

Updated XBlock version

---

lms/djangoapps/api_manager/migrations/0014_auto__del_organization.py

Reverts edx-solutions/edx-platform#435

Revert "clean up unnecessary migration"

---

common/static/coffee/src/discussion/discussion_router.coffee
common/static/coffee/src/discussion/views/discussion_thread_view.coffee

Backported fix from previous rebase.

Load thread if requested thread isn't loaded yet.

---

common/static/coffee/spec/discussion/discussion_router_spec.coffee
common/static/coffee/spec/discussion/view/new_post_view_spec.coffee
common/static/coffee/spec/discussion/view/thread_response_show_view_spec.coffee
common/templates/discussion/_course_discussion_section.html
common/templates/discussion/_discussion_course.html
common/templates/discussion/index.html

Follow up of #448. Includes the following:
* Fixed discussions-related tests failures
* Restored proper discussion/index.html template - using `_discussion_course.html` might make sense, but resulted in including discussion js and css twice.
* Added some discussion router tests to check thread rendering (specifically, when thread was not loaded yet).

Fixing various issues after birch rebase

---

lms/djangoapps/django_comment_client/management/commands/export_discussion_participation.py
lms/djangoapps/django_comment_client/tests/management/test_export_discussion_participation.py
lms/lib/comment_client/user.py

Improves the functionality of the `export_discussion_participation` command.
**Dependency:** https://github.com/edx-solutions/cs_comments_service/pull/17

Improve social stats dumping functionality

---

lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/views.py

Makes the User API update the user's email if it is provided in the POST request.

User api email update

---

common/lib/xmodule/xmodule/modulestore/search.py
lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/urls.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/courseware/views.py

Implements jump_to_id functionality for XBlock children.

Jump to children

---

requirements/edx/custom.txt

Latest commit on group project that should remove the modal pop-up scrollbar.

Update xblock-group-project hash

---

requirements/edx/custom.txt

@vkaracic Could you please review this?

(MCKIN-3164) Updated group work hash

---

lms/djangoapps/api_manager/users/serializers.py
lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/views.py

This is a prerequisite for YONK-69:
https://openedx.atlassian.net/browse/YONK-69

API call to display 'is_staff' attribute

---

common/lib/xmodule/xmodule/modulestore/__init__.py
lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/views.py
lms/djangoapps/gradebook/management/commands/generate_gradebook_entries.py
lms/djangoapps/gradebook/migrations/0003_add_fields_studentgradebookhistory_progress_summary_grade_summary_grading_policy.py
lms/djangoapps/gradebook/models.py
lms/djangoapps/gradebook/receivers.py

@mattdrayer Here's a PR marked as WIP regarding YONK-8. I followed the guidelines you left in the ticket description.
Story in JIRA: https://openedx.atlassian.net/browse/YONK-8

(YONK-8) Performance Improvement - UsersCoursesGradesDetail

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/api_manager/management/commands/tests/test_migrate_courseids.py
lms/djangoapps/api_manager/management/commands/tests/test_migrate_courseids_v2.py
lms/djangoapps/api_manager/management/commands/tests/test_migrate_stage_prefix.py
lms/djangoapps/api_manager/test_receivers.py
lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/urls.py
lms/djangoapps/api_manager/users/views.py
lms/djangoapps/courseware/grades.py
lms/djangoapps/gradebook/management/commands/tests/test_generate_gradebook_entries.py
lms/djangoapps/gradebook/management/commands/tests/test_migrate_gradebook_courseids_v2.py
lms/djangoapps/gradebook/receivers.py
lms/urls.py

@Kelketek -- everything appears to be passing locally for both the api_manager and projects unit test suites -- can you confirm on your side?

mattdrayer/cypress-rebase-api: Fixed broken api_manager unit tests

---

common/lib/xblock/discussion/discussion_forum/discussion_forum.py

@bradenmacdonald @e-kolpakov This is ready for review-- should prevent the Discussion forum from being mangled in Apros.

Add discussion forum CSS to forum XBlock render.

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#494 - should have been merged to cypress-rebase branch

Revert "Hash update: Poll XBlock"

---

lms/djangoapps/django_comment_client/forum/views.py

This reverts commit d0e44cd71e21b1b38ae176a8bfe956f0521202dd.
@smagoun @antoviaque

Revert "Better handling of group IDs in thread queries."

---

lms/djangoapps/gradebook/management/commands/generate_gradebook_entries.py
lms/djangoapps/gradebook/management/commands/tests/test_generate_gradebook_entries.py
lms/djangoapps/gradebook/tests.py

@vkaracic These are additional tests for YONK-8.
You can check the assertions and also use this branch to add more tests.

(YONK-120) Fix for the 500 error on progress page

---

cms/envs/common.py
lms/envs/common.py

Updated GP v1 notifications URL resolver to use new querystring attribute

[YONK-146] Fix GP v1 notifications

---

lms/djangoapps/api_manager/users/views.py

(YONK-158) Addressing issue with progress page - 500 error

---

requirements/edx/custom.txt

This is a simple hash update to include the Problem Builder changes from https://github.com/open-craft/problem-builder/pull/61 (Assessment targeted review)
The problem builder code is already reviewed so no further review is required for this hash update.

Hash update: Problem Builder

---

lms/static/sass/discussion/views/_thread.scss

Remove extraneous width setting from .response-header-actions

---

lms/djangoapps/progress/migrations/0004_studentprogress_add_indexes.py
lms/djangoapps/progress/models.py

Add indexes to the StudentProgress model for performance, per https://openedx.atlassian.net/browse/YONK-215
@bradenmacdonald @smarnach Please review at first opportunity.

Add indexes to 'modified' and 'completions' on StudentProgress model.

---

lms/djangoapps/gradebook/migrations/0004_auto__add_index_studentgradebook_created__add_index_studentgradebook_g.py
lms/djangoapps/gradebook/models.py

Add indexes to grade and modified fields on StudentGradebook

Gradebook indexes

---

requirements/edx/custom.txt

Bump problem builder version to include a few recent bugfix PRs

Bump problem builder

---

requirements/edx/custom.txt
requirements/edx/github.txt

xblock-utils: Update hash

---

requirements/edx/custom.txt
requirements/edx/github.txt

That version is required by Problem Builder.
Also remove the duplicate entry for xblock-utils in requirements/edx/custom.txt.

Update hash of xblock-utils to the latest version.

---

requirements/edx/custom.txt

To include https://github.com/open-craft/problem-builder/pull/90

Version bump problem builder

---

requirements/edx/custom.txt

To include https://github.com/open-craft/xblock-poll/pull/9

Version bump xblock-poll

---

lms/djangoapps/projects/tests/test_projects.py
lms/djangoapps/projects/views.py

**Description:** API (and related) updates to required for GP v2 [dashboard](https://edx-wiki.atlassian.net/browse/MCKIN-3221) and [dashboard details views](https://edx-wiki.atlassian.net/browse/MCKIN-3029)

Group Project updates to API

---

lms/djangoapps/courseware/testutils.py
lms/djangoapps/progress/signals.py
lms/envs/aws.py

**Description:** Part of three-PR changeset. Description and testing instructions are given on the [other PR](https://github.com/open-craft/xblock-group-project-v2/pull/73).

Group Project v2: student progress

---

requirements/edx/custom.txt

@zvishal @antoviaque Updating hash for bug fixes.

Hash Update #4: Diagnostic-Feedback [Bug fixes]

---

requirements/edx/custom.txt

To include https://github.com/open-craft/problem-builder/pull/93

Version bump problem-builder

---

requirements/edx/custom.txt

All changes have been covered by prior pull-requests: 
* https://github.com/open-craft/xblock-group-project-v2/pull/80

Updated hash code for group-project-v2

---

requirements/edx/custom.txt

All changes have been reviewed in following requests: 
- https://github.com/edx-solutions/xblock-mentoring/pull/119
- https://github.com/edx-solutions/xblock-mentoring/pull/120

Update hash code for xblock mentoring

---

requirements/edx/custom.txt

Includes IE fix: https://github.com/edx-solutions/xblock-ooyala/pull/62

Update hash for xblock-ooyala.

---

requirements/edx/custom.txt

Includes IE tweaks: https://github.com/edx-solutions/xblock-adventure/pull/16

Hash update: xblock-adventure.

---

requirements/edx/custom.txt

This change was already reviewed as a part of: 
- https://github.com/open-craft/xblock-group-project-v2/pull/85

Bump the requirements for gw-v2

---

requirements/edx/custom.txt

Problem Builder version bump.
New hash includes changes from #99 and #95.

Problem Builder version bump

---

requirements/edx/custom.txt

updated group-project-v2 hash

---

requirements/edx/custom.txt

updated gp-v2 hash

---

requirements/edx/custom.txt

bump group project v2 hash

---

requirements/edx/custom.txt

Brings in https://github.com/open-craft/xblock-group-project-v2/pull/97

Bump Group Work v2 Hash

---

requirements/edx/custom.txt

Update includes:
- https://github.com/open-craft/problem-builder/pull/110 (Enable freeform answer submit when feedback is hidden; MKCIN-3890)

Hash update: problem builder.

---

lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/views.py

Update user detail API to add last_login

---

requirements/edx/custom.txt

Hash update GWv2. Changes were already reviewed by these two PRs: 
- https://github.com/open-craft/xblock-group-project-v2/pull/98
- https://github.com/open-craft/xblock-group-project-v2/pull/99

Hash update GWv2

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/progress/models.py

@ziafazal :eyes: , this PR updates api_manager.courses.views.CoursesMetrics api to allow filtering of users by groups.

Update course metrics API to allow filtering of users by groups

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/gradebook/models.py

Update course metrics grades API to allow filtering of users by groups

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py

Update course time series metrics API to allow filtering of users by groups

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/gradebook/models.py

Update course metrics grades leaders API to allow filtering of users by groups

---

requirements/edx/custom.txt

All changes were reviewed in this PR: https://github.com/open-craft/problem-builder/pull/115 .

Bump hash for problem builder

---

requirements/edx/custom.txt

Includes updates from https://github.com/open-craft/problem-builder/pull/116

Update problem builder hash.

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/gradebook/models.py

fix user group filter to return distinct users data

---

requirements/edx/custom.txt

All changes reviewed in this PR: 
- https://github.com/edx-solutions/xblock-ooyala/pull/63

Update Ooyala hash

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/api_manager/utils.py
lms/djangoapps/progress/models.py

This PR updates course completion metrics API to allow filtering of users by groups and disables default limit of three on leaders, also did some refactoring in this PR.
@ziafazal 👓

Update course completion metrics API

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py

Update course users API to return additional fields and add workgroup filter

---

lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/views.py

This PR supports removal of user and organization link. It also has some code refactoring in tests to remove duplicate code.
@mattdrayer would you review this one?

Ziafazal/yonk-298: organization user removal support

---

requirements/edx/custom.txt

All changes already reviewed by: 
- https://github.com/open-craft/xblock-group-project-v2/pull/101 
- https://github.com/open-craft/xblock-group-project-v2/pull/102

Update custom.txt (bump GWv2 hash)

---

lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/views.py

Based on feedback of YONK-298 we should send a 204 status code if API did not remove any user. 
@msaqib52  would you please review this one?

Ziafazal/yonk-298: organization user removal support feedback

---

lms/djangoapps/api_manager/courses/serializers.py
lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/views.py

This PR creates a new API endpoint to get list courses an organization is hosting.

Add API endpoint to get list of courses in an organization

---

lms/djangoapps/api_manager/urls.py
lms/djangoapps/organizations/migrations/0004_auto__add_organizationgroupuser__add_unique_organizationgroupuser_orga.py
lms/djangoapps/organizations/models.py
lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/urls.py
lms/djangoapps/organizations/views.py

YONK-302: Adds API endpoint to link Organization permission groups with users

---

lms/djangoapps/organizations/tests.py
lms/djangoapps/organizations/views.py

This PR fixes server error when requested organization's groups have no course.

fix error when organization group have no courses

---

requirements/edx/custom.txt

@mattdrayer  @ziafazal 
Brings in 
https://github.com/open-craft/xblock-group-project-v2/pull/105

MCKIN-4174 Group Work v2: hash update 

---

lms/djangoapps/api_manager/permissions.py
requirements/edx/custom.txt

This PR creates ``SecureModelViewSet`` and ``SecurePaginatedModelViewSet`` classes to apply custom access permissions on a ``ModelViewSet``s. Also bumps the release tag for organizations and projects app to apply access permissions on these apps using above classes.

Add classes to apply access permissions on a ModelViewSet

---

requirements/edx/custom.txt

bump grade book app version

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/api_manager/users/serializers.py
lms/djangoapps/api_manager/users/tests.py

This PR fixes a bug related to course users and users list API returning system bases roles instead of course based roles.
@msaqib52 would you please review.

ziafazal/YONK-332: course users and users list API returning course based roles

---

requirements/edx/custom.txt

This PR updates version number of [organizations](https://github.com/edx-solutions/organizations-edx-platform-extensions/tree/v1.0.2) app which fixes the organizations list api to return number of courses in which this organization has it’s users enrolled in.

YONK-334: update organizations app version to fix organization list api number_of_courses attribute

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/api_manager/users/tests.py
lms/djangoapps/api_manager/users/views.py

This PR fixes bug which causes number of courses to be always one in both users
list and courses users list APIs.
@msaqib52 would you please review?

ziafazal/YONK-333: Fix bug number of courses is always one

---

lms/djangoapps/api_manager/courses/tests.py
lms/djangoapps/api_manager/courses/views.py
lms/djangoapps/api_manager/users/serializers.py

This PR adds paginations support to course users list API and adds `grades` field having user's grade and proforma grade. It also updates existing tests to support these changes and adds few new tests too.
@msaqib52 would you please review?

ziafazal/YONK-338: added pagination support and user grades

---

requirements/edx/custom.txt

This PR bumps ``organizations`` app version to add support of filtering by ``display_name`` to organizations list API

YONK-340: bump organizations app version

---

requirements/edx/custom.txt

bump organizations app version

bump organizations app version

---

scripts/circle-ci-tests.sh

@msaqib52 this would allow us to run tests in solutions extension apps. Is okay or should we come up with some other solution?

run solutions apps unit tests in circle CI

---

requirements/edx/custom.txt

bump organizations version

---

requirements/edx/custom.txt

bumped org version

---

cms/envs/test.py
lms/envs/aws.py
lms/envs/common.py
lms/envs/test.py
requirements/edx/custom.txt
scripts/circle-ci-tests.sh

This PR updates version of `api_integration`, `organizations` and `projects` apps to pull changes related to renaming of organizations app. It has modifications in settings files reflecting new name for organizations app.
@msaqib52 would you please review?

ziafazal/YONK-345: renaming organizations app

---

cms/envs/test.py
cms/startup.py
lms/djangoapps/courseware/management/commands/tests/test_delete_course_references.py
lms/envs/aws.py
lms/envs/common.py
lms/envs/test.py
lms/startup.py
requirements/edx/custom.txt
scripts/circle-ci-tests.sh

This PR updates ``projects`` app references to its new name ``edx_solutions_projects`` and bumps version of ``api_integration``, ``edx_solutions_organizations`` and ``edx_solutions_projects`` apps to pull changes related to renaming of projects app.

YONK-346: rename projects app

---

requirements/edx/custom.txt

This PR Adds ability to exclude users by their roles in CoursesMetricsGradesLeadersList API

bump edx_solutions_api_integration app version

---

requirements/edx/custom.txt

bumped solutions apps versions

bumped solutions apps versions

---

requirements/edx/base.txt
requirements/edx/custom.txt

bumped versions after adding revert commads

bumped versions after adding revert commads

---

requirements/edx/custom.txt

bumped gradebook version having populate_grade_summary command.

bump gradebook version

---

common/djangoapps/student/management/commands/repair_users_roles_on_all_courses.py
common/djangoapps/student/management/tests/test_repair_users_roles_on_all_courses.py

This is user course roles cleanup script for mckinsey academy

added user course roles repair script

---

common/djangoapps/student/management/commands/repair_internal_admin_instructor_role.py
common/djangoapps/student/management/tests/test_repair_internal_admin_instructor_role.py

Script for fixing internal admin instructor role.

repair_internal_admin_instructor_role script

---

requirements/edx/custom.txt

Ooyala Player's  commit hash in custom requirements is updated to a branch name. That change is required to deploy the updated player in integration/QA environments. 
@ziafazal @zvishal

Ooyala player branch update in custom requirements

---

requirements/edx/custom.txt

to allow for generic messages (copy changes only)

updated polls xblock version on mcka

---

requirements/edx/custom.txt

Xblock-poll hash set to [this](https://github.com/open-craft/xblock-poll/commit/e00aafb0149e207fbd989283756e22df4241dc40) commit  CC @zvishal  @bradenmacdonald

Updated xblock-poll version

---

requirements/edx/custom.txt

This PR pulls in changes from the following constituent PRs (newest first):
* https://github.com/open-craft/problem-builder/pull/133 (Remove migration that extends course_id column)
* https://github.com/open-craft/problem-builder/pull/132 (Implement Completion XBlock)
* https://github.com/open-craft/problem-builder/pull/130 (Extend course_id field to 255 characters)
* https://github.com/open-craft/problem-builder/pull/129 (Instructor Tool uses the Course Blocks REST API)
* https://github.com/open-craft/problem-builder/pull/128 (Uses the same import path for instructor_task.models as edxapp)
* https://github.com/open-craft/problem-builder/pull/127 (Bump version to 2.6.0)
* https://github.com/open-craft/problem-builder/pull/125 (Accessibility updates)
* …

Update problem-builder dependency.

---

circle.yml
common/djangoapps/student/management/tests/test_repair_internal_admin_instructor_role.py
common/djangoapps/student/management/tests/test_repair_users_roles_on_all_courses.py
requirements/edx/base.txt
scripts/install-system-req.sh

This PR addresses two issues to fix Circle CI build integration.
1) Fixed loading of proper environment dependencies
2) fixed quality violations
@bradenmacdonald would you please review it?
@smagoun FYI.

fixed broken tests due to missing packages

---

requirements/edx/custom.txt

updated gradebook app's version

updated gradebook app's version

---

common/djangoapps/third_party_auth/decorators.py

This PR has fix in `allow_frame_from_whitelisted_url` decorator to allow rendering of the custom_auth view in frames. We are now reconstructing `referer_url` without querystring to avoid mistmatch of `sso_url` and `referer_url` incase `referer_url` has querystring in it.
@kotky would you please review this?

 fix to allow frames with McKA IDP SSO

---

requirements/edx/custom.txt

... to pull in changes from https://github.com/open-craft/problem-builder/pull/140 and https://github.com/open-craft/problem-builder/pull/141.
**Reviewers**

Update problem-builder to most recent version

---

requirements/edx/custom.txt

Updated api-integration version to 1.1.0
and added command to remove download files for circle CI env.

updated api-integration version to 1.1.0

---

circle.yml
cms/djangoapps/contentstore/views/course.py
cms/startup.py
lms/djangoapps/django_comment_client/base/tests.py
lms/startup.py
scripts/all-tests.sh

This PR has changes to fix quality violations which would give us green builds on Circle CI.

fixed quality violations

---

requirements/edx/custom.txt

update api-integration version to 1.1.1

update api-integration version to 1.1.1

---

pavelib/paver_tests/test_extract_and_generate.py

This PR cherry picks a commit from upstream to fix broken paver tests.
@ayesha-baig FYI.

Adapt tests to the latest i18n-tools

---

lms/djangoapps/courseware/models.py
lms/djangoapps/courseware/module_render.py
lms/djangoapps/courseware/signals.py
lms/envs/common.py
lms/envs/test.py
requirements/edx/base.txt
requirements/edx/custom.txt
scripts/install-system-req.sh

This branch has changes to fix broken unit tests in solutions apps after ficus upgrade and to fix Circle CI builds.
@ayesha-baig Could you please review?

fix LMS unit tests after ficus upgrade

---

requirements/edx/custom.txt

updated gradebook version to 1.0.6

updated gradebook version to 1.0.6

---

common/templates/discussion/_course_discussion_section.html

removed unnecessary js escaping

removed unnecessary js escaping

---

openedx/core/lib/xblock_builtin/xblock_discussion_course/static/js/discussion_course.js

fix loading of discussion on Prod like environment.

fix loading of discussion on Prod like environment

---

common/static/common/js/discussion/views/discussion_inline_view.js
lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js

@ziafazal, could you please review these changes to adjust the left sidebar and also to enable the discussions header on inline discussion page. 
Here is the related JIRA story, https://openedx.atlassian.net/browse/YONK-533

[YONK-533]: Fix css of inline and course wide discussion

---

requirements/edx/custom.txt

updated discussions app version to fix broken unit tests.

updated discussions app version

---

requirements/edx/custom.txt

reverted social api optimisations.

reverted social api optimisations

---

requirements/edx/custom.txt

bumped api-integration version.

bumped api-integration version

---

requirements/edx/custom.txt

New features were added to xblock-chat.
This PR updates the dependency to enable these features in edx-platform.

Update xblock-chat dependency commit id

---

requirements/edx/custom.txt

Switching to using GPv2 v0.4.2

GPv2 hash update

---

requirements/edx/custom.txt

Bumped api-integration and gradebook versions

Bumped api-integration and gradebook versions

---

requirements/edx/custom.txt

The new version includes tweaks from https://github.com/open-craft/xblock-chat/pull/9.
**Reviewers**:

Update xblock-chat to latest version.

---

requirements/edx/custom.txt

This adds the [End of Course Journal XBlock](https://github.com/open-craft/xblock-eoc-journal) to the list of custom requirements.
**Reviewers**:

Add End of Course Journal xblock to custom requirements.

---

requirements/edx/custom.txt

The new version includes changes from https://github.com/open-craft/problem-builder/pull/147.
**Reviewers**:

Update problem-builder xblock to latest version.

---

requirements/edx/custom.txt

Updates `xblock-eoc-journal` to include changes from https://github.com/open-craft/xblock-eoc-journal/pull/3.
**Reviewers**:

Update EOC Journal XBlock.

---

requirements/edx/custom.txt

This bumps the Problem Builder version to provide a mobile endpoint.

Update Problem Builder with Native API endpoint

---

requirements/edx/custom.txt

Bump version to reflect latest changes to problem builder
**Reviewers**
[ ] @mtyaka

Bump xblock-eoc-journal version

---

requirements/edx/custom.txt

api-integration & gradebook-edx-platform-extensions version updated

YONK-697: Retrieve user details in course passed list API

---

requirements/edx/custom.txt

Added scorm xblock (https://github.com/raccoongang/edx_xblock_scorm)
We want to test out open source scorm xblock on our QA server.

Added scorm xblock

---

requirements/edx/custom.txt

Includes changes from https://github.com/open-craft/xblock-eoc-journal/pull/6.
**Reviewers**:

Update xblock-eoc-journal to latest version.

---

requirements/edx/custom.txt

The new version includes bugfix from https://github.com/open-craft/xblock-eoc-journal/pull/7.
**Reviewers**:

Update EOC Journal XBlock

---

requirements/edx/custom.txt

API-Integration version updated to 1.1.12.

YONK-719: Added mobile course flag in user progress API

---

common/djangoapps/student/roles.py
requirements/edx/custom.txt

updated apps versions after api optiomizations and moving 
McKA specific utility method into api-integration.

Moved McKA specific utility method into api-integration and updated apps versions

---

requirements/edx/custom.txt

api-integration & gradebook-edx-platform-extensions releases updated

YONK-721: Complete Status added in Passed Users API

---

requirements/edx/custom.txt

API optimisations using course blocks. Version of api-integration updated to 1.2.2.

YONK-15: API optimisations using course blocks

---

requirements/edx/custom.txt

Version bump to fix MCKIN-5419

Fix MCKIN-5419 Group Work v2 Installation Issue

---

requirements/edx/custom.txt

api-integration version updated

YONK-15: API optimisations using course blocks (FIX)

---

requirements/edx/custom.txt

Reverting YONK-15 API optimisations using course blocks. Have to investigate some issues we are having with the API optimisations PR.

Reverting YONK-15 API optimisations using course blocks

---

requirements/edx/custom.txt

Version includes content or children in each response to facilitate apros code base.

api integration version updated

---

requirements/edx/custom.txt

User update API allowed to set following attributes as NULL
- country
- city
- gender

YONK-742: User update API allowed to set country,city & gender as NULL

---

cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/tests/test_course_updates.py
cms/envs/common.py
common/djangoapps/student/tasks.py
requirements/edx/custom.txt

This PR has changes required to support urban airship push notifications on course announcements.
@jawadtahir could you please review?

yonk-729: urban airship push notification support

---

lms/djangoapps/courseware/module_render.py
lms/djangoapps/courseware/tests/test_entrance_exam.py
lms/djangoapps/courseware/tests/test_module_render.py
lms/urls.py

[MCKIN-5641] OAuth2 API to call XBlock handlers
**JIRA tickets**: [OC-2996](https://tasks.opencraft.com/browse/OC-2996)
**Reviewers**

[MCKIN-5641] OAuth2 API to call XBlock handlers

---

lms/djangoapps/courseware/tests/test_module_render.py

Fix pep8 violations introduced in https://github.com/edx-solutions/edx-platform/pull/856.

Fix pep8 violations.

---

requirements/edx/custom.txt

Oauth support for user course progress API & user organizations API

YONK-750: Oauth support for user APIs

---

requirements/edx/custom.txt

Updates ooyala xblock to include changes from https://github.com/edx-solutions/xblock-ooyala/pull/71.
**Reviewers**:

MCKIN-5675: Update ooyala xblock.

---

lms/djangoapps/completion_api/models.py
lms/djangoapps/completion_api/serializers.py

Performing calculations earlier, and memoizing the results helps prevent duplicate effort.

Improve the performance of the Completion API.

---

lms/djangoapps/completion_api/models.py
lms/djangoapps/completion_api/serializers.py
lms/djangoapps/completion_api/tests/test_serializers.py
lms/djangoapps/completion_api/tests/test_views.py
lms/djangoapps/completion_api/views.py

Implement an API view that returns the average completion for a course.

completion summary

---

requirements/edx/custom.txt

Fix a TypeError breaking some APIs
This is a version bump to bring in https://github.com/edx-solutions/xblock-ooyala/pull/72

MCKIN-5840 Version bump xblock-ooyala

---

requirements/edx/custom.txt

Pulls in https://github.com/open-craft/problem-builder/pull/163 and https://github.com/open-craft/problem-builder/pull/164

Problem Builder version bump [MCKIN-5435] [MCKIN-5434]

---

requirements/edx/custom.txt

This upgrades `api-integration` and `discussion-edx-platform-extensions` requirements for Engagement API OAuth support.
**Reviewers**:

MCKIN-5311: Update api-integration and discussion extensions.

---

requirements/edx/custom.txt

- Version bump for surveys from v1.3.1 to v1.3.2 for responsive changes.
@wajeeha-khalid  Please review and merge

bump xblock-poll version to v1.3.2

---

requirements/edx/custom.txt

Updates problem builder to new version 2.7.5.
Problem Builder PR: https://github.com/open-craft/problem-builder/pull/165

[MCKIN-5799] Version bump: problem Builder

---

lms/static/scorm/ssla/config_override.js

Replaced default SSLA config file with the one provided by appsembler team for SCORM xblock JCA player.

update config_override.js for scorm ssla

---

requirements/edx/custom.txt

- Added responsive fixes for polls
@wajeeha-khalid  Please review and merge

xblock-Poll version update to v1.3.3

---

requirements/edx/custom.txt

The new version includes changes from https://github.com/edx-solutions/api-integration/pull/70.
**Reviewers**:

Update api-integration to 1.3.4.

---

lms/djangoapps/completion_api/views.py

This is a doc-only fixup to #876

Fix completion API docstring

---

requirements/edx/custom.txt

This pulls in
* https://github.com/open-craft/xblock-poll/pull/36
* https://github.com/open-craft/xblock-poll/pull/37
@murad-hubib @msaqib52 Can one of you please review and merge if the build is green?

Version bump for polls (MCKIN-5706, MCKIN-5939)

---

common/djangoapps/student/migrations/0009_auto_20170921_0954.py
common/djangoapps/student/migrations/0010_auto_20170921_0955.py
common/djangoapps/student/models.py

set city field to char and create db index migration

set city field to char and create db index migration

---

requirements/edx/custom.txt

This pulls in https://github.com/edx-solutions/api-integration/pull/80

MCKIN-5418 Fix cohort avg calculation in new API

---

requirements/edx/custom.txt

- Added missing labels on result view
@wajeeha-khalid  please review and merge against [this PR](https://github.com/open-craft/xblock-poll/pull/38)

Version bump for xblock-poll to 1.3.5

---

requirements/edx/custom.txt

The new version includes feedback popup tweaks for mobile from https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/132.

[MCKIN-5772] Update DnDv2.

---

lms/envs/common.py

Reverts edx-solutions/edx-platform#909

Revert "always set CORS_REPLACE_HTTPS_REFERER to true"

---

lms/envs/common.py

Reverts edx-solutions/edx-platform#907

Revert "added CorsPostCsrfMiddleware to fix csrf referer issue with scorm xblock"

---

requirements/edx/custom.txt

re-introducing latest version of GWv2 with file validation security fixes.

add GWv2 v0.4.3

---

requirements/edx/custom.txt

Includes automatic zone & brackground generation from https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/136.
**Reviewers**:

[MCKIN-5776] Update DnDv2 xblock to v2.1.2.

---

requirements/edx/custom.txt

updated API integration version

updated API integration version

---

requirements/edx/custom.txt

projects-edx-platform-extensions version updated in custom.txt 
WorkgroupsViewSet and ProjectsViewSet are updated for performance improvements in latest version.

YONK-530: API Performance updates

---

requirements/edx/custom.txt

Includes changes from https://github.com/open-craft/problem-builder/pull/171.

[MCKIN-6092] Update problem-builder.

---

requirements/edx/custom.txt

updated api-integration version

updated api-integration version

---

requirements/edx/custom.txt

cf https://github.com/edx-solutions/api-integration/compare/v1.4.1...v1.4.2
**JIRA**: MCKIN-5909, OC-3126
**Reviewer**
CC @jcdyer

MCKIN-5909 Bumps the api-integration version to v1.4.2

---

requirements/edx/custom.txt

Includes changes from https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/135.

[MCKIN-5775] Update drag-and-drop-v2.

---

requirements/edx/custom.txt

This PR includes tests for courses with split module store in the following apps:
- api-integration
- organizations-edx-platform-extensions
- gradebook-edx-platform-extensions
- projects-edx-platform-extensions
- discussion-edx-platform-extensions
- course-edx-platform-extensions
- progress-edx-platform-extensions
Updated release versions of all of the updated apps.
@ziafazal Can you review this?

YONK-16: Added split module store for tests

---

requirements/edx/custom.txt

Includes the new Swipe block from https://github.com/open-craft/problem-builder/pull/172.

[MCKIN-5975] Update problem-builder to v2.7.9.

---

requirements/edx/custom.txt

Bumped api-intergration, social engagement and gradebook apps.

Bumped versions of api-intergration, social engagement and gradebook apps

---

requirements/edx/custom.txt

New version fixes problem with transcripts

Version bump for Ooyala xblock

---

requirements/edx/custom.txt

ooyala version bump

---

requirements/edx/custom.txt

bumped api integration version

bumped api integration version

---

lms/djangoapps/completion_api/tests/test_views.py
lms/djangoapps/completion_api/views.py

Return a completion record for each enrolled course for both the detail and list views, even if the user has not started the course.
Return a 404 from the detail view only if the user is not enrolled in the requested course.
**JIRA tickets**: Implements MCKIN-5978, OC-3156
In a solutions devstack:
1. Create a course with a start date in the past (Course A).  Add some units to it.
1. Create a course with a start date in the future (Course B).  Add some units to it.
1. Create a course with any start date (Course C).
1. Create a user, and enrol her in courses A and B.  (Can even use the new fancy [/api/users/integration-test-users/](https://github.com/edx-solutions/api-integration/pull/86) if you want to :smile:)
1. Login as the user.
1. Visit the REST API …

MCKIN-5978: Return a completion record for each enrolled course

---

lms/envs/common.py
requirements/edx/custom.txt

Adds [xblock-poll](https://github.com/open-craft/xblock-poll) to `OPTIONAL_APPS`. Required by https://github.com/open-craft/xblock-poll/pull/35

Add xblock-poll to optional apps

---

requirements/edx/custom.txt

YONK-798: bumped gradebook version

YONK-798: bumped gradebook version

---

requirements/edx/custom.txt

Includes fix from https://github.com/open-craft/xblock-group-project-v2/pull/116

[MCKIN-6282 ] Bump GPv2 to 0.4.5

---

requirements/edx/custom.txt

cf https://github.com/edx-solutions/xblock-ooyala/tree/v2.0.12
**Reviewer**

MCKIN-6161 Bumps xblock-ooyala to v2.0.12

---

requirements/edx/custom.txt

Adds the new [xblock-virtualreality](https://github.com/open-craft/xblock-virtualreality) to custom dependencies.
**Reviewers**:

Add xblock-virtualreality to custom dependencies.

---

requirements/edx/custom.txt

bumped gradebook and api-integration versions

bumped gradebook and api-integration versions

---

requirements/edx/custom.txt

cf https://github.com/edx-solutions/api-integration/pull/96
**Reviewer**

MCKIN-6328 Bumps version api-integration.git@v1.4.8

---

cms/envs/aws.py
cms/envs/common.py
cms/envs/test.py
lms/envs/aws.py
lms/envs/common.py
lms/envs/test.py
requirements/edx/custom.txt
scripts/circle-ci-tests.sh

This PR has changes to add mobile apps to edx-platfrom and bumped api-integration version.
@ihtram could you please review.

added mobileapps app

---

requirements/edx/custom.txt

Changes include oAuth2 support for mobile app configuration APIs

YONK-811: bumped mobileapps-extensions and api-integration versions

---

requirements/edx/custom.txt

@aamishbaloch  can you please review?

updating release versions in custom.txt

---

requirements/edx/custom.txt

Pulls in fixes from https://github.com/open-craft/problem-builder/pull/173

MCKIN-5975 Updates to Problem Builder Swipe Component

---

requirements/edx/custom.txt

bumped mobile apps version

---

requirements/edx/custom.txt

Changes include addition of organization id filter to mobile apps list API.

YONK-827: Bumped mobileapps-edx-platform-extensions version

---

requirements/edx/custom.txt

Changes include addition of Oauth Support to Course Detail view.

YONK-826: Bumped api-integration version

---

requirements/edx/custom.txt

Changes include the addition of progress to CoursesUsersList

YONK-828: Bumped api-integration version

---

requirements/edx/custom.txt

This pulls in https://github.com/open-craft/xblock-drag-and-drop-v2/pull/17 to fix MCKIN-6342.

MCKIN-6342 Fix select issues in iOS mobile app

---

requirements/edx/custom.txt

Organization param updated in Theme Post

YONK-829: Bumped Version of mobileapps-edx-platform-extensions

---

requirements/edx/custom.txt

Changes include modified User API to include list of enrolled courses instead of count.

YONK-836: Bumped api-integration version

---

requirements/edx/custom.txt

Bump xbox-chat version to include fixes and changes from open-craft/xblock-chat#20 and open-craft/xblock-chat#21
**JIRA ticket**:  MCKIN-6531

[MCKIN-6531] Update xblock-chat version

---

requirements/edx/custom.txt

Bumped api-integration and organizations versions.

YONK-839: Bumped api-integration and organizations versions

---

cms/djangoapps/contentstore/views/course.py
requirements/edx/custom.txt

Bumped edx-notification version which includes addition of notification type in course announcement notification payload

YONK-837: Bumped edx-notification version

---

requirements/edx/custom.txt

Changes include addition of mobile apps & themes detail added in organization API and addition of color attributes in organization's theme model.

YONK-837: Bumped api-integration & mobileapps versions

---

requirements/edx/custom.txt

Changes include PNG Image support to organization logo images and Unnecessary data excluded in Organizations list API

YONK-846: Bumped api-integration & mobileapps versions

---

lms/envs/common.py
requirements/edx/custom.txt

Changes include addition of ios_bundle_id added in users organizations.

YONK-851: Bumped api-integration & mobileapps version

---

requirements/edx/custom.txt

This pulls in a new version of Problem Builder that emits events using an explicit interaction API, for better integration with SCORM shells. This eliminates the need for SCORM shells to use hacky methods for determining when an "interaction" has occurred.
See https://github.com/open-craft/problem-builder/pull/175 for the specific change this brings in.

MCKIN-6513 Bump Problem Builder version

---

requirements/edx/custom.txt

Changes include addition of course settings to add support of having languages of the courses. Logo Image in organization theme is now optional, and its edges are now refined and more clearer.

YONK-852-855: Bumped apps to latest versions

---

lms/djangoapps/completion_api/models.py

Performance of completion v0 api requests is poor when requesting the mean completion ratio for numerous courses, because each one has to be calculated separately.  This ticket caches the results of that calculation, so that it doesn't slow down the QA team, who regularly deals with queries across a large number of courses.
MCKIN-6669, OC-3575
See tickets.
None
N/A
Upon request
ASAP, as this is causing site usability issues for McKinsey QA
1. Enroll the `staff` user in several courses (10-20)
2. While logged in as `staff`, visit https://localhost:8000/api/completion/v0/course/?page_size=30&username=staff&requested_fields=mean.
3. Verify that the request does not take mutiple times as long as the same request without requested_fields=mean.
None

Implement cached calculation of means.

---

circle.yml
common/lib/xmodule/xmodule/html_module.py
requirements/edx/custom.txt
requirements/edx/github.txt

updated custom txt with ginkgo fixes branches and resolved package conflict and fixed broken unit tests which might have been broken due to latest cherry-picks from master.

updated custom txt with ginkgo fixes branches

---

requirements/edx/custom.txt

Changes include the fix of theme not found issue in organization theme.

YONK-860: Bumped mobile apps version

---

requirements/edx/custom.txt

Changes include addition of mobile flag & languages in user course API, a fix to get settings of a course with no initial langauge set.

YONK-862-863: Bumped api integration & course extension versions

---

lms/djangoapps/django_comment_client/base/views.py
requirements/edx/custom.txt

Changes include comments & course settings issue fixed

YONK-864: Bumped Versions

---

lms/djangoapps/course_api/blocks/transformers/__init__.py
lms/djangoapps/course_blocks/api.py
lms/djangoapps/course_blocks/transformers/start_date.py
requirements/edx/custom.txt
setup.py

Changes include addition of new transformer to get start date of each block in course blocks API.

YONK-867: Block's start date added in Course Blocks API

---

openedx/core/djangoapps/content/course_overviews/migrations/0011_courseoverview_language.py
openedx/core/djangoapps/content/course_overviews/models.py
requirements/edx/custom.txt

Changes include addition of language in Course Overview. Course Detail APIs and Course Progress APIs will now return a single language of a course.

YONK-868: Bumped version of api-integration & course-extensions

---

requirements/edx/custom.txt

This increments the version of the new drag-and-drop XBlock, to incorporate improvements that automatically scroll the drag and drop target area while dragging, so that drop zones can be reached.
**Reviewers**

Update DnDv2 (temporary v3 branch).

---

requirements/edx/custom.txt

Bumps version to include https://github.com/open-craft/problem-builder/pull/177

Version bump: Problem Builder

---

requirements/edx/custom.txt

Changes include feature of Remove Images from Organization Theme

YONK-876: Bumped api-integration version

---

requirements/edx/custom.txt

scorm xblock version bump

---

requirements/edx/custom.txt

Changes include feature of Remove Images from Organization Theme

YONK-876: Bumped Mobileapp Version

---

requirements/edx/custom.txt

New version includes fix for html parsing

Image Explorer version bump

---

requirements/edx/custom.txt

This bumps dndv3 to pull in https://github.com/open-craft/xblock-drag-and-drop-v2/pull/23

Bump dndv3 to remove redundant custom css

---

requirements/edx/custom.txt

This PR just bumps the revision of the chat block to fix the alignment of users' text.
**Reviewers**

[MCKIN-6873] Chat XBlock: User's text is right-aligned

---

requirements/edx/custom.txt

Changes include an additional check in metric leaders api to avoid 500 error.

YONK-921: Bumped API integration version

---

requirements/edx/custom.txt

Changes include Organization Courses API optimization.

YONK-927: Version Bumps

---

requirements/edx/custom.txt

Bumped xblock chat version to 0.2

Xblock chat version bump

---

requirements/edx/custom.txt

Ooyala xblock version bump

---

requirements/edx/custom.txt

Changes include new api for getting xblock handler details

YONK-924: Version Bump API-Integration

---

requirements/edx/custom.txt

This pulls in https://github.com/open-craft/problem-builder/pull/180

MCKIN-7030 Add student_view_data to PB Recap components

---

lms/djangoapps/courseware/module_render.py

Changes include Fix of Oauth Issue in Xblock handler API.

YONK-924: Oauth Issue on Xblock handler API

---

openedx/features/course_experience/tests/views/test_course_home.py

Changes include a fix of the issue in test_queries in Home page tests.

YONK-940: Home page queries test fixed

---

common/djangoapps/student/tasks.py

Changes include missing import to be added in for notifications.

YONK-943: MobileApp import was missing

---

lms/templates/discussion/_thread_list_template.html

Changes include addition of filters on discussions.

YONK-946: Discussion Forum Filters Fix

---

common/djangoapps/django_comment_common/signals.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py

Changes include updation of signals to handle cohort discussions.

YONK-938: Signal updated for cohorted discussions

---

requirements/edx/custom.txt

VR xblock version bump to v0.1.1

VR xblock version bump

---

requirements/edx/custom.txt

IE version bump

---

cms/envs/common.py

EDX_SOLUTIONS_API flag enabled for signals to work on course publishing

YONK-952: EDX_SOLUTIONS_API flag enabled

---

requirements/edx/custom.txt

Changes include version bumps with respect to tickets [YONK-950](https://openedx.atlassian.net/browse/YONK-950) & [MCKIN-6903](https://edx-wiki.atlassian.net/browse/MCKIN-6903)

YONK-950 & MCKIN-6903: Version Bumps

---

cms/envs/common.py
cms/envs/test.py

Changes include EDX_SOLUTIONS_API flag enabled for cms and duplicate addition of solution apps removed from tests

YONK-952: EDX_SOLUTIONS_API flag enabled for cms

---

requirements/edx/custom.txt

Changes include api-integration version bump

YONK-952: Version Bump

---

requirements/edx/custom.txt

Changes include User API to support search on first-name and last-name.

YONK-966: Version Bump api-integration

---

requirements/edx/custom.txt

Changes include fix of importing course in existing shell. This was causing inconsistency before in progress.

YONK-994: Version Bump Course Extension

---

requirements/edx/custom.txt

This PR adds ooyala player support to problem builder.

MCKIN-7282: bump xblock problem builder version

---

requirements/edx/custom.txt

Reverts MCKIN-7493 by reverting problem builder version back to 2.10.0 from 2.10.1

revert-MCKIN-7493 problem builder version back to 2.10.0 from 2.10.1

---

requirements/edx/base.txt

This reverts commit dfc8c3a49feb2b687af3cdb744c1773ae172d630.

Revert "Revert "Add redis to requirements""

---

requirements/edx/custom.txt

The update pulls in fixes from https://github.com/open-craft/xblock-eoc-journal/pull/13

[MCKIN-7700] Bump EOC journal

---

openedx/core/djangoapps/dark_lang/middleware.py

Changes include support for xBlock to be translated in course language.

YONK-945: xBlock to be translated in course language

---

requirements/edx/custom.txt

cf https://github.com/open-craft/problem-builder/pull/196

Bumps problem-builder to v2.10.2

---

requirements/edx/custom.txt

Changes include addition of proficiency in User Progress API

YONK-997: api-integration version bump

---

requirements/edx/custom.txt

Changes include the fix for grade updating on change.

YONK-1018: Gradebook extension version bump

---

requirements/edx/custom.txt

Temporary branches set to test in-progress work
`IE->image-explorer-v2`
`DnDv2 -> drag-and-drop-v4`

IE and DnDv2 version bump

---

requirements/edx/custom.txt

Updated xblock drag and drop egg name to trigger build on integration server.

change drag and drop egg name

---

requirements/edx/custom.txt

Bumps version of the Group Project v2 XBlock to include bugfix in open-craft/xblock-group-project-v2#121.

upgrade group project v2

---

requirements/edx/custom.txt

Bump projects-edx-platform-extensions to include https://github.com/edx-solutions/projects-edx-platform-extensions/pull/18

Bump verison of projects-edx-platform-extensions

---

lms/lib/comment_client/utils.py

Error message modified to get more error details for https://openedx.atlassian.net/browse/YONK-1058

Error message modified to get more error details

---

cms/djangoapps/contentstore/signals/handlers.py

`https://openedx.atlassian.net/browse/YONK-1007`
Event transaction ID converted to Unicode

YONK 1007 - Event transaction ID converted to Unicode

---

requirements/edx/custom.txt

API integration version update

YONK-1067: Verify Bearer Token

---

requirements/edx/custom.txt

@bradenmacdonald @xitij2000  or @pomegranited Please review.

Bump completion_aggregator version to 1.1

---

requirements/edx/custom.txt

Include changes in https://github.com/open-craft/problem-builder/pull/203

Bump problem builder version to 2.10.3 to include theme fixes

---

requirements/edx/custom.txt

related commit: https://github.com/edx-solutions/xblock-drag-and-drop-v2/commit/26bcdb0404f72476a5d355b3e6660b96fc611052
Mcka ticket: https://edx-wiki.atlassian.net/browse/MCKIN-8249

DnD version bump

---

requirements/edx/custom.txt

This version bump will update the completion aggregator code to include some optimizations that reduce the number of database queries required to update aggregations.
AFAIK this code has not yet been tested on the solutions fork, so we need to make sure it can compute aggregations correctly on the solutions fork. See the PR linked below or other openedx-completion-aggregator PRs for testing instructions.
See https://github.com/open-craft/openedx-completion-aggregator/pull/21

[MCKIN-8259] Bump Completion aggregator version: optimization

---

common/djangoapps/enrollment/forms.py
common/djangoapps/enrollment/tests/test_views.py
common/djangoapps/enrollment/views.py

Also update the docstring of functions used by the endpoint. This is a follow-up PR to the https://github.com/edx-solutions/edx-platform/pull/1142 PR with fixes to the docstring.
**Reviewers**

[MCKIN-8184] Update the course enrollment list api endpoint docstring

---

requirements/edx/custom.txt

Pulls in fixes from https://github.com/open-craft/xblock-eoc-journal/pull/20.

Bump EOC Journal XBlock.

---

requirements/edx/base.txt

Include work to make completion atomic again.
https://github.com/edx/completion/pull/28
Reviewer:
Deadline: ASAP

Include completion change to make submit atomic.

---

requirements/edx/custom.txt

This is a version bump PR for a corresponding chat xblock PR https://github.com/open-craft/xblock-chat/pull/27

MCKIN-8273: updated chat xblock to 0.2.1

---

requirements/edx/custom.txt

Adding commit back which was overwritten in merging.
DnD commit: edx-solutions/xblock-drag-and-drop-v2@26bcdb0
Mcka ticket: https://edx-wiki.atlassian.net/browse/MCKIN-8249

DnD version bump 

---

openedx/core/lib/xblock_builtin/xblock_discussion_course/xblock_discussion_course.py

Exclude xblock_discussion_course block from completion.

---

requirements/edx/custom.txt

Tickets: MCKIN-8062, MCKIN-8059

Pb version bump

---

lms/djangoapps/courseware/testutils.py
lms/djangoapps/lti_provider/tests/test_views.py
requirements/edx/custom.txt

Bump version of api-integration and fix bug in module_render

[MCKIN-7755] [OC-4523] Incorporate completion api changes in api-integration v1 

---

requirements/edx/custom.txt

Bump version of eoj-journal to include fix from open-craft/xblock-eoc-journal#21

[MCKIN-8326] Bump version of eoc-journal

---

common/lib/xmodule/xmodule/tests/test_validation.py
requirements/edx/base.txt
requirements/edx/custom.txt

Bump version of xblocks and openedx-completion-aggregator to include fixes.
Update tests to remove dependency on removed code.

[MCKIN-8483] Bump version of xblocks and openedx-completion-aggregator

---

requirements/edx/custom.txt

Related to [this](https://github.com/edx-solutions/organizations-edx-platform-extensions/pull/34) PR.
@UmanShahzad

[MCKIN-8418] Bump version of organizations-edx-platform-extensions

---

requirements/edx/custom.txt

Releases changed for api integration and organization extensions repo.

Releases changed for api integration and organization extensions repo.

---

requirements/edx/custom.txt

MCKIN-8062 
Updated problem builder version to 2.10.5.

MCKIN-8062 Updated problem builder version to 2.10.5

---

common/djangoapps/django_comment_common/signals.py
lms/djangoapps/django_comment_client/base/views.py
requirements/edx/custom.txt

This PR is connected with [this](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/20).

[MCKIN-8418] Optimize UsersSocialMetrics.get API

---

requirements/edx/custom.txt

MCKIN-8582 Version bump for drag and drop

---

requirements/edx/custom.txt

MCKIN-8582 Version bump for dnd v2.

MCKIN-8582 Version bump for dnd v2

---

requirements/edx/custom.txt

Version bump to incorporate https://github.com/open-craft/openedx-completion-aggregator/pull/36
Reviewers:

Version bump aggregator to hotfix-1.5.4.1 tag

---

openedx/core/djangoapps/course_groups/cohorts.py
requirements/edx/custom.txt

@UmanShahzad, this PR is a part of `[MCKIN-8491]` PR-s.

[MCKIN-8491] Engagement score average reflective of Discussion activity by Cohort Group

---

common/lib/xmodule/xmodule/tests/test_validation.py
common/static/common/js/discussion/utils.js
common/test/utils.py
lms/djangoapps/courseware/testutils.py
lms/djangoapps/discussion/static/discussion/js/discussion_board_factory.js
lms/djangoapps/discussion_api/forms.py
lms/djangoapps/discussion_api/serializers.py
lms/djangoapps/discussion_api/tests/test_views.py
lms/djangoapps/discussion_api/urls.py
lms/djangoapps/discussion_api/views.py
lms/djangoapps/django_comment_client/base/tests.py
lms/djangoapps/instructor/views/api.py
lms/djangoapps/lti_provider/tests/test_views.py
lms/djangoapps/teams/tests/test_models.py
lms/lib/comment_client/thread.py
lms/templates/courseware/courseware-chromeless.html
lms/urls.py
openedx/core/djangoapps/course_groups/api.py
openedx/core/djangoapps/course_groups/cohorts.py
openedx/core/djangoapps/course_groups/serializers.py
openedx/core/djangoapps/course_groups/tests/test_api_views.py
openedx/core/djangoapps/course_groups/urls.py
openedx/core/djangoapps/course_groups/views.py
openedx/core/lib/api/view_utils.py
openedx/core/lib/xblock_builtin/xblock_discussion_course/xblock_discussion_course.py
requirements/edx/base.txt
requirements/edx/custom.txt

This PR merges development branch to integration

merge development to integration

---

common/static/common/js/discussion/utils.js

DiscussionsUtil Intermittent issue resolved

YONK-964 - DiscussionsUtil Intermittent issue resolved

---

requirements/edx/custom.txt

Version bump PR to bring in performance improvements to openedx-completion-aggregator migration.
**JIRA tickets**: Implements YONK-1175
**Sandbox URL**: N/A
N/A
**Reviewers**
**Settings**

YONK-1175: Version bump aggregator to 1.5.10

---

requirements/edx/custom.txt

This PR is a part of `[MCKIN-8511]` PR-s.

[MCKIN-8511] Optimize - Course cohort page - API

---

requirements/edx/custom.txt

[MCKIN-8530] Optimize Imports Participants API

---

requirements/edx/custom.txt

version bump for drag-and-drop-v2 MCKIN-8500.

Version bump for drag-and-drop-v2 MCKIN-8500

---

requirements/edx/custom.txt

This PR merges integration to development branch, we are not taking DnDv4 and Image Explorer v2 to development yet since they are still in testing.

merge integration to development branch

---

requirements/edx/custom.txt

This is a version bump for [this PR](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/25).

[MCKIN-8714] Fix and secure creating new entries for SocialEngagement

---

requirements/edx/custom.txt

This is a version bump for https://github.com/edx-solutions/api-integration/pull/162.

[MCKIN-8714] Bump api-integration

---

lms/lib/comment_client/user.py
lms/lib/comment_client/utils.py

This reverts commit df958390cb45f30edcc80d89f22c33d6dab988da.

Revert "Logs added to get status_code from forums (#1240)"

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#1253

Revert "[MCKIN-8325] Bump ooyala xblock for testing"

---

requirements/edx/custom.txt

Fixes an issue with the API making 1 query per user because of a missing select_related call.

[MCKIN-8890] Bump completion version.

---

requirements/edx/custom.txt

Version bump for edx-notifications

Version Bump for edx-notifications

---

requirements/edx/custom.txt

Cheery picked #1259 to get it to stage

MCKIN-8730 Optimize CourseMetricSocial API (#1259)

---

requirements/edx/custom.txt

[MCKIN-8780] Optimize CoursesUsersList.get

---

requirements/edx/custom.txt

This is a version bump for edx-solutions/api-integration#167.

Revert "[MCKIN-8730]" and "[MCKIN-8418]"

---

requirements/edx/custom.txt

This reverts MCKIN-8730 MCKIN-8714 MCKIN-8418.

[Revert "MCKIN-8730 MCKIN-8714 MCKIN-8418"] Bump version for testing

---

requirements/edx/custom.txt

This is actual version bump. The previous PR was merged to get it completed faster.

[Revert "MCKIN-8730 MCKIN-8714 MCKIN-8418"] Bump version

---

requirements/edx/custom.txt

This PR is updating the xblock versions for drag and drop v2, polls and problem builder.

update the xblock versions for drag and drop v2, polls and problem builder

---

requirements/edx/custom.txt

problem builder version bump to 2.11.3

YONK-1219 - Problem builder version bump to 2.11.3

---

requirements/edx/custom.txt

This PR is part of [MCKIN-8718].

[MCKIN-8718] Optimize Enroll existing Participants API

---

lms/djangoapps/courseware/module_render.py
lms/djangoapps/courseware/tests/factories.py
lms/djangoapps/courseware/tests/test_entrance_exam.py
lms/djangoapps/courseware/tests/test_module_render.py
lms/djangoapps/courseware/tests/test_views.py
lms/urls.py

Merging Integration into development

---

requirements/edx/custom.txt

This PR bumps api-integration version to v2.3.5

MCKIN-8585: bump api-integration version to v2.3.5

---

requirements/edx/custom.txt

This PR is a part of edx-solutions/api-integration#171.

[MCKIN-8891] Optimize CourseMetricsLeaders

---

requirements/edx/custom.txt

This Pr is to update the Ooyala version for resolving the Video issue on IE11 v11.0.9600.19180
and windows7.

Ooyala update

---

requirements/edx/custom.txt

Downgrade the Ooyala version for testing of Ooyala team.
This is a temporary change for debugging of Ooyala issues with Ooyala team

temporary: downgrade the ooyala version for testing of ooyala team

---

lms/lib/comment_client/user.py
lms/lib/comment_client/utils.py

Additional logs added to get the status code of response from forums. This is a temporary addition to load test on staging environment

YONK-1177 - Logs added to get status code from forums

---

requirements/edx/custom.txt

Replaces https://github.com/edx-solutions/edx-platform/pull/1296

Update problem-builder version to 2.11.4

---

requirements/edx/custom.txt

https://edx-wiki.atlassian.net/browse/MCKIN-8967
Ooyala Xblock version bump for https://github.com/edx-solutions/xblock-ooyala/pull/92

MCKIN-8967 - Version Bump

---

requirements/edx/custom.txt

This PR disables the features implemented by MCKIN-8502
1. Run the LMS, making sure it updates the python requirements.
2. Log into Apros with an user that has access to a course.
3. Make sure the progress is different from zero or browse the course to make it so.
4. Make sure the engagement score is different from zero or post a the discussion.
5. Check the average score in `/courses/<course/id>/cohort`
6. Enable cohorts and put the user in a cohort with other users.
7. Check again the scores at `/courses/<course/id>/cohort`, making sure nothing changed.
1. https://github.com/edx-solutions/api-integration/pull/175/ must be merged before this can be merged.

[MCKIN-8502] Revert

---

requirements/edx/custom.txt

See https://github.com/edx-solutions/api-integration/pull/174.

[MCKIN-8963] Bump api-integration.

---

requirements/edx/custom.txt

https://github.com/edx-solutions/api-integration/pull/179

[MCKIN-8977] Bump integration.

---

requirements/edx/custom.txt

version bump to xblock poll latest translations fix for https://github.com/open-craft/xblock-poll/commit/8a81d0527e5ec8e53a72461c23520dc5036c52ed.

version bump to xblock poll latest translations fix

---

requirements/edx/custom.txt

https://github.com/edx-solutions/api-integration/pull/178

[MCKIN-8978] Bump api-integration.

---

requirements/edx/custom.txt

[MCKIN-9040] Bump api-integration

---

requirements/edx/custom.txt

Reference PR: https://github.com/edx-solutions/xblock-ooyala/pull/93
Fixed translations, earlier no translations were working.

update ooyala version

---

lms/lib/comment_client/utils.py

[YONK-1253](https://openedx.atlassian.net/browse/YONK-1253)

Fix for discussion not loading in some courses

---

requirements/edx/custom.txt

Adds management command to fix fix invalid organization attributes.

[MCKIN-8823] Bump version of organizations-edx-platform-extensions

---

requirements/edx/custom.txt

Mcka Ticket:  https://edx-wiki.atlassian.net/browse/MCKIN-9083
To include v2.3.17

Api Integration version bump

---

openedx/core/djangoapps/course_groups/views.py

This PR is connected with MCKIN-8977 and MCKIN-9054 tickets.

[MCKIN-8977] Fix race condition during importing participants

---

requirements/edx/custom.txt

Mcka Ticket: MCKIN-8585 - Additional fix for course participant search
Releasing version: v2.3.18

MCKIN-8585 - Api integration version bump

---

requirements/edx/custom.txt

Related ticket: https://edx-wiki.atlassian.net/browse/MCKIN-7144

version bump scorm xblock to 2.0.12

---

requirements/edx/custom.txt

Updating DnD version so mcka-theme related changes could be verified on `integration`

DnD version updated to match development

---

lms/djangoapps/courseware/user_state_client.py

Implemented the try/catch block on saving user state as implemented in Hawthorn release [link](https://github.com/edx/edx-platform/blob/72fb572217fb17eb798632f4abdf88529deabbb0/lms/djangoapps/courseware/user_state_client.py#L276)
It will avoid raising XblockSaveError and KeyValueMultiSaveError on new relic and splunk
Upstream PR: https://github.com/edx/edx-platform/pull/14128

YONK-923 - XBlockSaveError handled by suppressing IntegrityErrors on saving user state

---

requirements/edx/custom.txt

This PR is a version bump for open-craft/problem-builder#222.

[MCKIN-8350] Incorporate recent changes in problem-builder v2 into problem-builder v3

---

requirements/edx/custom.txt

Releasing version [1.2.11](https://github.com/edx-solutions/discussion-edx-platform-extensions/releases/tag/v1.2.11)

Discussion extensions version bump

---

requirements/edx/custom.txt

This is a version bump for edx-solutions/api-integration#188.

[MCKIN-8911] Add `DELETE` method for users API

---

requirements/edx/custom.txt

Reference PR: https://github.com/open-craft/problem-builder/pull/220
MCKIN-9137 problem builder version bump for improved translations.

MCKIN-9137 problem builder version bump

---

requirements/edx/custom.txt

MCKIN-9179 - Optimized course participants search - slowness fixed.

MCKIN-9179 - Api integration version bump

---

requirements/edx/custom.txt

MCKIN-9177 - Ooyala version bump

MCKIN-9177 - Ooyala version bump

---

requirements/edx/custom.txt

Reference PR: https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/198

MCKIN-9180 Version bump Drag and Drop V2.

---

requirements/edx/custom.txt

This is a bump PR for MCKIN-9024.

[MCKIN-9024] Fix exporting stats for >= 1k users

---

requirements/edx/custom.txt

This PR bumps gradebook version to 1.1.13 which includes fix for MCKIN-9213.

MCKIN-9213: Proficiency score is not updating instantly

---

requirements/edx/custom.txt

MCKIN-9191 version bump to 2.0.13

---

requirements/edx/custom.txt

This is a version bump for data deletion PRs.

[BB-714] Bump mobileapps version

---

requirements/edx/custom.txt

MCIN-9153 MCKIN-9231 version bump
version bump for scormxblock

MCIN-9153 MCKIN-9231 version bump for scormxblock

---

requirements/edx/custom.txt

MCKIN-9202: version bump openedx-completion-aggregator==1.5.19

---

requirements/edx/custom.txt

@xitij2000: Here's a version bump PR for MCKIN-9071, which also includes the version bump for YONK-1302.

MCKIN-9071 / YONK-1302: Version bumps

---

requirements/edx/base.txt
requirements/edx/custom.txt

Revert 1351 MCKIN-7757/bump completion

---

requirements/edx/custom.txt

This is a version bump for edx-solutions/discussion-edx-platform-extensions#34.

[MCKIN-9225] Bump `discussion-edx-platform-extensions` version

---

requirements/edx/custom.txt

Version bump for scorm xblock.

Version bump: scorm xblock (2.0.16)

---

openedx/features/course_experience/tests/views/test_course_home.py

Fixed flaky unit test 'test_queries'

YONK-940:  Unit test 'test_queries' in TestCourseHomePage fixed

---

requirements/edx/custom.txt

This is a version bump for group-project-v2. Changes were tested [here](https://github.com/mckinseyacademy/django-upload-validator/pull/10).
**Dependencies:**

YONK-1306: Version bump for group project Xblocks

---

requirements/edx/custom.txt

Version bump for https://github.com/edx-solutions/api-integration/pull/200
This includes a fix for deleting a learner that does not have a discussion user yet.

[MCKIN-8918] Fix deleting user without discussion posts

---

requirements/edx/custom.txt

This Pr refers to version bumo for Scorm Xblock

MCKIN9497 xblock scorm version bump

---

requirements/edx/custom.txt

Version bump of api-integration from 2.5.4 to 2.5.5.

MCKIN-9798- Version Bump to 2.5.5 

---

lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tasks_helper/utils.py

Restores a bit of code that was missed during rebase.

[MCKIN-9476] Add missing report name that was lost during rebase

---

requirements/edx/custom.txt

Reference PR: https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/200

MCKIN-9197 Version bump Drag and Drop V2.

---

requirements/edx/custom.txt

Creating this on behalf of @nasirhjafri
bump gradebook-edx-platform-extensions version to 1.1.14
bump discussion-edx-platform-extensions version to 1.2.13
bump api-integration verion to 2.5.8
connects [edx-solutions/discussion-edx-platform-extensions#35](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/35)
connects [edx-solutions/api-integration#206](https://github.com/edx-solutions/api-integration/pull/206)
connects [edx-solutions/gradebook-edx-platform-extensions#31](https://github.com/edx-solutions/gradebook-edx-platform-extensions/pull/31)

MCKIN-9976 -- Bumped versions

---

requirements/edx/custom.txt

This is a version bump PR for edx-solutions/projects-edx-platform-extensions#19.

[MCKIN-8917] Bump `projects-edx-platform-extensions`

---

requirements/edx/custom.txt

This is a version bump PR for open-craft/xblock-poll#52.

[MCKIN-9952] Bump xblock-poll version

---

requirements/edx/custom.txt

This is a version bump for edx-solutions/api-integration#204.

[MCKIN-9402] Implement bulk deletion

---

requirements/edx/custom.txt

MCKIN-9802 version bump scorm xblock 2.0.22

---

requirements/edx/custom.txt

Reference Relase Tag: https://github.com/open-craft/problem-builder/releases/tag/v3.3.1
Reference PR: https://github.com/open-craft/problem-builder/pull/226

MCKIN-10126 problem builder version bump

---

requirements/edx/custom.txt

[MCKIN-9532](https://edx-wiki.atlassian.net/browse/MCKIN-9532) version bump for scorm xblock v2.0.24.

 MCKIN-9532 version bump for scorm xblock v2.0.24

---

requirements/edx/custom.txt

Bumps version of poll xblock to include this fix: https://github.com/open-craft/xblock-poll/pull/53

[MCKIN-9618] Bump version of xblock-poll

---

requirements/edx/custom.txt

Version bump to include xblock-image-explorer PR#55

[MCKIN-9104] update version to be used for image explorer

---

lms/djangoapps/courseware/management/commands/delete_duplicate_record.py

Duplicate record exists in the production database for the courseModuleCompletion table
That record needs to be deleted to fix the issue
the management command must be run with these three command line arguments
python manage.py lms delete_duplicate_record --settings=devstack "466/TAWASUL_ARABIC_V4/JAN2019" "i4x://466/TAWASUL_ARABIC_V4/static_tab/0f3f7dc298584702bcc687294d7269a2" "bushra"
"466/TAWASUL_ARABIC_V4/JAN2019" is course_id
"i4x://466/TAWASUL_ARABIC_V4/static_tab/0f3f7dc298584702bcc687294d7269a2" is content_id
"bushra" is username

Delete duplicate record in course module completion

---

openedx/core/djangoapps/user_api/accounts/api.py
requirements/edx/custom.txt

This PR modifies the API endpoints for user deletion to report failures.
1. Checkout this branch and restart the LMS making sure Python prereqs are reinstalled.
2. Stop the forum service to cause a failure during deletion.
3. Make a request to delete an existing user, e.g.:
```bash
$ curl -v -X DELETE -H "X-Edx-Api-Key: edx_api_key" localhost:8000/api/server/users?ids=<existing_user_id>
```
4. Make sure the response has the user email as key and the `HTTPConnectionPool` exception as error.
5. Check the LMS that the user still exists.
**Reviewers**

[MCKIN-10190] Report deletion errors

---

lms/djangoapps/courseware/tests/test_user_state_client.py
lms/djangoapps/courseware/user_state_client.py
lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/views/api.py
lms/djangoapps/instructor_analytics/basic.py
lms/djangoapps/instructor_task/api.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tests/test_api.py
lms/djangoapps/instructor_task/tests/test_base.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py
lms/envs/common.py
openedx/core/djangoapps/profile_images/tasks.py
openedx/core/djangoapps/profile_images/tests/test_tasks.py
openedx/core/djangoapps/user_api/accounts/api.py
openedx/core/djangoapps/user_api/accounts/tests/test_api.py
requirements/edx/base.txt
requirements/edx/github.txt

Cherry picks some of the data deletion work and all the problem response reporting improvements.

Cherry pick reporting imrovements and deletion code to release-candidate

---

requirements/edx/custom.txt

Version bump for https://github.com/edx-solutions/api-integration/pull/212.

MCKIN-10180: Api integration version bump

---

requirements/edx/custom.txt

Image explorer is updated to 1.1.3

BB-1025 Version bump for xblock-image-explorer

---

requirements/edx/custom.txt

This is a version bump PR for edx-solutions/projects-edx-platform-extensions#20.

[MCKIN-10357] Bump `projects-edx-platform-extensions`

---

requirements/edx/custom.txt

corresponding xblock PR https://github.com/open-craft/xblock-group-project-v2/pull/128

MCKIN-10341: version bump for xblock-group-project-v2 to 0.4.14

---

requirements/edx/custom.txt

Reference PR: https://github.com/open-craft/problem-builder/pull/230

MCKIN-10460: version bump of problem builder to 3.3.2

---

requirements/edx/custom.txt

Bumps versions of xblock-poll and xblock-ooyala to include fixes for completion.

[MCKIN-10391] Bump version of ooyala and poll xblocks to include completion fixes

---

requirements/edx/custom.txt

Profile image gets broken whenever we edit the username
The issue is fixed by renaming the uploaded image files for all four sizes according to the new username.

vVersion bump for api integration

---

requirements/edx/custom.txt

Added feedback header translations

MCKIN-9996 feedback header translations

---

lms/static/scorm/ssla/config_override.js

Related Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-10531
This PR adds branding support in the button displayed within the SSLA player within the iframe in scormxblock when popup fails to launch.

MCKIN-10531 Add branding support to SSLA button

---

requirements/edx/custom.txt

Version bump to fix bug affecting dragging on mobile. [PR](https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/205)

(MCKIN-10393) Version bump for drag and drop v2 xblock.

---

requirements/edx/custom.txt

Related to https://github.com/edx-solutions/projects-edx-platform-extensions/pull/21

Bump projects-edx-platform-extensions to fix S3 file deletion

---

requirements/edx/custom.txt

Ooyala: https://edx-wiki.atlassian.net/browse/MCKIN-10692
Scorm: tech-debt task (no ticket)

Ooyala and Scorm version bumps

---

requirements/edx/custom.txt

Version without progress backport cleanup work
api-integration: v2.7.3
course-extensions: v1.1.1

Version without progress backport cleanup work

---

requirements/edx/custom.txt

v2.7.5 contains: MCKIN-10458 & MCKIN-9977

api-integration version bump

---

requirements/edx/custom.txt

MCKIN-10354 updated scorm xblock version.

MCKIN-10354 updated scorm xblock version

---

requirements/edx/custom.txt

MCKIN-10546-version-bump

---

requirements/edx/custom.txt

Ooyala temp branch contains two fixes: 
1. Chrome fullscreen fix 
2. Default player width to 100%

MCKIN-9131 - Ooyala temp branch for Chrome fix

---

requirements/edx/custom.txt

This bump is related to edx-solutions/xblock-image-explorer#58.

[MCKIN-10542] Bump `xblock-image-explorer` version

---

requirements/edx/custom.txt

Related Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-10776
Related PR: https://github.com/mckinseyacademy/xblock-scorm/pull/40

MCKIN-10776 Version bump scorm xblock 2.0.28

---

requirements/edx/custom.txt

version-bump of api-integration

MCKIN-10858-version-bump

---

requirements/edx/custom.txt

We have created a test repo named wjia-temp and make it private. This PR is to test the private repo working on CircleCI and servers.

private temporary repo test on circleci

---

requirements/edx/custom.txt

I am reverting back the test PR to the.Reverts edx-solutions/edx-platform#1479

Revert "private temporary repo test on circleci"

---

requirements/edx/custom.txt

This is a version bump PR for edx-solutions/xblock-drag-and-drop-v2#210.

[MCKIN-10516] Bump `xblock-drag-and-drop-v2` to a temporary version

---

requirements/edx/custom.txt

Temp api-integration

---

requirements/edx/custom.txt

MCKIN-10868 - api-integration version bump

---

requirements/edx/custom.txt

This PR bumps api-integration version to v3.0.0

MCKIN-9499 : bump api-integration version to v3.0.0

---

requirements/edx/custom.txt

MCKIN-11012 - Ooyala Version bump

---

requirements/edx/custom.txt

Remove temporary private repo from custom.txt file and adding it to the mckinsey-internal repo.

Remove temporary private repo from custom.txt

---

requirements/edx/custom.txt

MCKIN-11023 - Ooyala version bump

---

requirements/edx/custom.txt

MCKIN-11125
Version bump scorm xblock.

MCKIN-11125 Scorm xblock version bump 2.0.31

---

requirements/edx/custom.txt

Version bumps of xblocks to include Polish translations.

[MCKIN-11140] Version bumps for integrating polish translations

---

lms/djangoapps/discussion/static/discussion/templates/discussion-home.underscore

Update Discussion home layout
- Keep intact for old UI
- but update for UI Refresh

Umar/mckin 10764 - Keep Discussion home page same for old UI but update for UI Refresh

---

requirements/edx/custom.txt

Changes:
- MCKIN-11023 - Ooyala version bump (#1499)

Updating master with release-candidate

---

common/static/common/js/discussion/views/discussion_content_view.js
common/static/common/js/discussion/views/discussion_thread_list_view.js
common/static/common/js/discussion/views/discussion_thread_view.js
common/static/common/js/discussion/views/thread_response_view.js
lms/djangoapps/django_comment_client/utils.py
lms/lib/comment_client/thread.py
lms/lib/comment_client/user.py

In this PR I have displayed the 
> **First name + “ “ + First initial of Last Name**
in the place of the username in the discussion module.

MCKIN-10967 Update username in discussion.

---

requirements/edx/custom.txt

Bump `api-integration` version to v3.1.5

MCKIN-11198: Bump api-integration version to v3.1.5

---

requirements/edx/custom.txt

MCKIN-11136-version-bump

---

requirements/edx/custom.txt

https://edx-wiki.atlassian.net/browse/MCKIN-11232
Oyala version bump
Japanese translation fix

MCKIN-11232 Ooyala version bump v2.1.3

---

requirements/edx/custom.txt

This simply updates the version of xblock-drag-and-drop-v2 to the latest.

Update version of xblock-drag-and-drop-v2

---

requirements/edx/custom.txt

Add new versions for eoc-journal and virtualreality xblocks.

Add version bump for eoc-journal and virtualreality.

---

requirements/edx/custom.txt

Reverts https://github.com/edx-solutions/edx-platform/pull/1526 which was accidentally merged to master.

Revert #1526

---

lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js

Removed sidebar height class for new UI

MCKIN-10846 removed sidebar height class

---

cms/djangoapps/contentstore/views/course.py

Fixed iOS- Unable to receive notification of announcement when sent in the Arabic language.

MCKIN-7543 iOS- Unable to receive notification of announcement in the Arabic

---

requirements/edx/custom.txt

- api-integratoin version bump
- Removed unneeded bcove player from requirements

MCKIN-11408 - api-integraton bump

---

requirements/edx/custom.txt

MCKIN-11426 - api-integration version bump

---

requirements/edx/custom.txt

MCKIN-11369 - api-integration version bump

---

requirements/edx/custom.txt

MCKIN-11571 Problem builder version bump v3.3.10

MCKIN-11571 Problem builder version bump v3.3.10

---

requirements/edx/custom.txt

Fixed pop up appearing empty tips in the second attempt of MRQ.

MCKIN-11065

---

lms/static/js/i18n/ja-jp/djangojs.js

Add static compiled file for Japanese translation.

MCKIN-11589 Ja fix

---

requirements/edx/custom.txt

MCKIN-11589 Poll version bump v1.8.9

---

requirements/edx/custom.txt

MCKIN-11606 - api-integration version bump

---

requirements/edx/custom.txt

MCKIN-12100 - api-integration version bump

---

lms/static/coffee/src/customwmd.coffee

MCKIN-12135-MCKIN-12137 Added text for discussion post add/edit labels

---

requirements/edx/custom.txt

MCKIN-12624 - api-integration release

---

requirements/edx/custom.txt

MCKIN-12605 - api-integration version bump

---

requirements/edx/custom.txt

version bump for problem builder
Release 3.3.12

MCKIN-12116 version bump for problem builder

---

requirements/edx/custom.txt

This version bump will bring accessibility changes in problem builder

MCKIN-12122: bump problem builder version to v3.3.13.

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#1574
Reverting to test https://openedx.atlassian.net/browse/YONK-1518

Revert "MCKIN-12183 Bumped xblock-image-explorer version to 1.1.6"

---

requirements/edx/custom.txt

MCKIN-12647 - api-integration version bump

---

requirements/edx/custom.txt

bump xblock-group-project-v2 version to 0.6.0

MCKIN-12639: bump xblock-group-project-v2 version to 0.6.0

---

requirements/edx/custom.txt

Version bump organizations-extensions to v1.2.8

---

requirements/edx/custom.txt

MCKIN-12179 IE version bump

---

requirements/edx/custom.txt

Version bump for problem builder

MCKIN-12194 Version bump for problem builder

---

common/lib/capa/capa/safe_exec/tests/test_lazymod.py

YONK-1536 Fixing failed unit tests on CircleCI

YONK-1536 fixed failed test

---

requirements/edx/custom.txt

bump xblock image explorer version to v1.1.9

MCKIN-12180: bump xblock image explorer version to v1.1.9

---

requirements/edx/custom.txt

bump organizations-edx-platform-extensions version to 1.3.0

MCKIN-12682: bump organizations-edx-platform-extensions version to 1.3.0

---

common/lib/capa/capa/safe_exec/tests/test_lazymod.py
requirements/edx/custom.txt

MCKIN-12253 problem builder version bump

---

requirements/edx/custom.txt

MCKIN-12700 - api-integration version bump

---

common/static/common/templates/discussion/thread-type.underscore

MCKIN-12235 Updated discussion help text
Added on request of @murad-hubib 
https://github.com/mckinseyacademy/mcka-theme/pull/239

MCKIN-12235 Updated discussion help text

---

requirements/edx/custom.txt

MCKIN-12152 Bumped problem builder version to 3.4.2

MCKIN-12152 Bumped problem builder version to 3.4.2

---

requirements/edx/custom.txt

MCKIN-12728 - IE version bump

---

requirements/edx/custom.txt

MCKIN-12729 - api-integration version bump

---

requirements/edx/custom.txt

Cherry picked to exclude Accessibility fixes

MCKIN-12728 IE release version

---

requirements/edx/custom.txt

MCKIN-12641 - projects-extensions version bump

---

requirements/edx/custom.txt

YONK-1547 - api-integration version bump

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#1614

Reverted IE version to 1.1.10

---

requirements/edx/custom.txt

Releasing `v3.1.24` and `v1.1.11`

MCKIN-12762 - api-integration and image-explorer version bumps

---

requirements/edx/custom.txt

MCKIN-12693 xblock poll bumped to 1.9.2

---

requirements/edx/custom.txt

MCKIN-12706 - Groupwork xblock version bump

---

requirements/edx/custom.txt

Fix the number of course count on companies page

MCKIN-12757 versoin bump to 1.3.1

---

requirements/edx/custom.txt

YONK-1547 - api-integration version bump (#1618)

---

common/lib/xmodule/xmodule/modulestore/tests/factories.py

YONK-1459 : cherry pick commit to apply custom changes in order to fix a failed unit test in api-integration

YONK-1459 : Fixed broken unit test from api-integration

---

requirements/edx/custom.txt

MCKIN-12786-12287-12227 v_bump for poll and problem builder

---

requirements/edx/custom.txt

MCKIN-12823 - api-integration version bump

---

requirements/edx/custom.txt

[2020-01-28] Release 1.41.0

---

common/static/common/templates/discussion/new-post.underscore
common/static/common/templates/discussion/thread-edit.underscore
common/static/common/templates/discussion/topic.underscore

Fixed dual text for screen readers

MCKIN-12235 Discussion removed dual ARIA

---

common/static/common/templates/discussion/inline-discussion.underscore
common/static/common/templates/discussion/new-post.underscore

Inline discussion header tabindex added

MCKIN-12809 making inline-discussion accessible

---

requirements/edx/custom.txt

MCKIN-12921 - api-integration version bump

---

requirements/edx/custom.txt

Tagging XBlock Ooyala

---

requirements/edx/custom.txt

MCKIN-12927 IE version bump

---

requirements/edx/custom.txt

MCKIN-13055 - Ooyala version bump

---

common/static/common/js/discussion/views/discussion_inline_view.js
lms/djangoapps/discussion/static/discussion/js/discussion_router.js
lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html

discussion focus navigation fixed

MCKIN-12809 discussion focus navigation fixed

---

requirements/edx/custom.txt

GW version bump

---

requirements/edx/custom.txt

MCKIN-13073 IE version bump

---

requirements/edx/custom.txt

MCKIN-12920 Problem builder Version bump

---

requirements/edx/custom.txt

MCKIN-13215 - api-integration version bump

---

requirements/edx/custom.txt

MCKIN-13194 IE version bump

---

requirements/edx/custom.txt

MCKIN-13279 IE VB

---

requirements/edx/custom.txt

MCKIN-13279 IE version bump

---

requirements/edx/custom.txt

MCKIN-13525 - api-integration version bump

---

openedx/core/djangoapps/contentserver/middleware.py

Bytes conversion of encryption key

MCKIN-13351 - Support for locked assets

---

requirements/edx/custom.txt

MCKIN-13352 - api-integration version bump

---

lms/djangoapps/lti_provider/views.py

Log any errors in the LTI launch flow to splunk.

MCKIN-13610 Add logs to LTI launch erros

---

requirements/edx/custom.txt

MCKIN-12757 version bump organizations-edx-platform-extensions

---

requirements/edx/custom.txt

MCKIN-12722 - api-integration version bump

---

requirements/edx/custom.txt

MCKIN-13560 releasing version api-integration

---

requirements/edx/custom.txt

 MCKIN-14037 - api-integration version bump

---

common/lib/xmodule/xmodule/assets/vertical/public/js/vertical_student_view.js
common/lib/xmodule/xmodule/vertical_block.py
common/lib/xmodule/xmodule/x_module.py
openedx/core/lib/xblock_utils/__init__.py

updated custom changes and used add_webpack_to_fragment introduced in ironwood

YONK-1601 - Studio edit page issue

---

requirements/edx/custom.txt

MCKIN-15673 Problem builder version bump

---

cms/static/js/factories/edit_tabs.js

Reference PR: https://github.com/edx/edx-platform/pull/23746/

[YONK-1601] Load XBlockToXModuleShim for Studio Tabs page.

---

requirements/edx/custom.txt

MCKIN-15673 VB PB

---

requirements/edx/custom.txt

MCKIN-14231 releaseing version api-integration

---

requirements/edx/custom.txt

Check related PR: https://github.com/open-craft/openedx-completion-aggregator/pull/69

Bump openedx-completion-aggregator

---

requirements/edx/custom.txt

Bumping group-project-v2 to fix issues.
Related to https://github.com/open-craft/xblock-group-project-v2/pull/137
**JIRA tickets**: MCKIN-14281
**Testing instructions**: Check related ticket
**Reviewers**

Bump group-project-v2 to a specific commit

---

requirements/edx/custom.txt

MCKIN-16409 version bump D&D

---

lms/djangoapps/branding/tests/test_page.py
lms/djangoapps/courseware/tests/test_views.py
lms/djangoapps/shoppingcart/tests/test_reports.py

Fixed flaky tests. Ref: https://github.com/edx/edx-platform/pull/23848

YONK- 1569 - Fixed skipped unit tests

---

requirements/edx/custom.txt

MCKIN-17533 VB of problem builder

---

requirements/edx/custom.txt

MCKIN-16081, MCKIN-17682 - Ooyala xblock version bump

---

requirements/edx/custom.txt

MCKIN-18058 - projects extension version bump

---

requirements/edx/custom.txt

MCKIN-18291 Poll version bump

---

requirements/edx/custom.txt

MCKIN-18603 VR VB

---

requirements/edx/custom.txt

MCKIN-16642 - Ooyala xblock version bump

---

requirements/edx/custom.txt

MCKIN-19583 - xblock-ooyala version bump

---

common/static/common/js/discussion/views/discussion_thread_list_view.js
common/static/common/js/spec/discussion/view/discussion_thread_list_view_spec.js
common/test/acceptance/tests/discussion/test_discussion.py

This reverts commit 9704146e40883a472500b2891a4da25c838d2d4e.

Revert "EDUCATOR-2224 Discussion Topic with no posts have message."

---

requirements/edx/custom.txt

Version bump for https://github.com/edx-solutions/projects-edx-platform-extensions/pull/35

Bump projects-edx-platform-extensions

---

requirements/edx/custom.txt

tickets: https://edx-wiki.atlassian.net/browse/MCKIN-20588, https://edx-wiki.atlassian.net/browse/MCKIN-20615

[MCKIN-20588/MCKIN-20615] Bumped version for organization and api-integration extensions apps

---

requirements/edx/custom.txt

MCKIN-21004 - Ooyala xblock version bump

---

requirements/edx/custom.txt

Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-20813
Relevant PR: https://github.com/edx-solutions/gradebook-edx-platform-extensions/pull/40

MCKIN-20261 Review version bump for gradebook

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#1826

Revert "MCKIN-21004: bump xblock ooyala version to v4.0.4"

---

requirements/edx/custom.txt

MCKIN-21507 updated version to 2.2.4 and fixed failing tests

---

lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js
openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion.py

add support for inline discussions translations

MCKIN-19584: add support for inline discussions translations

---

requirements/edx/custom.txt

MCKIN-21004 - VB Ooyala xblock

---

openedx/core/djangoapps/auth_exchange/tests/test_views.py
openedx/core/djangoapps/auth_exchange/views.py

This reverts https://github.com/edx-solutions/edx-platform/commit/e2721757565ef754286fea6b62d8e2532f4d92e1

MCKIN-21743 Revert e272175756

---

common/djangoapps/util/request_rate_limiter.py

During ironwood rebase, a custom change got missed. Here is the PR for that custom change https://github.com/edx-solutions/edx-platform/pull/1452

added rate limit flag, missed during ironwood rebase 

---

requirements/edx/custom.txt

Version update for Chat, PB, POLL

MCKIN-16959 Version update for Chat, PB, POLL

---

requirements/edx/custom.txt

Relevant PR: https://github.com/edx-solutions/projects-edx-platform-extensions/pull/39

[MCKIN-19691] Bumped version for projects-edx-platform-extensions

---

cms/static/js/views/video/transcripts/file_uploader.js
cms/templates/edit-tabs.html
cms/templates/manage_users_lib.html
lms/static/js/verify_student/views/pay_and_verify_view.js
lms/static/js/verify_student/views/reverify_view.js
lms/static/js/views/image_field.js
lms/static/js/views/notification.js
lms/templates/split_test_author_view.html

[YONK-1753](https://openedx.atlassian.net/browse/YONK-1753)
I have applied the security patch of **Juniper_sustaining_security_fixes.patch** on the Ironwood release.

[YONK-1753] Apply the security Patch.

---

requirements/edx/custom.txt

https://edx-wiki.atlassian.net/projects/MCKIN/versions/17141/tab/release-report-all-issues
https://edx-wiki.atlassian.net/projects/MCKIN/versions/17142/tab/release-report-all-issues

Releasing v1.49.2 v1.50.0 issues

---

requirements/edx/custom.txt

MCKIN-22441 PB version update

---

requirements/edx/custom.txt

Relevant PR: https://github.com/edx-solutions/projects-edx-platform-extensions/pull/40

[MCKIN-17690] Review version bump for projects-edx-platform-extensions

---

requirements/edx/custom.txt

bump organizations-edx-platform-extensions version to v2.0.5

MCKIN-21885: bump organizations-edx-platform-extensions version to v2.0.5

---

requirements/edx/custom.txt

MCKIN-19840 EOC (End of course Journal) - None of the strings are translated in any language

---

requirements/edx/custom.txt

Releasing v2.0.7 of projects-edx-platform-extensions

MCKIN-21998 fix deleted groups appearance on private discussion

---

requirements/edx/custom.txt

Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-22152
Relevant PR: https://github.com/edx-solutions/projects-edx-platform-extensions/pull/42

[MCKIN-22152] Bumped up version for projects-edx-platform-extensions

---

requirements/edx/custom.txt

Ref: https://github.com/edx-solutions/projects-edx-platform-extensions/pull/44

MCKIN-22505 projects extension VB

---

requirements/edx/custom.txt

MCKIN-23062 purge cohorts of deleted groups

---

cms/static/js/views/components/add_xblock.js
cms/static/js/views/components/add_xblock_button.js
cms/static/js/views/course_rerun.js
cms/static/js/views/instructor_info.js
cms/static/js/views/list_item_editor.js
cms/static/js/views/metadata.js
cms/static/js/views/video/translations_editor.js
cms/static/js/views/xblock_validation.js

Upstream PR: https://github.com/edx/edx-platform/pull/24762

YONK-1761 - Sustaining security fixes

---

requirements/edx/custom.txt

This is temporary for testing until https://github.com/open-craft/xblock-group-project-v2/pull/140 is merged

Updated the GW fork

---

requirements/edx/custom.txt

MCKIN-23037 - Ooyala xblock version bump

---

requirements/edx/custom.txt

Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-22507
Relevant PR: https://github.com/open-craft/xblock-group-project-v2/pull/140

[MCKIN-22507] Review version bump for xblock-group-project-v2

---

common/static/common/templates/discussion/inline-discussion.underscore
lms/templates/discussion/_discussion_inline.html

This is replacement PR for https://github.com/edx-solutions/edx-platform/pull/1888, because ci tests were not running on that PR. Code changes are made by @murad-hubib

MCKIN-21918 Inline discussion japanese buttons

---

cms/templates/js/course_info_handouts.underscore
cms/templates/js/grading-editor.underscore
cms/templates/js/metadata-string-entry.underscore
cms/templates/js/section-name-edit.underscore
cms/templates/js/signatory-actions.underscore
cms/templates/js/team-member.underscore
cms/templates/js/video/transcripts/messages/transcripts-import.underscore
cms/templates/js/video/transcripts/messages/transcripts-not-found.underscore
cms/templates/js/video/transcripts/messages/transcripts-replace.underscore
cms/templates/js/video/transcripts/messages/transcripts-uploaded.underscore
cms/templates/js/video/transcripts/messages/transcripts-use-existing.underscore
cms/templates/js/xblock-outline.underscore

Upstream link: https://github.com/edx/edx-platform/commit/c635372e0aead476bb9c88831c05c5c71686fb6a

YONK-1776 - Security patch

---

cms/static/js/views/baseview.js
cms/static/js/views/license.js
cms/static/js/views/list.js
cms/static/js/views/manage_users_and_roles.js
cms/static/js/views/uploads.js
cms/static/js/views/video/transcripts/message_manager.js
cms/static/js/views/xblock_string_field_editor.js

https://github.com/edx/edx-platform/commit/234050b1995d4d718040eeaba143996580934e20

[YONK-1777] Sustaining security fixes.

---

requirements/edx/custom.txt

MCKIN-24492 version bump api-integration

---

cms/static/js/views/container.js
cms/static/js/views/experiment_group_edit.js
cms/static/js/views/learning_info.js
cms/static/js/views/list_item.js
lms/templates/ccx/coach_dashboard.html
lms/templates/components/card/card.underscore
lms/templates/edxnotes/note-item.underscore
lms/templates/edxnotes/tab-item.underscore
lms/templates/fields/field_image.underscore
lms/templates/instructor/instructor_dashboard_2/enrollment-code-lookup-links.underscore
lms/templates/learner_dashboard/program_card.underscore
lms/templates/video.html

Upstream PR: https://github.com/edx/edx-platform/pull/24927

[YONK-1779] Sustaining security fixes 4 & 5.

---

requirements/edx/custom.txt

MCKIN-24501 version bump api-integration

---

requirements/edx/custom.txt

 MCKIN-24559 - Organizations extensions VB

---

openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py

https://edx-wiki.atlassian.net/browse/MCKIN-21919

MCKIN-21919 Inline Discussion - The following strings are not translated in Korean Language

---

requirements/edx/custom.txt

MCKIN-24565 - Organizations extensions VB

---

requirements/edx/custom.txt

MCKIN-24630 version update

---

requirements/edx/custom.txt

MCKIN-24508 D&D version bump

---

requirements/edx/custom.txt

Releasing DND against mckinsey-master

MCKIN-9834 DND version bump

---

requirements/edx/custom.txt

MCKIN-24508 PB VB

---

requirements/edx/custom.txt

MCKIN-25170 PB VB

---

requirements/edx/custom.txt

MCKIN-24381-23104 VB for eoc and VR

---

cms/templates/js/group-configuration-details.underscore
cms/templates/js/maintenance/force-published-course-response.underscore
cms/templates/js/mock/mock-xmodule-editor.underscore
cms/templates/js/publish-editor.underscore
cms/templates/js/unit-outline.underscore
cms/templates/js/video/transcripts/file-upload.underscore
cms/templates/js/xblock-validation-messages.underscore

Upstream PR: https://github.com/edx/edx-platform/pull/25226

[YONK-1791] sustaining security fixes 6

---

requirements/edx/custom.txt

Problem Builder https://github.com/open-craft/problem-builder/pull/313

MCKIN-26123 Version Update for Problem Builder

---

requirements/edx/custom.txt

MCKIN-26468 - projects extensions VB

---

requirements/edx/custom.txt

MCKIN-24383 & 24384 VB for GP v2 and Adventure

---

lms/djangoapps/courseware/tests/test_video_mongo.py
lms/djangoapps/courseware/tests/test_views.py

This PR fixes unit tests for lms courseware app

MCKIN-26672: fix unit tests for lms courseware app

---

requirements/edx/custom.txt

MCKIN-24382 Scorm VB

---

requirements/edx/custom.txt

MCKIN-24786 version bump

---

requirements/edx/custom.txt

Update xblock-eoc-journal to include this PR: https://github.com/open-craft/xblock-eoc-journal/pull/38

[MCKIN-27010] Update xblock-eoc-journal to fix import issue

---

common/djangoapps/course_modes/tests/test_admin.py
common/djangoapps/pipeline_mako/tests/test_render.py
openedx/features/discounts/tests/test_applicability.py
scripts/circle-ci-tests.sh

This PR fixes all the remaining unit test cases for platform.

MCKIN-27321: fix unit tests

---

cms/djangoapps/contentstore/views/component.py
cms/templates/container.html

Cherry-pick of https://github.com/edx/edx-platform/pull/25537

[MCKIN-26432] Add back unit to Studio breadcrumbs UI

---

requirements/edx/custom.txt

Update group project block to latest release that support python 3 and juniper

[MCKIN-24503] Update group project to work on python 3

---

requirements/edx/custom.txt

Releasing 0.10.1 of Group work v2

MCKIN-24383 GW v2 version bump

---

requirements/edx/custom.txt

MCKIN-26850 EOC-journal version bump

---

requirements/edx/custom.txt

MCKIN-27771 group project version bump

---

requirements/edx/custom.txt

MCKIN-27923 VB FOR GP

---

requirements/edx/custom.txt

Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-27180
PR created replicating https://github.com/edx-solutions/edx-platform/pull/2007 since developer does not has access to edx-solutions repo yet.

MCKIN-27180 Version bump api-integration

---

openedx/core/djangoapps/user_api/completion/tasks.py

This PR fixes the following error:
```
[2020-11-17 20:04:20,049: INFO/Worker-1] Started progress migration from "***" to "***" for "secondary/course2/2020" course
[2020-11-17 20:04:20,085: WARNING/Worker-1] /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1145: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
self, resource_name
[2020-11-17 20:04:20,136: ERROR/MainProcess] Task openedx.core.djangoapps.user_api.completion.tasks.migrate_progress[5428cbbf-b450-46e2-b49a-733c2a8c2468] raised unexpected: TransactionManagementError('select_for_update cannot be used outside of a transaction.',)
Traceback (most recent call last):
File …
```

[BB-2959] [MCKIN-27241]: Wrap _migrate_progress in transaction

---

requirements/edx/custom.txt

MCKIN-27921 GP v2 version bump

---

requirements/edx/custom.txt

MCKIN-28123 Group Project version bump

---

requirements/edx/custom.txt

MCKIN-28239 Version bump for GP v2

---

requirements/edx/custom.txt

MCKIN-28307 - Ooyala & Adventure version bumps

---

requirements/edx/custom.txt

MCKIN-28399 VB group_project v2

---

requirements/edx/custom.txt

MCKIN-28300 VB GP v2

---

requirements/edx/custom.txt

MCKIN-28399 VB group project v2

---

requirements/edx/custom.txt

MCKIN-28554 VB GP v2

---

requirements/edx/custom.txt

MCKIN-28611 - PB VB

---

requirements/edx/custom.txt

MCKIN-28448 - GW v2 VB

---

requirements/edx/custom.txt

 MCKIN-28362 - GW v2 VB

---

common/static/common/templates/discussion/templates.underscore

Implemented Option 1 of https://edx-wiki.atlassian.net/browse/MCKIN-28820?focusedCommentId=119933

MCKIN-28820 Main Discussions - The group work discussion link is throwing a 404 error (for the user who is not enrolled in any group)

---

lms/djangoapps/instructor_task/models.py

Writing rows of list to csv file batch wise and deleting those rows from list simultaneously.

MCKIN-24991 memory optimization in storing rows to csv

---

lms/djangoapps/commerce/api/v1/tests/test_views.py

MCKIN-29164 Fix edx-platform failing tests (#2058)

---

requirements/edx/custom.txt

MCKIN-28363 - SCORM VB

---

requirements/edx/custom.txt

MCKIN-29159 Problem builder version bump

---

requirements/edx/custom.txt

Version bump xblock-group-project-v2 to 0.12.13

MCKIN-29429 Version bump xblock-group-project-v2

---

requirements/edx/custom.txt

RC: https://openedx.atlassian.net/wiki/spaces/MCKA/pages/2289664057/2021-01-22+McKA+Release+Checklist+v1.59.2

Release v1.59.2

---

.circleci/config.yml
common/lib/xmodule/xmodule/contentstore/mongo.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/modulestore/mongo/base.py
common/lib/xmodule/xmodule/modulestore/mongo/draft.py
common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
common/lib/xmodule/xmodule/modulestore/tests/factories.py
common/lib/xmodule/xmodule/modulestore/tests/test_mongo_call_count.py
common/lib/xmodule/xmodule/modulestore/tests/test_split_mongo_mongo_connection.py
common/lib/xmodule/xmodule/mongo_utils.py
lms/djangoapps/dashboard/git_import.py
lms/djangoapps/dashboard/sysadmin.py
lms/djangoapps/verify_student/tests/test_services.py
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/paver.in
requirements/edx/paver.txt
requirements/edx/testing.txt

Fix for Pymongo upgrade.
Here are the related tickets:
https://openedx.atlassian.net/browse/YONK-1904
https://openedx.atlassian.net/browse/YONK-1905
https://edx-wiki.atlassian.net/browse/MCKIN-29930
https://edx-wiki.atlassian.net/browse/MCKIN-29928

Releasing v1.59.2 - rc/2022-01-28 to stage

---

requirements/edx/custom.txt

MCKIN-29786 GPV2 VB

---

requirements/edx/custom.txt

MCKIN-30011 projects-edx-platform-extensions version bump

---

.circleci/config.yml

It will build to the integration as taking [MCKIN-29700](https://github.com/edx-solutions/api-integration/pull/324) to juniper to complete post-prod steps.

MCKIN-29700 to juniper

---

requirements/edx/custom.txt

YONK-1914 | Fixed Intermittently Unit/Module bar is missing for the lesson.

---

requirements/edx/custom.txt

MCKIN-29542 xblock eoc journal vb

---

requirements/edx/custom.txt

This should fix issues with progress notifications

Bump openedx-completion-aggregator to 3.0.3

---

requirements/edx/custom.txt

MCKIN-30997 - Gradebook version bump

---

cms/djangoapps/contentstore/tests/test_libraries.py
cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/library.py
cms/djangoapps/contentstore/views/tests/test_library.py
cms/djangoapps/contentstore/views/user.py
cms/djangoapps/course_creators/admin.py
cms/djangoapps/course_creators/models.py
cms/djangoapps/course_creators/tests/test_admin.py
cms/djangoapps/course_creators/tests/test_views.py
cms/djangoapps/course_creators/views.py
cms/envs/common.py
lms/envs/common.py
requirements/edx/custom.txt

cherry picked the required commits from backup-ironwood-development branch to development branch 
https://edx-wiki.atlassian.net/browse/MCKIN-31645

MCKIN-31645 cherry picked the required commits from backup-ironwood-development branch to development branch 

---

lms/djangoapps/instructor_analytics/basic.py
lms/djangoapps/instructor_task/models.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tasks_helper/utils.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py

Cherry picking #2060 into development

MCKIN-24491 - Cherry pick commit into development

---

requirements/edx/custom.txt

MCKIN-30999 api-integration version bump

---

requirements/edx/custom.txt

Version bump for api-integration and adventure xblock

MCKIN 31645 - Version bump for api-integration and adventure xblock

---

cms/djangoapps/contentstore/views/component.py
cms/templates/container.html

This PR is a cherry-pick of changes in edx#25537

[MCKIN-26432] [BB-3158] Add Unit & Nested blocks to breadcrumbs

---

cms/djangoapps/contentstore/tests/test_libraries.py
cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/library.py
cms/djangoapps/contentstore/views/tests/test_library.py
cms/djangoapps/contentstore/views/user.py
cms/djangoapps/course_creators/admin.py
cms/djangoapps/course_creators/models.py
cms/djangoapps/course_creators/tests/test_admin.py
cms/djangoapps/course_creators/tests/test_views.py
cms/djangoapps/course_creators/views.py
cms/envs/common.py
common/lib/xmodule/xmodule/modulestore/xml.py
lms/djangoapps/courseware/user_state_client.py
lms/djangoapps/instructor_analytics/basic.py
lms/djangoapps/instructor_task/models.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tasks_helper/utils.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py
lms/envs/common.py
openedx/core/djangoapps/course_groups/cohorts.py
openedx/core/djangoapps/course_groups/tests/test_cohorts.py
requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/custom.txt
requirements/edx/development.txt
requirements/edx/testing.txt

RC: https://openedx.atlassian.net/wiki/spaces/MCKA/pages/2554658980/2021-03-30+McKA+Release+Checklist+v1.62.0

[v1.62.0] Review sync up of master branch with release-candidate

---

common/djangoapps/third_party_auth/saml.py

Handled attributes values that store in form of strings.

MEI-6830 handled attributes values that store except list

---

requirements/edx/custom.txt

MEI-7001 problem builder version bump

---

common/djangoapps/database_fixups/migrations/0003_remove_foreign_keys_from_edx_django_oauth2_provider.py
requirements/edx/custom.txt

RC: https://itdocs.intranet.mckinsey.com/pages/viewpage.action?pageId=163973079

[v1.62.3] Review sync up of master branch with release-candidate

---

requirements/edx/custom.txt

MEI-7607-7616 Version Bump

---

requirements/edx/custom.txt

Reverts edx-solutions/edx-platform#2149

Revert "MEI-7607-7616 Version Bump"

---

openedx/core/djangoapps/content_libraries/permissions.py
requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Reverts edx-solutions/edx-platform#2150

Revert "Bridgekeeper upgrade"

---

requirements/edx/custom.txt

MEI-7607 and MEI-7616 version bump

---

lms/djangoapps/courseware/user_state_client.py
lms/djangoapps/instructor_analytics/basic.py
lms/djangoapps/instructor_analytics/tests/test_basic.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py
requirements/edx/custom.txt

RC: [https://itdocs.intranet.mckinsey.com/pages/viewpage.action?pageId=173408594](https://itdocs.intranet.mckinsey.com/pages/viewpage.action?pageId=173408594)

[v1.62.5] Review sync up of master branch with release-candidate
